from django.utils.translation import gettext_lazy as _

class PhysicalInfoHelpText:
    HEIGHT = _("Enter the height of the user in centimeters.")
    WEIGHT = _("Enter the weight of the user in kilograms.")
    GLASSES = _("Does the user wear glasses?")
    GLASSES_SIZE = _("Enter the size of the glasses if applicable.")
    DISEASE_OR_SURGERY = _("Has the user had any disease or surgery?")
    MEDICATION_SURGERY_DISEASE_TYPE = _("Specify the type of medication, surgery, or disease if applicable.")

class PersonalInfoHelpText:
    GENDER = _("Select the gender of the user.")
    MILITARY_STATUS_EXPLANATION = _("Provide an explanation for the military status if applicable.")
    INCOME = _("Enter the income of the user.")
    DEPOSIT = _("Enter the deposit amount of the user.")
    INSURANCE_YEARS = _("Enter the number of years the user has had insurance.")
    CONVICTION_OR_ARREST_HISTORY = _("Does the user have a conviction or arrest history?")
    CONVICTION_REASON = _("Specify the reason for the conviction if applicable.")

class FinancialInfoHelpText:
    CURRENT_RESIDENCE_STATUS = _("Select the current residence status of the user.")
    OWNERSHIP_STATUS = _("Select the ownership status of the residence.")
    RENT_AMOUNT = _("Enter the rent amount in the local currency.")
    MORTGAGE_AMOUNT = _("Enter the mortgage amount in the local currency.")
    CAPITAL = _("Select the types of capital owned by the user.")
    AFTER_MARRIAGE_RESIDENCE_STATUS = _("Select the residence status after marriage.")
    EX_SPOUSE_FINANCIAL_STATUS = _("Select the financial status with the ex-spouse.")
    EX_SPOUSE_FINANCIAL_AMOUNT = _("Enter the financial amount related to the ex-spouse.")
    EX_SPOUSE_FINANCIAL_PAY_STATUS = _("Select the payment status for the ex-spouse financial amount.")
    DOWRY_TYPE = _("Select the type of dowry.")
    DOWRY_AMOUNT = _("Enter the dowry amount in the local currency or gold.")
    TOCHER = _("Select the type of dowry gifts.")
    AGREEMENT_ID = _("Unique identifier for the financial agreement.")
    USER = _("Select the user associated with this financial information.")

class AccessCodeHelpText:
    CODE = _("Unique access code for user creation.")
    ACTIVE = _("Indicates whether the access code is active.")
    DATE_CREATED = _("The date and time when the access code was created.")

class FamilyInfoHelpText:
    EX_HUSBAND_CHILD_STATUS = _("Check the box if you have child from ex husband")
    AVERAGE_FAMILY_EDUCATION = _("Select the average family education level.")
    AVERAGE_FAMILY_FINANCE = _("Select the average family financial status.")
    FAMILY_DIVORCE_HISTORY = _("Indicate if there is a history of divorce in the family.")
    FAMILY_DIVORCE_REASON = _("Specify the reason for the family divorce if applicable.")
    CONTACT_WITH_FAMILY = _("Describe the contact with the family.")
    USER = _("Select the user associated with this family information.")
    STATUS = _("Select the engagement or wedding status.")
    CONTRACT_LENGTH = _("Enter the length of the contract.")
    LIVING_LENGTH = _("Enter the length of living together.")
    DEATH_DATE = _("Enter the death date if applicable.")
    DIVORCE_DATE = _("Enter the divorce date if applicable.")
    REASON_FOR_DIVORCE_OR_DEATH = _("Specify the reason for divorce or death if applicable.")
    GIRL_BIRTH_DATE = _("Enter the birth date of the girl if applicable.")
    BOY_BIRTH_DATE = _("Enter the birth date of the boy if applicable.")
    CUSTODY = _("Select the custody status of the children.")
    LIVING_LOCATION = _("Enter the living location if applicable.")
    EDUCATION = _("Select the education level of the family member.")
    JOB = _("Select the job of the family member.")
    LANGUAGE = _("Enter the language spoken by the parent.")
    BIRTH_DATE = _("Enter the birth date of the parent.")
    ORIGINALITY = _("Enter the originality of the parent.")
    ALIVE = _("Indicate if the parent is alive.")
    DEATH_DATE_PARENT = _("Enter the death date of the parent if applicable.")

class IdentityInfoHelpText:
    FIRST_NAME = _("Enter the first name of the user.")
    LAST_NAME = _("Enter the last name of the user.")
    FATHER_NAME = _("Enter the father's name of the user.")
    EITTA_NUMBER = _("Enter a unique Eitta number in the format: +98 or 09**.")
    LANDLINE_PHONE = _("Enter a landline number in the format: 025-32305083.")
    MOTHER_PHONE = _("Enter a unique phone number for the mother in the format: +98 or 09**.")
    FATHER_PHONE = _("Enter a unique phone number for the father in the format: +98 or 09**.")
    HOME_ADDRESS = _("Enter the home address of the user.")
    WORK_ADDRESS = _("Enter the work address of the user.")
    ORIGINALITY = _("Enter the originality of the user.")
    EDUCATION = _("Enter the education level of the user.")
    JOB = _("Select the job of the user.")
    INSURANCE = _("Select the insurance type of the user.")
    INCOME = _("Enter the income of the user in Rials.")
    ASSETS = _("Enter the assets of the user.")
    WEIGHT = _("Enter the weight of the user in kilograms.")
    HEIGHT = _("Enter the height of the user in centimeters.")
    INTRODUCED_SUBJECTS = _("Select the user who introduced the subjects.")
    PREFERED_MEETING_TIME = _("Enter the preferred meeting time of the user.")
    TYPE_OF_PAYMENT = _("Select the type of payment.")
    USER = _("Select the user associated with this identity information.")

class BirthCertificateInfoHelpText:
    NATIONAL_CODE = _("Enter the national code of the user.")
    BIRTH_CERTIFICATE_SERIAL = _("Enter the birth certificate serial number of the user.")
    BIRTH_CERTIFICATE_LOCATION = _("Enter the location where the birth certificate was issued.")
    MARRIAGE_EXPERINCE = _("Select the marriage experience of the user.")
    CONTRACT_DATE = _("Enter the contract date.")
    MARRIAGE_STATUS = _("Select the marriage status of the user.")
    MARRIAGE_DATE = _("Enter the marriage date.")
    DIVORCE_DATE = _("Enter the divorce date.")
    HUSBAND_DEATH_DATE = _("Enter the husband death date.")
    BIRTH_DATE = _("Enter the birth date of the user.")
    CHILDREN = _("Select the number of children.")
    CHILDREN_CUSTODY = _("Select the custody status of the children.")
    USER = _("Select the user associated with this birth certificate information.")

class UserHelpText:
    ID = _("Unique identifier for the user.")
    ACCESS_CODE = _("Required access code for initial user creation.")
    MIDDLE_MAN_CODE = _("Optional code for middle man reference.")
    USERNAME = _("Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.")
    FIRST_NAME = _("Optional. 150 characters or fewer.")
    LAST_NAME = _("Optional. 150 characters or fewer.")
    DATE_CREATED = _("The date and time when the user was created.")
    PHONE_NUMBER = _("Required. +98 or 09** format accepted.")
    EMAIL = _("Required. Email format accepted.")
    IS_STAFF = _("Designates whether the user can log into this admin site.")
    IS_ACTIVE = _("Designates whether this user should be treated as active. Unselect this instead of deleting accounts.")
    DATE_JOINED = _("The date and time when the user joined.")
