# Generated by Django 4.2.13 on 2024-12-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscode',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='accesscode',
            name='date_used',
        ),
        migrations.RemoveField(
            model_name='accesscode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='accesscode',
            name='used_by_who',
        ),
        migrations.AddField(
            model_name='accesscode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
