# Generated by Django 4.2.13 on 2024-12-21 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_accesscode_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_code',
            field=models.UUIDField(default=uuid.uuid4, help_text='Required, UUID Access Code Field', unique=True, verbose_name='Access code'),
        ),
    ]
