# Generated by Django 4.2.13 on 2024-12-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.UUIDField(help_text='Required, UUID Access Code Field', unique=True, verbose_name='Access code'),
        ),
    ]
