# Generated by Django 4.2.13 on 2024-12-21 19:52

from django.db import migrations, models
import users.user_related_models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.UUIDField(help_text='Required, UUID Access Code Field', unique=True, validators=[users.user_related_models.validate_active_access_code], verbose_name='Access code'),
        ),
    ]
