# Generated by Django 4.2.13 on 2024-12-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_access_code'),
    ]