# Generated by Django 4.2.13 on 2024-12-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.OneToOneField(blank=True, help_text='Required access code for user authentication.', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.accesscode', verbose_name='Access Code'),
        ),
    ]
