# Generated by Django 4.2.13 on 2024-12-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.CharField(blank=True, help_text='Required access code for user authentication.', max_length=50, null=True, verbose_name='Access code'),
        ),
    ]
