# Generated by Django 4.2.13 on 2024-12-26 11:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.CharField(help_text='Required access code for user authentication.', max_length=50, validators=[users.models.validate_active_access_code], verbose_name='Access code'),
        ),
    ]
