# Generated by Django 4.2.13 on 2024-12-26 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
    ]
