# Generated by Django 4.2.13 on 2024-12-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_accesscode_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_access_codes', to=settings.AUTH_USER_MODEL, verbose_name='Used by'),
        ),
    ]
