# Generated by Django 4.2.13 on 2024-12-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_accesscode_used_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscode',
            old_name='used_by',
            new_name='creator',
        ),
    ]
