# Generated by Django 4.2.13 on 2024-12-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_used_by_accesscode_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscode',
            name='creator',
        ),
    ]
