# Generated by Django 4.2.13 on 2024-12-26 11:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_accesscode_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.CharField(blank=True, help_text='Required access code for initial user creation.', max_length=50, null=True, validators=[users.models.validate_active_access_code], verbose_name='Access code'),
        ),
    ]
