# Generated by Django 4.2.13 on 2024-12-26 12:07

from django.db import migrations, models
import users.user_related_models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.CharField(help_text='Required access code for initial user creation.', max_length=50, validators=[users.user_related_models.validate_active_access_code], verbose_name='Access code'),
        ),
    ]
