# Generated by Django 4.2.13 on 2024-12-28 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 10, 49, 16, 486700, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
