# Generated by Django 4.2.13 on 2024-12-28 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
from core.utils.validators.user_validators import ConfidentialInfoValidator

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 12, 46, 16, 282105, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='IdentityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=80, verbose_name="Father's Name")),
                ('eitta_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, verbose_name='Eitta Number')),
                ('landline_phone', models.CharField(help_text='Enter a landline number in the format: 025-32305083', max_length=12, validators=[ConfidentialInfoValidator.landline_number_validator], verbose_name='Landline Phone')),
                ('mother_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, verbose_name="Mother's Phone")),
                ('father_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, verbose_name="Father's Phone")),
                ('home_address', models.CharField(max_length=150, verbose_name='Home Address')),
                ('work_address', models.CharField(max_length=150, verbose_name='Work Address')),
                ('originality', models.CharField(max_length=80, verbose_name='Originality')),
                ('education', models.CharField(max_length=80, verbose_name='Education')),
                ('job', multiselectfield.db.fields.MultiSelectField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], max_length=137, verbose_name='Job')),
                ('insurance', multiselectfield.db.fields.MultiSelectField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('other', 'Other')], max_length=46, verbose_name='Insurance')),
                ('income', models.BigIntegerField(verbose_name='Income in Rials')),
                ('assets', models.CharField(max_length=150, verbose_name='Assets')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (in kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height (in cm)')),
                ('prefered_meeting_time', models.CharField(max_length=150, verbose_name='Prefered Meeting Time')),
                ('type_of_payment', multiselectfield.db.fields.MultiSelectField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=11, verbose_name='Type of payment')),
                ('introduced_subjects', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confidintional_info_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Introduced Subjects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confidintional_info_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'IdentityInfo',
                'verbose_name_plural': 'IdentityInfos',
            },
        ),
        migrations.CreateModel(
            name='BirthCertificateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='National Code')),
                ('birth_certificate_serial', models.CharField(max_length=10, verbose_name='Birth Certificate Serial')),
                ('birth_certificate_location', models.CharField(max_length=50, verbose_name='Birth Certificate Location')),
                ('marriage_experince', multiselectfield.db.fields.MultiSelectField(choices=[('yes', 'Yes'), ('no', 'No'), ('engagement_only', 'Engagement Only')], max_length=22, verbose_name='Marriage Experince')),
                ('contract_date', models.DateTimeField(blank=True, null=True, verbose_name='Contract Date')),
                ('marriage_status', multiselectfield.db.fields.MultiSelectField(choices=[('husband', 'Husband'), ('blank_birth_certificate', 'Blank Birth Certificate')], max_length=31, verbose_name='Marriage Status')),
                ('marriage_date', models.DateTimeField(blank=True, null=True, verbose_name='Marriage Date')),
                ('divorce_date', models.DateTimeField(blank=True, null=True, verbose_name='Divorce Date')),
                ('husband_death_date', models.DateTimeField(blank=True, null=True, verbose_name='Husband Death Date')),
                ('birth_date', models.DateTimeField(verbose_name='Birth Date')),
                ('children', multiselectfield.db.fields.MultiSelectField(choices=[('one_boy', 'One Boy'), ('two_boys', 'Two Boys'), ('three_boys', 'Three Boys'), ('one_girl', 'One Girl'), ('two_girls', 'Two Girls'), ('three_girls', 'Three Girls'), ('one_boy_one_girl', 'One Boy, One Girl'), ('one_boy_two_girls', 'One Boy, Two Girls'), ('two_boys_one_girl', 'Two Boys, One Girl'), ('two_boys_two_girls', 'Two Boys, Two Girls'), ('three_boys_one_girl', 'Three Boys, One Girl'), ('one_boy_three_girls', 'One Boy, Three Girls'), ('three_boys_two_girls', 'Three Boys, Two Girls'), ('two_boys_three_girls', 'Two Boys, Three Girls'), ('three_boys_three_girls', 'Three Boys, Three Girls')], max_length=235, verbose_name='Children')),
                ('children_custody', multiselectfield.db.fields.MultiSelectField(choices=[('father', 'Father'), ('mother', 'Mother')], max_length=13, verbose_name='Children Custody')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_certificate_info', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'BirthCertificateInfo',
                'verbose_name_plural': 'BirthCertificateInfos',
            },
        ),
    ]
