# Generated by Django 4.2.13 on 2024-12-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_date_joined_identityinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='children_custody',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother')], max_length=50, verbose_name='Children Custody'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='marriage_experince',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('engagement_only', 'Engagement Only')], max_length=50, verbose_name='Marriage Experince'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='marriage_status',
            field=models.CharField(choices=[('husband', 'Husband'), ('blank_birth_certificate', 'Blank Birth Certificate')], max_length=50, verbose_name='Marriage Status'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='insurance',
            field=models.CharField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('other', 'Other')], max_length=50, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='job',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='type_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, verbose_name='Type of payment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 12, 55, 26, 49234, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
