# Generated by Django 4.2.13 on 2024-12-28 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_birthcertificateinfo_children_custody_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinfo',
            name='introduced_subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confidintional_info_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Introduced Subjects'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 12, 58, 39, 624972, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
