# Generated by Django 4.2.13 on 2024-12-28 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_identityinfo_introduced_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 15, 14, 31, 677242, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
