# Generated by Django 4.2.13 on 2024-12-29 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import phonenumber_field.modelfields
import users.models.access_code_model
from core.utils import validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='active',
            field=models.BooleanField(default=True, error_messages={'blank': 'Active status cannot be blank.', 'invalid': 'Active status is invalid.', 'null': 'Active status cannot be null.'}, help_text='Indicates whether the access code is active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, error_messages={'blank': 'Access code cannot be blank.', 'invalid': 'Access code is invalid.', 'null': 'Access code cannot be null.', 'unique': 'This access code is already taken.'}, help_text='Unique access code for user creation.', verbose_name='Access Code'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, error_messages={'blank': 'Date created cannot be blank.', 'invalid': 'Date created is invalid.', 'null': 'Date created cannot be null.'}, help_text='The date and time when the access code was created.', verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='birth_certificate_location',
            field=models.CharField(error_messages={'blank': 'Birth certificate location cannot be blank.', 'max_length': 'Birth certificate location cannot exceed 50 characters.', 'null': 'Birth certificate location cannot be null.'}, help_text='Enter the location where the birth certificate was issued.', max_length=50, verbose_name='Birth Certificate Location'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='birth_certificate_serial',
            field=models.CharField(error_messages={'blank': 'Birth certificate serial cannot be blank.', 'max_length': 'Birth certificate serial cannot exceed 10 characters.', 'null': 'Birth certificate serial cannot be null.'}, help_text='Enter the birth certificate serial number of the user.', max_length=10, verbose_name='Birth Certificate Serial'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='birth_date',
            field=models.DateTimeField(error_messages={'blank': 'Birth date cannot be blank.', 'invalid': 'Birth date is invalid.', 'null': 'Birth date cannot be null.'}, help_text='Enter the birth date of the user.', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='children',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('one_boy', 'One Boy'), ('two_boys', 'Two Boys'), ('three_boys', 'Three Boys'), ('one_girl', 'One Girl'), ('two_girls', 'Two Girls'), ('three_girls', 'Three Girls'), ('one_boy_one_girl', 'One Boy, One Girl'), ('one_boy_two_girls', 'One Boy, Two Girls'), ('two_boys_one_girl', 'Two Boys, One Girl'), ('two_boys_two_girls', 'Two Boys, Two Girls'), ('three_boys_one_girl', 'Three Boys, One Girl'), ('one_boy_three_girls', 'One Boy, Three Girls'), ('three_boys_two_girls', 'Three Boys, Two Girls'), ('two_boys_three_girls', 'Two Boys, Three Girls'), ('three_boys_three_girls', 'Three Boys, Three Girls')], error_messages={'blank': 'Children cannot be blank.', 'invalid': 'Children is invalid.', 'null': 'Children cannot be null.'}, help_text='Select the number of children.', max_length=240, verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='children_custody',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother')], error_messages={'blank': 'Children custody cannot be blank.', 'invalid': 'Children custody is invalid.', 'null': 'Children custody cannot be null.'}, help_text='Select the custody status of the children.', max_length=50, null=True, verbose_name='Children Custody'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='contract_date',
            field=models.DateTimeField(blank=True, error_messages={'blank': 'Contract date cannot be blank.', 'invalid': 'Contract date is invalid.', 'null': 'Contract date cannot be null.'}, help_text='Enter the contract date.', null=True, verbose_name='Contract Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='divorce_date',
            field=models.DateTimeField(blank=True, error_messages={'blank': 'Divorce date cannot be blank.', 'invalid': 'Divorce date is invalid.', 'null': 'Divorce date cannot be null.'}, help_text='Enter the divorce date.', null=True, verbose_name='Divorce Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='husband_death_date',
            field=models.DateTimeField(blank=True, error_messages={'blank': 'Husband death date cannot be blank.', 'invalid': 'Husband death date is invalid.', 'null': 'Husband death date cannot be null.'}, help_text='Enter the husband death date.', null=True, verbose_name='Husband Death Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='marriage_date',
            field=models.DateTimeField(blank=True, error_messages={'blank': 'Marriage date cannot be blank.', 'invalid': 'Marriage date is invalid.', 'null': 'Marriage date cannot be null.'}, help_text='Enter the marriage date.', null=True, verbose_name='Marriage Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='marriage_experince',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('engagement_only', 'Engagement Only')], error_messages={'blank': 'Marriage experience cannot be blank.', 'invalid': 'Marriage experience is invalid.', 'null': 'Marriage experience cannot be null.'}, help_text='Select the marriage experience of the user.', max_length=50, verbose_name='Marriage Experince'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='marriage_status',
            field=models.CharField(choices=[('husband', 'Husband'), ('blank_birth_certificate', 'Blank Birth Certificate')], error_messages={'blank': 'Marriage status cannot be blank.', 'invalid': 'Marriage status is invalid.', 'null': 'Marriage status cannot be null.'}, help_text='Select the marriage status of the user.', max_length=50, verbose_name='Marriage Status'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='national_code',
            field=models.CharField(error_messages={'blank': 'National code cannot be blank.', 'max_length': 'National code cannot exceed 10 characters.', 'null': 'National code cannot be null.', 'unique': 'This national code is already taken.'}, help_text='Enter the national code of the user.', max_length=10, unique=True, verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='user',
            field=models.OneToOneField(error_messages={'blank': 'User cannot be blank.', 'invalid': 'User is invalid.', 'null': 'User cannot be null.'}, help_text='Select the user associated with this birth certificate information.', on_delete=django.db.models.deletion.CASCADE, related_name='birth_certificate_info', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='assets',
            field=models.CharField(error_messages={'blank': 'Assets cannot be blank.', 'max_length': 'Assets cannot exceed 150 characters.', 'null': 'Assets cannot be null.'}, help_text='Enter the assets of the user.', max_length=150, verbose_name='Assets'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='education',
            field=models.CharField(error_messages={'blank': 'Education cannot be blank.', 'max_length': 'Education cannot exceed 80 characters.', 'null': 'Education cannot be null.'}, help_text='Enter the education level of the user.', max_length=80, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='eitta_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'blank': 'Eitta number cannot be blank.', 'invalid': 'Eitta number is invalid.', 'null': 'Eitta number cannot be null.', 'unique': 'This Eitta number is already taken.'}, help_text='Enter a unique Eitta number in the format: +98 or 09**.', max_length=128, null=True, region='IR', unique=True, verbose_name='Eitta Number'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='father_name',
            field=models.CharField(error_messages={'blank': "Father's name cannot be blank.", 'max_length': "Father's name cannot exceed 80 characters.", 'null': "Father's name cannot be null."}, help_text='Optional. 80 characters or fewer.', max_length=80, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='father_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'blank': "Father's phone number cannot be blank.", 'invalid': "Father's phone number is invalid.", 'null': "Father's phone number cannot be null.", 'unique': "This father's phone number is already taken."}, help_text='Enter a unique phone number for the father in the format: +98 or 09**.', max_length=128, null=True, region='IR', unique=True, verbose_name="Father's Phone"),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'First name cannot be blank.', 'max_length': 'First name cannot exceed 80 characters.', 'null': 'First name cannot be null.'}, help_text='Enter the first name of the user.', max_length=80, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='height',
            field=models.DecimalField(decimal_places=2, error_messages={'blank': 'Height cannot be blank.', 'invalid': 'Height is invalid.', 'null': 'Height cannot be null.'}, help_text='Enter the height of the user in centimeters.', max_digits=5, verbose_name='Height (in cm)'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='home_address',
            field=models.CharField(error_messages={'blank': 'Home address cannot be blank.', 'max_length': 'Home address cannot exceed 150 characters.', 'null': 'Home address cannot be null.'}, help_text='Enter the home address of the user.', max_length=150, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='income',
            field=models.BigIntegerField(error_messages={'blank': 'Income cannot be blank.', 'invalid': 'Income is invalid.', 'null': 'Income cannot be null.'}, help_text='Enter the income of the user in Rials.', verbose_name='Income in Rials'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='insurance',
            field=models.CharField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('other', 'Other')], error_messages={'blank': 'Insurance cannot be blank.', 'invalid': 'Insurance is invalid.', 'null': 'Insurance cannot be null.'}, help_text='Select the insurance type of the user.', max_length=50, verbose_name='Insurance'),
        ),
        migrations.RemoveField(
            model_name='identityinfo',
            name='introduced_subjects',
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='job',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], error_messages={'blank': 'Job cannot be blank.', 'invalid': 'Job is invalid.', 'null': 'Job cannot be null.'}, help_text='Select the job of the user.', max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='landline_phone',
            field=models.CharField(blank=True, error_messages={'blank': 'Landline phone cannot be blank.', 'invalid': 'Landline phone is invalid.', 'null': 'Landline phone cannot be null.'}, help_text='Enter a landline number in the format: 025-32305083.', max_length=12, null=True, validators=[validators.LandlineNumberValidator.landline_number_validator], verbose_name='Landline Phone'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'Last name cannot be blank.', 'max_length': 'Last name cannot exceed 50 characters.', 'null': 'Last name cannot be null.'}, help_text='Optional. 50 characters or fewer.', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='mother_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'blank': "Mother's phone number cannot be blank.", 'invalid': "Mother's phone number is invalid.", 'null': "Mother's phone number cannot be null.", 'unique': "This mother's phone number is already taken."}, help_text='Enter a unique phone number for the mother in the format: +98 or 09**.', max_length=128, null=True, region='IR', unique=True, verbose_name="Mother's Phone"),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='originality',
            field=models.CharField(error_messages={'blank': 'Originality cannot be blank.', 'max_length': 'Originality cannot exceed 80 characters.', 'null': 'Originality cannot be null.'}, help_text='Enter the originality of the user.', max_length=80, verbose_name='Originality'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='prefered_meeting_time',
            field=models.CharField(error_messages={'blank': 'Preferred meeting time cannot be blank.', 'max_length': 'Preferred meeting time cannot exceed 150 characters.', 'null': 'Preferred meeting time cannot be null.'}, help_text='Enter the preferred meeting time of the user.', max_length=150, verbose_name='Prefered Meeting Time'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='type_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], error_messages={'blank': 'Type of payment cannot be blank.', 'invalid': 'Type of payment is invalid.', 'null': 'Type of payment cannot be null.'}, help_text='Select the type of payment.', max_length=20, verbose_name='Type of payment'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='user',
            field=models.OneToOneField(error_messages={'blank': 'User cannot be blank.', 'invalid': 'User is invalid.', 'null': 'User cannot be null.'}, help_text='Select the user associated with this identity information.', on_delete=django.db.models.deletion.CASCADE, related_name='confidintional_info_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='weight',
            field=models.DecimalField(decimal_places=2, error_messages={'blank': 'Weight cannot be blank.', 'invalid': 'Weight is invalid.', 'null': 'Weight cannot be null.'}, help_text='Enter the weight of the user in kilograms.', max_digits=5, verbose_name='Weight (in kg)'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='work_address',
            field=models.CharField(blank=True, error_messages={'blank': 'Work address cannot be blank.', 'max_length': 'Work address cannot exceed 150 characters.', 'null': 'Work address cannot be null.'}, help_text='Enter the work address of the user.', max_length=150, null=True, verbose_name='Work Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.CharField(error_messages={'blank': 'Access code cannot be blank.', 'invalid': 'Access code is invalid.', 'null': 'Access code cannot be null.'}, help_text='Required access code for initial user creation.', max_length=50, validators=[validators.validate_active_access_code], verbose_name='Access code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, error_messages={'blank': 'Date created cannot be blank.', 'invalid': 'Date created is invalid.', 'null': 'Date created cannot be null.'}, help_text='The date and time when the user was created.', verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.localtime, error_messages={'blank': 'Date joined cannot be blank.', 'invalid': 'Date joined is invalid.', 'null': 'Date joined cannot be null.'}, help_text='The date and time when the user joined.', verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'Email cannot be blank.', 'invalid': 'Email is invalid.', 'null': 'Email cannot be null.', 'unique': 'This email is already taken.'}, help_text='Required. Email format accepted.', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'blank': 'First name cannot be blank.', 'max_length': 'First name cannot exceed 150 characters.', 'null': 'First name cannot be null.'}, help_text='Optional. 150 characters or fewer.', max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, error_messages={'blank': 'Active status cannot be blank.', 'invalid': 'Active status is invalid.', 'null': 'Active status cannot be null.'}, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, error_messages={'blank': 'Staff status cannot be blank.', 'invalid': 'Staff status is invalid.', 'null': 'Staff status cannot be null.'}, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, error_messages={'blank': 'Last name cannot be blank.', 'max_length': 'Last name cannot exceed 150 characters.', 'null': 'Last name cannot be null.'}, help_text='Optional. 150 characters or fewer.', max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_man_code',
            field=models.UUIDField(blank=True, error_messages={'blank': 'Middle man code cannot be blank.', 'invalid': 'Middle man code is invalid.', 'null': 'Middle man code cannot be null.'}, help_text='Optional code for middle man reference.', null=True, verbose_name='Middle man code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'blank': 'Phone number cannot be blank.', 'invalid': 'Phone number is invalid.', 'null': 'Phone number cannot be null.', 'unique': 'This phone number is already taken.'}, help_text='Required. +98 or 09** format accepted.', max_length=128, region='IR', unique=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='identityinfo',
            name='introduced_subjects',
            field=models.ManyToManyField(blank=True, error_messages={'blank': 'Introduced subjects cannot be blank.', 'invalid': 'Introduced subjects is invalid.', 'null': 'Introduced subjects cannot be null.'}, help_text='Select the user who introduced the subjects.', related_name='confidintional_info_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Introduced Subjects'),
        ),
    ]
