# Generated by Django 4.2.13 on 2025-01-02 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_accesscode_active_alter_accesscode_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.BigIntegerField(error_messages={'invalid': 'Invalid height value.', 'max_value': 'Height cannot exceed 260 cm.', 'required': 'Height is required.'})),
                ('weight', models.BigIntegerField(error_messages={'invalid': 'Invalid weight value.', 'max_value': 'Weight cannot exceed 300 kg.', 'required': 'Weight is required.'})),
                ('skin_color', models.CharField(choices=[('Very Bright', 'Very Bright'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Date', 'Date'), ('Green', 'Green'), ('Dark', 'Dark')], error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, max_length=20)),
                ('eyes_color', models.CharField(choices=[('Green', 'Green'), ('Light Blue', 'Light Blue'), ('Hazel', 'Hazel'), ('Darken Blue', 'Darken Blue'), ('Grey', 'Grey'), ('Honey', 'Honey'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Black', 'Black')], error_messages={'invalid_choice': 'Invalid choice for eyes color.', 'required': 'Eyes color is required.'}, max_length=20)),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], error_messages={'invalid_choice': 'Invalid choice for blood type.', 'required': 'Blood type is required.'}, max_length=3)),
                ('character_and_temperament', models.CharField(choices=[('Safravi', 'Safravi (Hot & Dry)'), ('Damvi', 'Damvi (Hot & Wet)'), ('Sodavi', 'Sodavi (Cold & Dry)'), ('Balghami', 'Balghami (Cold & Wet)')], error_messages={'invalid_choice': 'Invalid choice for character and temperament.', 'required': 'Character and temperament is required.'}, max_length=20)),
                ('glasses', models.BooleanField(error_messages={'required': 'Glasses field is required.'})),
                ('glasses_size', models.IntegerField(blank=True, error_messages={'invalid': 'Invalid glasses size value.'}, null=True)),
                ('body_and_face', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Suitable', 'Suitable'), ('Nice Face', 'Nice Face'), ('Nice Body', 'Nice Body'), ('Looks Older', 'Looks Older'), ('Looks Younger', 'Looks Younger'), ('Satisfied', 'Satisfied'), ('None', 'None')], error_messages={'invalid_choice': 'Invalid choice for body and face.', 'required': 'Body and face is required.'}, max_length=20)),
                ('disease_or_surgery', models.BooleanField(error_messages={'required': 'Disease or surgery field is required.'})),
                ('medication_surgery_disease_type', models.CharField(blank=True, error_messages={'max_length': 'Medication, surgery, or disease type cannot exceed 100 characters.'}, max_length=100, null=True)),
                ('user', models.OneToOneField(error_messages={'required': 'User is required.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], error_messages={'invalid_choice': 'Invalid choice for gender.', 'required': 'Gender is required.'}, max_length=50)),
                ('sadat', models.BooleanField(error_messages={'required': 'Sadat field is required.'})),
                ('birth_date', models.DateField(error_messages={'invalid': 'Invalid birth date format.', 'required': 'Birth date is required.'})),
                ('birth_location', models.CharField(error_messages={'max_length': 'Birth location cannot exceed 50 characters.', 'required': 'Birth location is required.'}, max_length=50)),
                ('education', models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, max_length=50)),
                ('degree', models.CharField(choices=[('Medical', 'Medical'), ('Engineer', 'Engineer'), ('Human Science', 'Human Science'), ('Hoze Molabas', 'Hoze Molabas'), ('Hoze Not Molabas', 'Hoze Not Molabas'), ('Art', 'Art'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, max_length=50)),
                ('military_status', models.CharField(choices=[('Exemption', 'Exemption'), ('Mother Sponsorship', 'Mother Sponsorship'), ('Father Sponsorship', 'Father Sponsorship'), ('Educational Exemption', 'Educational Exemption'), ('Medical Exemption', 'Medical Exemption'), ('End of Service', 'End of Service')], error_messages={'invalid_choice': 'Invalid choice for military status.', 'required': 'Military status is required.'}, max_length=50)),
                ('military_status_explanation', models.TextField(blank=True, null=True)),
                ('income', models.BigIntegerField(error_messages={'invalid': 'Invalid income value.', 'required': 'Income is required.'})),
                ('deposit', models.BigIntegerField(error_messages={'invalid': 'Invalid deposit value.', 'required': 'Deposit is required.'})),
                ('insurance_type', models.CharField(choices=[('Takmili', 'Takmili'), ('Darmani', 'Darmani'), ('Niro Mosalah (Military Insurance)', 'Niro Mosalah (Military Insurance)'), ('Ommi', 'Ommi')], error_messages={'invalid_choice': 'Invalid choice for insurance type.', 'required': 'Insurance type is required.'}, max_length=50)),
                ('insurance_years', models.PositiveIntegerField(error_messages={'invalid': 'Invalid insurance years value.', 'max_value': 'Insurance years cannot exceed 60.', 'required': 'Insurance years are required.'})),
                ('leisure_type', models.CharField(choices=[('Park', 'Park'), ('Trip', 'Trip'), ('Family', 'Family'), ('Television', 'Television'), ('Mobile Reading', 'Mobile Reading'), ('Shrine', 'Shrine'), ('Jankaran', 'Jankaran'), ('Cinema', 'Cinema'), ('Working in Home', 'Working in Home'), ('Gym', 'Gym'), ('Poem', 'Poem'), ('Garden', 'Garden')], error_messages={'invalid_choice': 'Invalid choice for leisure type.', 'required': 'Leisure type is required.'}, max_length=50)),
                ('usage_cases', models.CharField(choices=[('Alcoholic Drinks', 'Alcoholic Drinks'), ('Drugs', 'Drugs'), ('Cigarettes', 'Cigarettes'), ('Hookah', 'Hookah')], error_messages={'invalid_choice': 'Invalid choice for usage cases.', 'required': 'Usage cases are required.'}, max_length=50)),
                ('conviction_or_arrest_history', models.BooleanField(error_messages={'required': 'Conviction or arrest history is required.'})),
                ('conviction_reason', models.CharField(blank=True, error_messages={'max_length': 'Conviction reason cannot exceed 150 characters.', 'required': 'Conviction reason is required.'}, max_length=150, null=True)),
                ('user', models.OneToOneField(error_messages={'required': 'User is required.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
