# Generated by Django 4.2.13 on 2025-01-02 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_physicalinformation_personalinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificateinfo',
            name='user',
            field=models.OneToOneField(error_messages={'blank': 'User cannot be blank.', 'invalid': 'User is invalid.', 'null': 'User cannot be null.'}, help_text='Select the user associated with this birth certificate information.', on_delete=django.db.models.deletion.CASCADE, related_name='birth_certificate_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='introduced_subjects',
            field=models.ManyToManyField(blank=True, error_messages={'blank': 'Introduced subjects cannot be blank.', 'invalid': 'Introduced subjects is invalid.', 'null': 'Introduced subjects cannot be null.'}, help_text='Select the user who introduced the subjects.', related_name='confidintional_info_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='user',
            field=models.OneToOneField(error_messages={'blank': 'User cannot be blank.', 'invalid': 'User is invalid.', 'null': 'User cannot be null.'}, help_text='Select the user associated with this identity information.', on_delete=django.db.models.deletion.CASCADE, related_name='confidintional_info_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_date',
            field=models.DateField(error_messages={'invalid': 'Invalid birth date format.', 'required': 'Birth date is required.'}, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_location',
            field=models.CharField(error_messages={'max_length': 'Birth location cannot exceed 50 characters.', 'required': 'Birth location is required.'}, max_length=50, verbose_name='Birth Location'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='conviction_or_arrest_history',
            field=models.BooleanField(error_messages={'required': 'Conviction or arrest history is required.'}, verbose_name='Conviction or Arrest History'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='conviction_reason',
            field=models.CharField(blank=True, error_messages={'max_length': 'Conviction reason cannot exceed 150 characters.', 'required': 'Conviction reason is required.'}, max_length=150, null=True, verbose_name='Conviction Reason'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='degree',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineer', 'Engineer'), ('Human Science', 'Human Science'), ('Hoze Molabas', 'Hoze Molabas'), ('Hoze Not Molabas', 'Hoze Not Molabas'), ('Art', 'Art'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, max_length=50, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='deposit',
            field=models.BigIntegerField(error_messages={'invalid': 'Invalid deposit value.', 'required': 'Deposit is required.'}, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], error_messages={'invalid_choice': 'Invalid choice for gender.', 'required': 'Gender is required.'}, help_text='Select the gender of the user.', max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='income',
            field=models.BigIntegerField(error_messages={'invalid': 'Invalid income value.', 'required': 'Income is required.'}, verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_type',
            field=models.CharField(choices=[('Takmili', 'Takmili'), ('Darmani', 'Darmani'), ('Niro Mosalah (Military Insurance)', 'Niro Mosalah (Military Insurance)'), ('Ommi', 'Ommi')], error_messages={'invalid_choice': 'Invalid choice for insurance type.', 'required': 'Insurance type is required.'}, max_length=50, verbose_name='Insurance Type'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_years',
            field=models.PositiveIntegerField(error_messages={'invalid': 'Invalid insurance years value.', 'max_value': 'Insurance years cannot exceed 60.', 'required': 'Insurance years are required.'}, verbose_name='Insurance Years'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='leisure_type',
            field=models.CharField(choices=[('Park', 'Park'), ('Trip', 'Trip'), ('Family', 'Family'), ('Television', 'Television'), ('Mobile Reading', 'Mobile Reading'), ('Shrine', 'Shrine'), ('Jankaran', 'Jankaran'), ('Cinema', 'Cinema'), ('Working in Home', 'Working in Home'), ('Gym', 'Gym'), ('Poem', 'Poem'), ('Garden', 'Garden')], error_messages={'invalid_choice': 'Invalid choice for leisure type.', 'required': 'Leisure type is required.'}, max_length=50, verbose_name='Leisure Type'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='military_status',
            field=models.CharField(choices=[('Exemption', 'Exemption'), ('Mother Sponsorship', 'Mother Sponsorship'), ('Father Sponsorship', 'Father Sponsorship'), ('Educational Exemption', 'Educational Exemption'), ('Medical Exemption', 'Medical Exemption'), ('End of Service', 'End of Service')], error_messages={'invalid_choice': 'Invalid choice for military status.', 'required': 'Military status is required.'}, max_length=50, verbose_name='Military Status'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='military_status_explanation',
            field=models.TextField(blank=True, help_text='Provide an explanation for the military status if applicable.', null=True, verbose_name='Military Status Explanation'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='sadat',
            field=models.BooleanField(error_messages={'required': 'Sadat field is required.'}, verbose_name='Sadat'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='usage_cases',
            field=models.CharField(choices=[('Alcoholic Drinks', 'Alcoholic Drinks'), ('Drugs', 'Drugs'), ('Cigarettes', 'Cigarettes'), ('Hookah', 'Hookah')], error_messages={'invalid_choice': 'Invalid choice for usage cases.', 'required': 'Usage cases are required.'}, max_length=50, verbose_name='Usage Cases'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='blood_type',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], error_messages={'invalid_choice': 'Invalid choice for blood type.', 'required': 'Blood type is required.'}, max_length=3, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='body_and_face',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Suitable', 'Suitable'), ('Nice Face', 'Nice Face'), ('Nice Body', 'Nice Body'), ('Looks Older', 'Looks Older'), ('Looks Younger', 'Looks Younger'), ('Satisfied', 'Satisfied'), ('None', 'None')], error_messages={'invalid_choice': 'Invalid choice for body and face.', 'required': 'Body and face is required.'}, max_length=20, verbose_name='Body and Face'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='character_and_temperament',
            field=models.CharField(choices=[('Safravi', 'Safravi (Hot & Dry)'), ('Damvi', 'Damvi (Hot & Wet)'), ('Sodavi', 'Sodavi (Cold & Dry)'), ('Balghami', 'Balghami (Cold & Wet)')], error_messages={'invalid_choice': 'Invalid choice for character and temperament.', 'required': 'Character and temperament is required.'}, max_length=20, verbose_name='Character and Temperament'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='disease_or_surgery',
            field=models.BooleanField(error_messages={'required': 'Disease or surgery field is required.'}, verbose_name='Disease or Surgery'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='eyes_color',
            field=models.CharField(choices=[('Green', 'Green'), ('Light Blue', 'Light Blue'), ('Hazel', 'Hazel'), ('Darken Blue', 'Darken Blue'), ('Grey', 'Grey'), ('Honey', 'Honey'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Black', 'Black')], error_messages={'invalid_choice': 'Invalid choice for eyes color.', 'required': 'Eyes color is required.'}, max_length=20, verbose_name='Eyes Color'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='glasses',
            field=models.BooleanField(error_messages={'required': 'Glasses field is required.'}, verbose_name='Glasses'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='glasses_size',
            field=models.IntegerField(blank=True, error_messages={'invalid': 'Invalid glasses size value.'}, null=True, verbose_name='Glasses Size'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='height',
            field=models.BigIntegerField(error_messages={'invalid': 'Invalid height value.', 'max_value': 'Height cannot exceed 260 cm.', 'required': 'Height is required.'}, help_text='Enter the height of the user in centimeters.', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='medication_surgery_disease_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'Medication, surgery, or disease type cannot exceed 100 characters.'}, max_length=100, null=True, verbose_name='Medication/Surgery/Disease Type'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='skin_color',
            field=models.CharField(choices=[('Very Bright', 'Very Bright'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Date', 'Date'), ('Green', 'Green'), ('Dark', 'Dark')], error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, max_length=20, verbose_name='Skin Color'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='user',
            field=models.OneToOneField(error_messages={'required': 'User is required.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='weight',
            field=models.BigIntegerField(error_messages={'invalid': 'Invalid weight value.', 'max_value': 'Weight cannot exceed 300 kg.', 'required': 'Weight is required.'}, help_text='Enter the weight of the user in kilograms.', verbose_name='Weight'),
        ),
    ]
