# Generated by Django 4.2.13 on 2025-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_birthcertificateinfo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='conviction_or_arrest_history',
            field=models.BooleanField(error_messages={'required': 'Conviction or arrest history is required.'}, help_text='Does the user have a conviction or arrest history?', verbose_name='Conviction or Arrest History'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='conviction_reason',
            field=models.CharField(blank=True, error_messages={'max_length': 'Conviction reason cannot exceed 150 characters.', 'required': 'Conviction reason is required.'}, help_text='Specify the reason for the conviction if applicable.', max_length=150, null=True, verbose_name='Conviction Reason'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='deposit',
            field=models.BigIntegerField(error_messages={'invalid': 'Invalid deposit value.', 'required': 'Deposit is required.'}, help_text='Enter the deposit amount of the user.', verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='income',
            field=models.BigIntegerField(error_messages={'invalid': 'Invalid income value.', 'required': 'Income is required.'}, help_text='Enter the income of the user.', verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_years',
            field=models.PositiveIntegerField(error_messages={'invalid': 'Invalid insurance years value.', 'max_value': 'Insurance years cannot exceed 60.', 'required': 'Insurance years are required.'}, help_text='Enter the number of years the user has had insurance.', verbose_name='Insurance Years'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='disease_or_surgery',
            field=models.BooleanField(error_messages={'required': 'Disease or surgery field is required.'}, help_text='Has the user had any disease or surgery?', verbose_name='Disease or Surgery'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='glasses',
            field=models.BooleanField(error_messages={'required': 'Glasses field is required.'}, help_text='Does the user wear glasses?', verbose_name='Glasses'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='glasses_size',
            field=models.IntegerField(blank=True, error_messages={'invalid': 'Invalid glasses size value.'}, help_text='Enter the size of the glasses if applicable.', null=True, verbose_name='Glasses Size'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='medication_surgery_disease_type',
            field=models.CharField(blank=True, error_messages={'max_length': 'Medication, surgery, or disease type cannot exceed 100 characters.'}, help_text='Specify the type of medication, surgery, or disease if applicable.', max_length=100, null=True, verbose_name='Medication/Surgery/Disease Type'),
        ),
    ]
