# Generated by Django 4.2.13 on 2025-01-02 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_personalinformation_conviction_or_arrest_history_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BirthCertificateInfo',
            new_name='BirthCertificateInformation',
        ),
        migrations.RenameModel(
            old_name='IdentityInfo',
            new_name='IdentityInformation',
        ),
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personal Informations'},
        ),
        migrations.AlterModelOptions(
            name='physicalinformation',
            options={'verbose_name': 'ModelName', 'verbose_name_plural': 'ModelNames'},
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_date',
            field=models.DateField(error_messages={'invalid': 'Invalid birth date format.', 'required': 'Birth date is required.'}, help_text='Enter the birth date of the user.', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_location',
            field=models.CharField(error_messages={'max_length': 'Birth location cannot exceed 50 characters.', 'required': 'Birth location is required.'}, help_text='Enter the birth location of the user.', max_length=50, verbose_name='Birth Location'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='degree',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineer', 'Engineer'), ('Human Science', 'Human Science'), ('Hoze Molabas', 'Hoze Molabas'), ('Hoze Not Molabas', 'Hoze Not Molabas'), ('Art', 'Art'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the user.', max_length=50, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, help_text='Select the education level of the user.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Takmili', 'Takmili'), ('Darmani', 'Darmani'), ('Niro Mosalah (Military Insurance)', 'Niro Mosalah (Military Insurance)'), ('Ommi', 'Ommi')], error_messages={'invalid_choice': 'Invalid choice for insurance type.', 'required': 'Insurance type is required.'}, help_text='Select the type of insurance the user has.', max_length=54, verbose_name='Insurance Type'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='leisure_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Park', 'Park'), ('Trip', 'Trip'), ('Family', 'Family'), ('Television', 'Television'), ('Mobile Reading', 'Mobile Reading'), ('Shrine', 'Shrine'), ('Jankaran', 'Jankaran'), ('Cinema', 'Cinema'), ('Working in Home', 'Working in Home'), ('Gym', 'Gym'), ('Poem', 'Poem'), ('Garden', 'Garden')], error_messages={'invalid_choice': 'Invalid choice for leisure type.', 'required': 'Leisure type is required.'}, help_text='Select the types of leisure activities the user enjoys.', max_length=97, verbose_name='Leisure Type'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='military_status',
            field=models.CharField(choices=[('Exemption', 'Exemption'), ('Mother Sponsorship', 'Mother Sponsorship'), ('Father Sponsorship', 'Father Sponsorship'), ('Educational Exemption', 'Educational Exemption'), ('Medical Exemption', 'Medical Exemption'), ('End of Service', 'End of Service')], error_messages={'invalid_choice': 'Invalid choice for military status.', 'required': 'Military status is required.'}, help_text='Select the military status of the user.', max_length=50, verbose_name='Military Status'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='sadat',
            field=models.BooleanField(error_messages={'required': 'Sadat field is required.'}, help_text='Is the user a Sadat?', verbose_name='Sadat'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='usage_cases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Alcoholic Drinks', 'Alcoholic Drinks'), ('Drugs', 'Drugs'), ('Cigarettes', 'Cigarettes'), ('Hookah', 'Hookah')], error_messages={'invalid_choice': 'Invalid choice for usage cases.', 'required': 'Usage cases are required.'}, help_text='Select the usage cases applicable to the user.', max_length=40, verbose_name='Usage Cases'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='user',
            field=models.OneToOneField(error_messages={'required': 'User is required.'}, help_text='The user associated with this personal information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('education', models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], max_length=50, verbose_name='Education')),
                ('job', models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], max_length=50, verbose_name='Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sister',
                'verbose_name_plural': 'Sisters',
            },
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('job', models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], max_length=50, verbose_name='Job')),
                ('originality', models.CharField(max_length=80, verbose_name='Originality')),
                ('education', models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], max_length=50, verbose_name='Education')),
                ('alive', models.BooleanField(verbose_name='Alive')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Death Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Mother',
                'verbose_name_plural': 'Mothers',
            },
        ),
        migrations.CreateModel(
            name='Groom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('education', models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], max_length=50, verbose_name='Education')),
                ('job', models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], max_length=50, verbose_name='Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Groom',
                'verbose_name_plural': 'Grooms',
            },
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('job', models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], max_length=50, verbose_name='Job')),
                ('originality', models.CharField(max_length=80, verbose_name='Originality')),
                ('education', models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], max_length=50, verbose_name='Education')),
                ('alive', models.BooleanField(verbose_name='Alive')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Death Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Father',
                'verbose_name_plural': 'Fathers',
            },
        ),
        migrations.CreateModel(
            name='FamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_family_education', models.CharField(choices=[('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Ph.D.', 'Ph.D.'), ('Hoze', 'Hoze')], error_messages={'invalid_choice': 'Invalid choice for average family education.', 'required': 'Average family education is required.'}, max_length=50, verbose_name='Average Family Education')),
                ('average_family_finance', models.CharField(choices=[('Perfect', 'Perfect'), ('Good', 'Good'), ('Average', 'Average'), ('Weak', 'Weak')], error_messages={'invalid_choice': 'Invalid choice for average family finance.', 'required': 'Average family finance is required.'}, max_length=50, verbose_name='Average Family Finance')),
                ('family_divorce_history', models.BooleanField(error_messages={'required': 'Family divorce history is required.'}, verbose_name='Family Divorce History')),
                ('family_divorce_reason', models.CharField(blank=True, error_messages={'max_length': 'Family divorce reason cannot exceed 150 characters.'}, max_length=150, null=True, verbose_name='Family Divorce Reason')),
                ('contact_with_family', models.CharField(error_messages={'max_length': 'Contact with family cannot exceed 50 characters.', 'required': 'Contact with family is required.'}, max_length=50, verbose_name='Contact with Family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Family Information',
                'verbose_name_plural': 'Family Informations',
            },
        ),
        migrations.CreateModel(
            name='ExHusbandChildStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('girl_birth_date', models.TimeField(blank=True, null=True, verbose_name='Girl Birth Date')),
                ('boy_birth_date', models.TimeField(blank=True, null=True, verbose_name='Boy Birth Date')),
                ('custody', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother')], max_length=50, verbose_name='Custody')),
                ('living_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ex-Husband Child Status',
                'verbose_name_plural': 'Ex-Husband Child Statuses',
            },
        ),
        migrations.CreateModel(
            name='EngagementOrWeddingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Engagement', 'Engagement'), ('Contract', 'Contract'), ('Wedding', 'Wedding'), ('None', 'None')], error_messages={'invalid_choice': 'Invalid choice for engagement or wedding status.', 'required': 'Engagement or wedding status is required.'}, max_length=50, verbose_name='Status')),
                ('contract_length', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contract Length')),
                ('living_length', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living Length')),
                ('death_date', models.TimeField(blank=True, null=True, verbose_name='Death Date')),
                ('divorce_date', models.TimeField(blank=True, null=True, verbose_name='Divorce Date')),
                ('reason_for_divorce_or_death', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason for Divorce or Death')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Engagement or Wedding Status',
                'verbose_name_plural': 'Engagement or Wedding Statuses',
            },
        ),
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('education', models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], max_length=50, verbose_name='Education')),
                ('job', models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], max_length=50, verbose_name='Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Brother',
                'verbose_name_plural': 'Brothers',
            },
        ),
        migrations.CreateModel(
            name='BrideOrWife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('education', models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], max_length=50, verbose_name='Education')),
                ('job', models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], max_length=50, verbose_name='Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bride or Wife',
                'verbose_name_plural': 'Brides or Wives',
            },
        ),
    ]
