# Generated by Django 4.2.13 on 2025-01-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_brideorwife_user_alter_brother_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscode',
            options={'verbose_name': 'Access Code Information', 'verbose_name_plural': 'Access Codes Information'},
        ),
        migrations.AlterModelOptions(
            name='birthcertificateinformation',
            options={'verbose_name': 'Birth Certificate Information', 'verbose_name_plural': 'Birth Certificates Information'},
        ),
        migrations.AlterModelOptions(
            name='engagementorweddingstatus',
            options={'verbose_name': 'Engagement or Wedding Status', 'verbose_name_plural': 'Engagements or Weddings Statuse'},
        ),
        migrations.AlterModelOptions(
            name='exhusbandchildstatus',
            options={'verbose_name': 'Ex-Husband Child Status', 'verbose_name_plural': 'Ex-Husbands Child Status'},
        ),
        migrations.AlterModelOptions(
            name='familyinformation',
            options={'verbose_name': 'Family Information', 'verbose_name_plural': 'Families Information'},
        ),
        migrations.AlterModelOptions(
            name='identityinformation',
            options={'verbose_name': 'Identities Information', 'verbose_name_plural': 'Identities Information'},
        ),
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personals Information'},
        ),
        migrations.AlterModelOptions(
            name='physicalinformation',
            options={'verbose_name': 'Physical Information', 'verbose_name_plural': 'Physical Informations'},
        ),
    ]
