# Generated by Django 4.2.13 on 2025-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_accesscode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinformation',
            name='average_family_education',
            field=models.CharField(choices=[('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Ph.D.', 'Ph.D.'), ('Hoze', 'Hoze')], error_messages={'invalid_choice': 'Invalid choice for average family education.', 'required': 'Average family education is required.'}, help_text='Select the average family education level.', max_length=50, verbose_name='Average Family Education'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='average_family_finance',
            field=models.CharField(choices=[('Perfect', 'Perfect'), ('Good', 'Good'), ('Average', 'Average'), ('Weak', 'Weak')], error_messages={'invalid_choice': 'Invalid choice for average family finance.', 'required': 'Average family finance is required.'}, help_text='Select the average family financial status.', max_length=50, verbose_name='Average Family Finance'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='contact_with_family',
            field=models.CharField(error_messages={'max_length': 'Contact with family cannot exceed 50 characters.', 'required': 'Contact with family is required.'}, help_text='Describe the contact with the family.', max_length=50, verbose_name='Contact with Family'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='family_divorce_history',
            field=models.BooleanField(error_messages={'required': 'Family divorce history is required.'}, help_text='Indicate if there is a history of divorce in the family.', verbose_name='Family Divorce History'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='family_divorce_reason',
            field=models.CharField(blank=True, error_messages={'max_length': 'Family divorce reason cannot exceed 150 characters.'}, help_text='Specify the reason for the family divorce if applicable.', max_length=150, null=True, verbose_name='Family Divorce Reason'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='father_name',
            field=models.CharField(error_messages={'blank': "Father's name cannot be blank.", 'max_length': "Father's name cannot exceed 80 characters.", 'null': "Father's name cannot be null."}, help_text="Enter the father's name of the user.", max_length=80, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'Last name cannot be blank.', 'max_length': 'Last name cannot exceed 50 characters.', 'null': 'Last name cannot be null.'}, help_text='Enter the last name of the user.', max_length=50, verbose_name='Last Name'),
        ),
    ]
