# Generated by Django 4.2.13 on 2025-01-03 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_familyinformation_average_family_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_residence_status', models.CharField(choices=[('fathers_house', "Father's House"), ('mothers_house', "Mother's House"), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for current residence status.', 'required': 'Current residence status is required.'}, help_text='Select the current residence status of the user.', max_length=50)),
                ('ownership_status', models.CharField(choices=[('owner', 'Owner'), ('rent', 'Rent')], error_messages={'invalid_choice': 'Invalid choice for ownership status.', 'required': 'Ownership status is required.'}, help_text='Select the ownership status of the residence.', max_length=50)),
                ('rent_amount', models.IntegerField(error_messages={'invalid': 'Invalid value for rent amount.', 'required': 'Rent amount is required.'}, help_text='Enter the rent amount in the local currency.')),
                ('mortgage_amount', models.IntegerField(error_messages={'invalid': 'Invalid value for mortgage amount.', 'required': 'Mortgage amount is required.'}, help_text='Enter the mortgage amount in the local currency.')),
                ('capital', multiselectfield.db.fields.MultiSelectField(choices=[('house', 'House'), ('shop', 'Shop'), ('land', 'Land'), ('garden', 'Garden'), ('factory', 'Factory'), ('company', 'Company'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for capital.', 'required': 'Capital is required.'}, help_text='Select the types of capital owned by the user.', max_length=59)),
                ('after_marriage_residence_status', models.CharField(choices=[('owner', 'Owner'), ('mortgage', 'Mortgage'), ('fathers_house', "Father's House"), ('mothers_house', "Mother's House"), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for after marriage residence status.', 'required': 'After marriage residence status is required.'}, help_text='Select the residence status after marriage.', max_length=50)),
                ('ex_spouse_financial_status', models.CharField(choices=[('does', 'Does'), ('doesnt', "Doesn't"), ('wants', 'Wants'), ('doesnt_want', "Doesn't Want"), ('man_should_help', 'Man Should Help'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial status.', 'required': 'Ex-spouse financial status is required.'}, help_text='Select the financial status with the ex-spouse.', max_length=50)),
                ('ex_spouse_financial_amount', models.CharField(error_messages={'max_length': 'Ex-spouse financial amount cannot exceed 50 characters.', 'required': 'Ex-spouse financial amount is required.'}, help_text='Enter the financial amount related to the ex-spouse.', max_length=50)),
                ('ex_spouse_financial_pay_status', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('two_years', 'Two Years')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial pay status.', 'required': 'Ex-spouse financial pay status is required.'}, help_text='Select the payment status for the ex-spouse financial amount.', max_length=50)),
                ('dowry_type', multiselectfield.db.fields.MultiSelectField(choices=[('cash', 'Cash'), ('rights', 'Rights'), ('settled', 'Settled'), ('creditor', 'Creditor'), ('debtor', 'Debtor')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the type of dowry.', max_length=35)),
                ('dowry_amount', models.CharField(error_messages={'max_length': 'Dowry amount cannot exceed 50 characters.', 'required': 'Dowry amount is required.'}, help_text='Enter the dowry amount in the local currency or gold.', max_length=50)),
                ('tocher', models.CharField(choices=[('mecca', 'Mecca'), ('gifts_from_iraq', 'Gifts from Iraq'), ('gifts_from_syria', 'Gifts from Syria'), ('gold_coin', 'Gold Coin'), ('money', 'Money'), ('land', 'Land'), ('car', 'Car'), ('garden', 'Garden'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for tocher.', 'required': 'Tocher is required.'}, help_text='Select the type of dowry gifts.', max_length=50)),
                ('agreement_id', models.UUIDField(help_text='Unique identifier for the financial agreement.', unique=True)),
                ('user', models.OneToOneField(help_text='Select the user associated with this financial information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Information',
                'verbose_name_plural': 'Financial Informations',
            },
        ),
    ]
