# Generated by Django 4.2.13 on 2025-01-03 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_financialinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brideorwife',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], help_text='Select the education level of the family member.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='brideorwife',
            name='job',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], help_text='Select the job of the family member.', max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='brideorwife',
            name='status',
            field=models.BooleanField(help_text='Select the engagement or wedding status.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='brideorwife',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], help_text='Select the education level of the family member.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='job',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], help_text='Select the job of the family member.', max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='status',
            field=models.BooleanField(help_text='Select the engagement or wedding status.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='contract_length',
            field=models.CharField(blank=True, help_text='Enter the length of the contract.', max_length=50, null=True, verbose_name='Contract Length'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='death_date',
            field=models.TimeField(blank=True, help_text='Enter the death date if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='divorce_date',
            field=models.TimeField(blank=True, help_text='Enter the divorce date if applicable.', null=True, verbose_name='Divorce Date'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='living_length',
            field=models.CharField(blank=True, help_text='Enter the length of living together.', max_length=50, null=True, verbose_name='Living Length'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='reason_for_divorce_or_death',
            field=models.CharField(blank=True, help_text='Specify the reason for divorce or death if applicable.', max_length=100, null=True, verbose_name='Reason for Divorce or Death'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='status',
            field=models.CharField(choices=[('Engagement', 'Engagement'), ('Contract', 'Contract'), ('Wedding', 'Wedding'), ('None', 'None')], error_messages={'invalid_choice': 'Invalid choice for engagement or wedding status.', 'required': 'Engagement or wedding status is required.'}, help_text='Select the engagement or wedding status.', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='boy_birth_date',
            field=models.TimeField(blank=True, help_text='Enter the birth date of the boy if applicable.', null=True, verbose_name='Boy Birth Date'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='custody',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother')], help_text='Select the custody status of the children.', max_length=50, verbose_name='Custody'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='girl_birth_date',
            field=models.TimeField(blank=True, help_text='Enter the birth date of the girl if applicable.', null=True, verbose_name='Girl Birth Date'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='living_location',
            field=models.CharField(blank=True, help_text='Enter the living location if applicable.', max_length=50, null=True, verbose_name='Living Location'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='status',
            field=models.BooleanField(help_text='Check the box if you have child from ex husband', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='father',
            name='alive',
            field=models.BooleanField(help_text='Indicate if the parent is alive.', verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='father',
            name='birth_date',
            field=models.DateField(help_text='Enter the birth date of the parent.', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='father',
            name='death_date',
            field=models.DateField(blank=True, help_text='Enter the death date of the parent if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='father',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], help_text='Select the education level of the family member.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='father',
            name='job',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], help_text='Select the job of the family member.', max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='father',
            name='language',
            field=models.CharField(help_text='Enter the language spoken by the parent.', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='father',
            name='originality',
            field=models.CharField(help_text='Enter the originality of the parent.', max_length=80, verbose_name='Originality'),
        ),
        migrations.AlterField(
            model_name='father',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], help_text='Select the education level of the family member.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='job',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], help_text='Select the job of the family member.', max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='status',
            field=models.BooleanField(help_text='Select the engagement or wedding status.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='alive',
            field=models.BooleanField(help_text='Indicate if the parent is alive.', verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='birth_date',
            field=models.DateField(help_text='Enter the birth date of the parent.', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='death_date',
            field=models.DateField(blank=True, help_text='Enter the death date of the parent if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], help_text='Select the education level of the family member.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='job',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], help_text='Select the job of the family member.', max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='language',
            field=models.CharField(help_text='Enter the language spoken by the parent.', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='originality',
            field=models.CharField(help_text='Enter the originality of the parent.', max_length=80, verbose_name='Originality'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sister',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], help_text='Select the education level of the family member.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='sister',
            name='job',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('military', 'Military'), ('administrative', 'Administrative'), ('teacher', 'Teacher'), ('hoze_molabas', 'Hoze Molabas'), ('hoze_none_molabas', 'Hoze None Molabas'), ('hoze_sisters', 'Hoze Sisters'), ('womanly_job', 'Womanly Job'), ('no_job', 'No Job'), ('housekeeper', 'Housekeeper'), ('doesnt_matter', "Doesn't matter"), ('other', 'Other')], help_text='Select the job of the family member.', max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='sister',
            name='status',
            field=models.BooleanField(help_text='Select the engagement or wedding status.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sister',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
