# Generated by Django 4.2.13 on 2025-01-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_brideorwife_education_alter_brideorwife_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredWifePhysicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, error_messages={'invalid': 'Invalid height value.', 'required': 'Height is required.'}, help_text='Enter the height of the preferred wife in centimeters.', max_digits=5, verbose_name='Height')),
                ('weight', models.DecimalField(decimal_places=2, error_messages={'invalid': 'Invalid weight value.', 'required': 'Weight is required.'}, help_text='Enter the weight of the preferred wife in kilograms.', max_digits=5, verbose_name='Weight')),
                ('skin_color', models.CharField(choices=[('Very Bright', 'Very Bright'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Date', 'Date'), ('Green', 'Green'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Normal', 'Normal'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Green', 'Bright Green')], error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the preferred wife.', max_length=50, verbose_name='Skin Color')),
                ('user', models.OneToOneField(help_text='Select the user associated with this preferred wife information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Preferred Wife Physical Information',
                'verbose_name_plural': 'Preferred Wife Physical Information',
            },
        ),
        migrations.CreateModel(
            name='PreferredWifePersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('Uninterested', 'Uninterested'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ('Bachelor', 'Bachelor'), ('Master’s Bachelor', 'Master’s Bachelor'), ('Hoze LVL1', 'Hoze LVL1'), ('Hoze LVL2', 'Hoze LVL2'), ('Hoze LVL3', 'Hoze LVL3'), ('Hoze LVL4', 'Hoze LVL4'), ('School & Quranic', 'School & Quranic')], error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, help_text='Select the education level of the preferred wife.', max_length=50, verbose_name='Education')),
                ('degree', models.CharField(choices=[('Medical', 'Medical'), ('Engineer', 'Engineer'), ('Human Science', 'Human Science'), ('Hoze Mobtadas', 'Hoze Mobtadas'), ('Hoze Not Mobtadas', 'Hoze Not Mobtadas'), ('Art', 'Art'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the preferred wife.', max_length=50, verbose_name='Degree')),
                ('future_spouse_job', models.CharField(choices=[('Free', 'Free'), ('Military', 'Military'), ('Administrative', 'Administrative'), ('Teacher', 'Teacher'), ('Hoze Mobtadas', 'Hoze Mobtadas'), ('Hoze Not Mobtadas', 'Hoze Not Mobtadas'), ('Nurse Status', 'Nurse Status'), ('Womanly Job', 'Womanly Job'), ('No Job', 'No Job'), ('Doesn’t Matter', 'Doesn’t Matter'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for future spouse job.', 'required': 'Future spouse job is required.'}, help_text='Select the future spouse job of the preferred wife.', max_length=50, verbose_name='Future Spouse Job')),
                ('current_residence_location', models.CharField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mecca City', 'Mecca City'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for current residence location.', 'required': 'Current residence location is required.'}, help_text='Select the current residence location of the preferred wife.', max_length=50, verbose_name='Current Residence Location')),
                ('after_marriage_residence_location', models.CharField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mecca City', 'Mecca City'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for after marriage residence location.', 'required': 'After marriage residence location is required.'}, help_text='Select the after marriage residence location of the preferred wife.', max_length=50, verbose_name='After Marriage Residence Location')),
                ('user', models.OneToOneField(help_text='Select the user associated with this preferred wife information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Preferred Wife Personal Information',
                'verbose_name_plural': 'Preferred Wife Personal Information',
            },
        ),
        migrations.CreateModel(
            name='PreferredWifeIntellectualInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_type', models.CharField(choices=[('Religious', 'Religious'), ('Norm', 'Norm'), ('Cador', 'Cador'), ('Manto', 'Manto'), ('Sport & Modern', 'Sport & Modern')], error_messages={'invalid_choice': 'Invalid choice for appearance type.', 'required': 'Appearance type is required.'}, help_text='Select the appearance type of the preferred wife.', max_length=50, verbose_name='Appearance Type')),
                ('age_difference', multiselectfield.db.fields.MultiSelectField(choices=[('Same', 'Same'), ('Till 3', 'Till 3'), ('3 to 7', '3 to 7'), ('7 to 10', '7 to 10'), ('10 to 15', '10 to 15'), ('Depends on the Looks', 'Depends on the Looks'), ('Doesn’t Matter', 'Doesn’t Matter')], error_messages={'invalid_choice': 'Invalid choice for age difference.', 'required': 'Age difference is required.'}, help_text='Select the age difference preference for the preferred wife.', max_length=71, verbose_name='Age Difference')),
                ('future_spouse_family_religious_status_importance', models.CharField(choices=[('Too Much', 'Too Much'), ('Much', 'Much'), ('Any', 'Any'), ('Low', 'Low'), ('Doesn’t Matter', 'Doesn’t Matter')], error_messages={'invalid_choice': 'Invalid choice for future spouse family religious status importance.', 'required': 'Future spouse family religious status importance is required.'}, help_text="Select the importance of the future spouse's family religious status.", max_length=50, verbose_name='Future Spouse Family Religious Status Importance')),
                ('future_spouse_family_financial_status_importance', models.CharField(choices=[('Too Much', 'Too Much'), ('Much', 'Much'), ('Any', 'Any'), ('Low', 'Low'), ('Doesn’t Matter', 'Doesn’t Matter')], error_messages={'invalid_choice': 'Invalid choice for future spouse family financial status importance.', 'required': 'Future spouse family financial status importance is required.'}, help_text="Select the importance of the future spouse's family financial status.", max_length=50, verbose_name='Future Spouse Family Financial Status Importance')),
                ('marriage_with_someone_with_marriage_experience', multiselectfield.db.fields.MultiSelectField(choices=[('Never', 'Never'), ('Divorced Virgin', 'Divorced Virgin'), ('Divorced No Life', 'Divorced No Life'), ('No Child', 'No Child'), ('Child Present', 'Child Present'), ('Have Children', 'Have Children'), ('Have Boy', 'Have Boy'), ('Have Girl', 'Have Girl')], error_messages={'invalid_choice': 'Invalid choice for marriage with someone with marriage experience.', 'required': 'Marriage with someone with marriage experience is required.'}, help_text='Select the preference for marriage with someone with marriage experience.', max_length=94, verbose_name='Marriage with Someone with Marriage Experience')),
                ('future_spouse_originality', models.CharField(choices=[('Doesn’t Matter', 'Doesn’t Matter'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for future spouse originality.', 'required': 'Future spouse originality is required.'}, help_text='Select the originality of the future spouse.', max_length=50, verbose_name='Future Spouse Originality')),
                ('most_important_moral_feature_of_future_spouse', models.TextField(error_messages={'required': 'Most important moral feature of future spouse is required.'}, help_text='Enter the most important moral feature of the future spouse.', verbose_name='Most Important Moral Feature of Future Spouse')),
                ('marriage_with_disabled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Depends', 'Depends')], error_messages={'invalid_choice': 'Invalid choice for marriage with disabled.', 'required': 'Marriage with disabled is required.'}, help_text='Select the preference for marriage with a disabled person.', max_length=50, verbose_name='Marriage with Disabled')),
                ('red_flags', models.TextField(error_messages={'required': 'Red flags are required.'}, help_text='Enter any red flags for the future spouse.', verbose_name='Red Flags')),
                ('user', models.OneToOneField(help_text='Select the user associated with this preferred wife information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Preferred Wife Intellectual Information',
                'verbose_name_plural': 'Preferred Wife Intellectual Information',
            },
        ),
        migrations.CreateModel(
            name='PreferredWifeExtraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_explanations', models.TextField(error_messages={'required': 'Additional explanations are required.'}, help_text='Enter any additional information that is not included in the form.', verbose_name='Additional Explanations')),
                ('user', models.OneToOneField(help_text='Select the user associated with this preferred wife information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Preferred Wife Extra Information',
                'verbose_name_plural': 'Preferred Wife Extra Information',
            },
        ),
    ]
