# Generated by Django 4.2.13 on 2025-01-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_preferredwifephysicalinformation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscode',
            options={'verbose_name': 'Access Code Management', 'verbose_name_plural': 'Access Codes Management'},
        ),
    ]
