# Generated by Django 4.2.13 on 2025-01-07 14:34

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_accesscode_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementorweddingstatus',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='engagementorweddingstatus',
            name='divorce_date',
        ),
        migrations.RemoveField(
            model_name='exhusbandchildstatus',
            name='boy_birth_date',
        ),
        migrations.RemoveField(
            model_name='exhusbandchildstatus',
            name='girl_birth_date',
        ),
        migrations.RemoveField(
            model_name='father',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='financialinformation',
            name='agreement_id',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='preferredwifepersonalinformation',
            name='degree',
        ),
        migrations.AddField(
            model_name='engagementorweddingstatus',
            name='new_death_date',
            field=models.DateField(blank=True, help_text='Enter the death date if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AddField(
            model_name='exhusbandchildstatus',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Enter the birth date of the parent.', null=True, verbose_name='Child Birth Date'),
        ),
        migrations.AddField(
            model_name='father',
            name='new_death_date',
            field=models.DateField(blank=True, help_text='Enter the death date of the parent if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AddField(
            model_name='financialinformation',
            name='new_death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Death Date'),
        ),
        migrations.AddField(
            model_name='mother',
            name='new_death_date',
            field=models.DateField(blank=True, help_text='Enter the death date of the parent if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AddField(
            model_name='preferredwifepersonalinformation',
            name='field_of_study',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineer', 'Engineer'), ('Human Science', 'Human Science'), ('Hoze Mobtadas', 'Hoze Mobtadas'), ('Hoze Not Mobtadas', 'Hoze Not Mobtadas'), ('Art', 'Art'), ('Other', 'Other')], default='Medical', error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the preferred wife.', max_length=50, verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinformation',
            name='birth_date',
            field=models.DateField(error_messages={'blank': 'Birth date cannot be blank.', 'invalid': 'Birth date is invalid.', 'null': 'Birth date cannot be null.'}, help_text='Enter the birth date of the user.', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinformation',
            name='contract_date',
            field=models.DateField(blank=True, error_messages={'blank': 'Contract date cannot be blank.', 'invalid': 'Contract date is invalid.', 'null': 'Contract date cannot be null.'}, help_text='Enter the contract date.', null=True, verbose_name='Contract Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinformation',
            name='divorce_date',
            field=models.DateField(blank=True, error_messages={'blank': 'Divorce date cannot be blank.', 'invalid': 'Divorce date is invalid.', 'null': 'Divorce date cannot be null.'}, help_text='Enter the divorce date.', null=True, verbose_name='Divorce Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinformation',
            name='husband_death_date',
            field=models.DateField(blank=True, error_messages={'blank': 'Husband death date cannot be blank.', 'invalid': 'Husband death date is invalid.', 'null': 'Husband death date cannot be null.'}, help_text='Enter the husband death date.', null=True, verbose_name='Husband Death Date'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinformation',
            name='marriage_date',
            field=models.DateField(blank=True, error_messages={'blank': 'Marriage date cannot be blank.', 'invalid': 'Marriage date is invalid.', 'null': 'Marriage date cannot be null.'}, help_text='Enter the marriage date.', null=True, verbose_name='Marriage Date'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='after_marriage_residence_status',
            field=models.CharField(choices=[('owner', 'Owner'), ('mortgage', 'Mortgage'), ('fathers_house', "Father's House"), ('mothers_house', "Mother's House"), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for after marriage residence status.', 'required': 'After marriage residence status is required.'}, help_text='Select the residence status after marriage.', max_length=50, verbose_name='After Marriage Residence Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='capital',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('house', 'House'), ('shop', 'Shop'), ('land', 'Land'), ('garden', 'Garden'), ('factory', 'Factory'), ('company', 'Company'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for capital.', 'required': 'Capital is required.'}, help_text='Select the types of capital owned by the user.', max_length=59, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='current_residence_status',
            field=models.CharField(choices=[('fathers_house', "Father's House"), ('mothers_house', "Mother's House"), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for current residence status.', 'required': 'Current residence status is required.'}, help_text='Select the current residence status of the user.', max_length=50, verbose_name='Current Residence Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_amount',
            field=models.CharField(error_messages={'max_length': 'Dowry amount cannot exceed 50 characters.', 'required': 'Dowry amount is required.'}, help_text='Enter the dowry amount in the local currency or gold.', max_length=50, verbose_name='Dowry Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cash', 'Cash'), ('rights', 'Rights'), ('settled', 'Settled'), ('creditor', 'Creditor'), ('debtor', 'Debtor')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the type of dowry.', max_length=35, verbose_name='Dowry Type'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_amount',
            field=models.CharField(error_messages={'max_length': 'Ex-spouse financial amount cannot exceed 50 characters.', 'required': 'Ex-spouse financial amount is required.'}, help_text='Enter the financial amount related to the ex-spouse.', max_length=50, verbose_name='Ex-Spouse Financial Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_pay_status',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('two_years', 'Two Years')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial pay status.', 'required': 'Ex-spouse financial pay status is required.'}, help_text='Select the payment status for the ex-spouse financial amount.', max_length=50, verbose_name='Ex-Spouse Financial Pay Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_status',
            field=models.CharField(choices=[('does', 'Does'), ('doesnt', "Doesn't"), ('wants', 'Wants'), ('doesnt_want', "Doesn't Want"), ('man_should_help', 'Man Should Help'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial status.', 'required': 'Ex-spouse financial status is required.'}, help_text='Select the financial status with the ex-spouse.', max_length=50, verbose_name='Ex-Spouse Financial Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='mortgage_amount',
            field=models.IntegerField(error_messages={'invalid': 'Invalid value for mortgage amount.', 'required': 'Mortgage amount is required.'}, help_text='Enter the mortgage amount in the local currency.', verbose_name='Mortgage Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ownership_status',
            field=models.CharField(choices=[('owner', 'Owner'), ('rent', 'Rent')], error_messages={'invalid_choice': 'Invalid choice for ownership status.', 'required': 'Ownership status is required.'}, help_text='Select the ownership status of the residence.', max_length=50, verbose_name='Ownership Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='rent_amount',
            field=models.IntegerField(error_messages={'invalid': 'Invalid value for rent amount.', 'required': 'Rent amount is required.'}, help_text='Enter the rent amount in the local currency.', verbose_name='Rent Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='tocher',
            field=models.CharField(choices=[('mecca', 'Mecca'), ('gifts_from_iraq', 'Gifts from Iraq'), ('gifts_from_syria', 'Gifts from Syria'), ('gold_coin', 'Gold Coin'), ('money', 'Money'), ('land', 'Land'), ('car', 'Car'), ('garden', 'Garden'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for tocher.', 'required': 'Tocher is required.'}, help_text='Select the type of dowry gifts.', max_length=50, verbose_name='Tocher'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='introduced_subjects',
            field=models.ManyToManyField(blank=True, error_messages={'blank': 'Introduced subjects cannot be blank.', 'invalid': 'Introduced subjects is invalid.', 'null': 'Introduced subjects cannot be null.'}, help_text='Select the user who introduced the subjects.', related_name='confidintional_info_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Introduced Subjects'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='disease_or_surgery',
            field=models.BooleanField(error_messages={'required': 'Disease or surgery field is required.'}, help_text='Has the user had any disease or surgery?', verbose_name='Disease or Surgery History'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='height',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Invalid height value.', 'max_value': 'Height cannot exceed 260 cm.', 'required': 'Height is required.'}, help_text='Enter the height of the user in centimeters.', max_digits=5, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='weight',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Invalid weight value.', 'max_value': 'Weight cannot exceed 300 kg.', 'required': 'Weight is required.'}, help_text='Enter the weight of the user in kilograms.', max_digits=5, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_disabled',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Depends', 'Depends')], error_messages={'invalid_choice': 'Invalid choice for marriage with disabled.', 'required': 'Marriage with disabled is required.'}, help_text='Select the preference for marriage with a disabled person.', max_length=50, verbose_name='Marriage with Disabled Person'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='education',
            field=models.CharField(choices=[('Uninterested', 'Uninterested'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ('Bachelor', 'Bachelor'), ('Master’s Bachelor', 'Master’s Bachelor'), ('Hoze LVL1', 'Hoze LVL1'), ('Hoze LVL2', 'Hoze LVL2'), ('Hoze LVL3', 'Hoze LVL3'), ('Hoze LVL4', 'Hoze LVL4'), ('School & Quranic', 'School & Quranic')], error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, help_text='Select the education level of the preferred wife.', max_length=50, verbose_name='Education Level'),
        ),
    ]
