# Generated by Django 4.2.13 on 2025-01-07 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_engagementorweddingstatus_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementorweddingstatus',
            name='divorce_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localtime, help_text='Enter the divorce date if applicable.', null=True, verbose_name='Divorce Date'),
        ),
    ]
