# Generated by Django 4.2.13 on 2025-01-07 16:25

import django.contrib.auth.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_engagementorweddingstatus_divorce_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'Email cannot be blank.', 'invalid': 'Email is invalid.', 'null': 'Email cannot be null.', 'unique': 'This email is already taken.'}, help_text='Email format accepted.', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'First name cannot be blank.', 'max_length': 'First name cannot exceed 150 characters.', 'null': 'First name cannot be null.'}, help_text='150 characters or fewer.', max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'Last name cannot be blank.', 'max_length': 'Last name cannot exceed 150 characters.', 'null': 'Last name cannot be null.'}, help_text='150 characters or fewer.', max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'blank': 'Phone number cannot be blank.', 'invalid': 'Phone number is invalid.', 'null': 'Phone number cannot be null.', 'unique': 'This phone number is already taken.'}, help_text='+98 or 09** format accepted.', max_length=128, region='IR', unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username cannot be blank.', 'invalid': 'Username is invalid.', 'max_length': 'Username cannot exceed 150 characters.', 'null': 'Username cannot be null.', 'unique': 'This username is already taken.'}, help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
