# Generated by Django 4.2.13 on 2025-01-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagementorweddingstatus',
            old_name='new_death_date',
            new_name='death_date',
        ),
        migrations.RenameField(
            model_name='father',
            old_name='new_death_date',
            new_name='death_date',
        ),
        migrations.RenameField(
            model_name='financialinformation',
            old_name='new_death_date',
            new_name='death_date',
        ),
        migrations.RenameField(
            model_name='mother',
            old_name='new_death_date',
            new_name='death_date',
        ),
    ]
