# Generated by Django 4.2.13 on 2025-01-07 18:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_new_death_date_engagementorweddingstatus_death_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_amount',
            field=models.CharField(blank=True, error_messages={'max_length': 'Ex-spouse financial amount cannot exceed 50 characters.', 'required': 'Ex-spouse financial amount is required.'}, help_text='Enter the financial amount related to the ex-spouse.', max_length=50, null=True, verbose_name='Ex-Spouse Financial Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='mortgage_amount',
            field=models.IntegerField(blank=True, error_messages={'invalid': 'Invalid value for mortgage amount.', 'required': 'Mortgage amount is required.'}, help_text='Enter the mortgage amount in the local currency.', null=True, verbose_name='Mortgage Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='rent_amount',
            field=models.IntegerField(blank=True, error_messages={'invalid': 'Invalid value for rent amount.', 'required': 'Rent amount is required.'}, help_text='Enter the rent amount in the local currency.', null=True, verbose_name='Rent Amount'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='eitta_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'blank': 'Eitta number cannot be blank.', 'invalid': 'Eitta number is invalid.', 'null': 'Eitta number cannot be null.', 'unique': 'This Eitta number is already taken.'}, help_text='Enter a unique Eitta number in the format: +98 or 09**.', max_length=128, region='IR', unique=True, verbose_name='Eitta Number'),
        ),
    ]
