# Generated by Django 4.2.13 on 2025-01-23 18:56

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_financialinformation_ex_spouse_financial_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificateinformation',
            name='national_code',
            field=models.CharField(db_index=True, error_messages={'blank': 'National code cannot be blank.', 'max_length': 'National code cannot exceed 10 characters.', 'null': 'National code cannot be null.', 'unique': 'This national code is already taken.'}, help_text='Enter the national code of the user.', max_length=10, unique=True, verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='status',
            field=models.CharField(choices=[('Engagement', 'Engagement'), ('Contract', 'Contract'), ('Wedding', 'Wedding'), ('None', 'None')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for engagement or wedding status.', 'required': 'Engagement or wedding status is required.'}, help_text='Select the engagement or wedding status.', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='status',
            field=models.BooleanField(db_index=True, help_text='Check the box if you have child from ex husband', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='average_family_education',
            field=models.CharField(choices=[('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Ph.D.', 'Ph.D.'), ('Hoze', 'Hoze')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for average family education.', 'required': 'Average family education is required.'}, help_text='Select the average family education level.', max_length=50, verbose_name='Average Family Education'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='average_family_finance',
            field=models.CharField(choices=[('Perfect', 'Perfect'), ('Good', 'Good'), ('Average', 'Average'), ('Weak', 'Weak')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for average family finance.', 'required': 'Average family finance is required.'}, help_text='Select the average family financial status.', max_length=50, verbose_name='Average Family Finance'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='capital',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('house', 'House'), ('shop', 'Shop'), ('land', 'Land'), ('garden', 'Garden'), ('factory', 'Factory'), ('company', 'Company'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('other', 'Other')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for capital.', 'required': 'Capital is required.'}, help_text='Select the types of capital owned by the user.', max_length=59, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='eitta_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, error_messages={'blank': 'Eitta number cannot be blank.', 'invalid': 'Eitta number is invalid.', 'null': 'Eitta number cannot be null.', 'unique': 'This Eitta number is already taken.'}, help_text='Enter a unique Eitta number in the format: +98 or 09**.', max_length=128, region='IR', unique=True, verbose_name='Eitta Number'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='first_name',
            field=models.CharField(db_index=True, error_messages={'blank': 'First name cannot be blank.', 'max_length': 'First name cannot exceed 80 characters.', 'null': 'First name cannot be null.'}, help_text='Enter the first name of the user.', max_length=80, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='last_name',
            field=models.CharField(db_index=True, error_messages={'blank': 'Last name cannot be blank.', 'max_length': 'Last name cannot exceed 50 characters.', 'null': 'Last name cannot be null.'}, help_text='Enter the last name of the user.', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_date',
            field=models.DateField(db_index=True, error_messages={'invalid': 'Invalid birth date format.', 'required': 'Birth date is required.'}, help_text='Enter the birth date of the user.', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='income',
            field=models.BigIntegerField(db_index=True, error_messages={'invalid': 'Invalid income value.', 'required': 'Income is required.'}, help_text='Enter the income of the user.', verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='usage_cases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Alcoholic Drinks', 'Alcoholic Drinks'), ('Drugs', 'Drugs'), ('Cigarettes', 'Cigarettes'), ('Hookah', 'Hookah')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for usage cases.', 'required': 'Usage cases are required.'}, help_text='Select the usage cases applicable to the user.', max_length=40, verbose_name='Usage Cases'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='glasses',
            field=models.BooleanField(db_index=True, error_messages={'required': 'Glasses field is required.'}, help_text='Does the user wear glasses?', verbose_name='Glasses'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='height',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid height value.', 'max_value': 'Height cannot exceed 260 cm.', 'required': 'Height is required.'}, help_text='Enter the height of the user in centimeters.', max_digits=5, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='skin_color',
            field=models.CharField(choices=[('Very Bright', 'Very Bright'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Date', 'Date'), ('Green', 'Green'), ('Dark', 'Dark')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, max_length=20, verbose_name='Skin Color'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='weight',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid weight value.', 'max_value': 'Weight cannot exceed 300 kg.', 'required': 'Weight is required.'}, help_text='Enter the weight of the user in kilograms.', max_digits=5, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='future_spouse_family_financial_status_importance',
            field=models.CharField(choices=[('Too Much', 'Too Much'), ('Much', 'Much'), ('Any', 'Any'), ('Low', 'Low'), ('Doesn’t Matter', 'Doesn’t Matter')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for future spouse family financial status importance.', 'required': 'Future spouse family financial status importance is required.'}, help_text="Select the importance of the future spouse's family financial status.", max_length=50, verbose_name='Future Spouse Family Financial Status Importance'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='future_spouse_family_religious_status_importance',
            field=models.CharField(choices=[('Too Much', 'Too Much'), ('Much', 'Much'), ('Any', 'Any'), ('Low', 'Low'), ('Doesn’t Matter', 'Doesn’t Matter')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for future spouse family religious status importance.', 'required': 'Future spouse family religious status importance is required.'}, help_text="Select the importance of the future spouse's family religious status.", max_length=50, verbose_name='Future Spouse Family Religious Status Importance'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_disabled',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Depends', 'Depends')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for marriage with disabled.', 'required': 'Marriage with disabled is required.'}, help_text='Select the preference for marriage with a disabled person.', max_length=50, verbose_name='Marriage with Disabled Person'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_someone_with_marriage_experience',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Never', 'Never'), ('Divorced Virgin', 'Divorced Virgin'), ('Divorced No Life', 'Divorced No Life'), ('No Child', 'No Child'), ('Child Present', 'Child Present'), ('Have Children', 'Have Children'), ('Have Boy', 'Have Boy'), ('Have Girl', 'Have Girl')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for marriage with someone with marriage experience.', 'required': 'Marriage with someone with marriage experience is required.'}, help_text='Select the preference for marriage with someone with marriage experience.', max_length=94, verbose_name='Marriage with Someone with Marriage Experience'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='after_marriage_residence_location',
            field=models.CharField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mecca City', 'Mecca City'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Agreement', 'Agreement')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for after marriage residence location.', 'required': 'After marriage residence location is required.'}, help_text='Select the after marriage residence location of the preferred wife.', max_length=50, verbose_name='After Marriage Residence Location'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='current_residence_location',
            field=models.CharField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mecca City', 'Mecca City'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Agreement', 'Agreement')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for current residence location.', 'required': 'Current residence location is required.'}, help_text='Select the current residence location of the preferred wife.', max_length=50, verbose_name='Current Residence Location'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='future_spouse_job',
            field=models.CharField(choices=[('Free', 'Free'), ('Military', 'Military'), ('Administrative', 'Administrative'), ('Teacher', 'Teacher'), ('Hoze Mobtadas', 'Hoze Mobtadas'), ('Hoze Not Mobtadas', 'Hoze Not Mobtadas'), ('Nurse Status', 'Nurse Status'), ('Womanly Job', 'Womanly Job'), ('No Job', 'No Job'), ('Doesn’t Matter', 'Doesn’t Matter'), ('Other', 'Other')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for future spouse job.', 'required': 'Future spouse job is required.'}, help_text='Select the future spouse job of the preferred wife.', max_length=50, verbose_name='Future Spouse Job'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='height',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid height value.', 'required': 'Height is required.'}, help_text='Enter the height of the preferred wife in centimeters.', max_digits=5, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='skin_color',
            field=models.CharField(choices=[('Very Bright', 'Very Bright'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Date', 'Date'), ('Green', 'Green'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Normal', 'Normal'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Green', 'Bright Green')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the preferred wife.', max_length=50, verbose_name='Skin Color'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='weight',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid weight value.', 'required': 'Weight is required.'}, help_text='Enter the weight of the preferred wife in kilograms.', max_digits=5, verbose_name='Weight'),
        ),
    ]
