# Generated by Django 4.2.13 on 2025-01-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_birthcertificateinformation_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='field_of_study',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineer', 'Engineer'), ('Human Science', 'Human Science'), ('Hoze Mobtadas', 'Hoze Mobtadas'), ('Hoze Not Mobtadas', 'Hoze Not Mobtadas'), ('Art', 'Art'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the preferred wife.', max_length=50, verbose_name='Field of Study'),
        ),
    ]
