# Generated by Django 4.2.13 on 2025-01-27 15:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_preferredwifepersonalinformation_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinformation',
            name='father_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, error_messages={'blank': "Father's phone number cannot be blank.", 'invalid': "Father's phone number is invalid.", 'null': "Father's phone number cannot be null.", 'unique': "This father's phone number is already taken."}, help_text='Enter a unique phone number for the father in the format: +98 or 09**.', max_length=128, null=True, region='IR', unique=True, verbose_name="Father's Phone"),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='mother_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, error_messages={'blank': "Mother's phone number cannot be blank.", 'invalid': "Mother's phone number is invalid.", 'null': "Mother's phone number cannot be null.", 'unique': "This mother's phone number is already taken."}, help_text='Enter a unique phone number for the mother in the format: +98 or 09**.', max_length=128, null=True, region='IR', unique=True, verbose_name="Mother's Phone"),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='glasses_size',
            field=models.CharField(blank=True, error_messages={'invalid': 'Invalid glasses size value.'}, help_text='Enter the size of the glasses if applicable.', null=True, verbose_name='Glasses Size'),
        ),
    ]
