# Generated by Django 4.2.13 on 2025-02-02 22:39

import core.utils.validators.shared
import core.utils.validators.user_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_identityinformation_father_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users Management'},
        ),
        migrations.AlterField(
            model_name='brideorwife',
            name='status',
            field=models.BooleanField(help_text='Select the Status Of Life.', verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='status',
            field=models.BooleanField(help_text='Select the Status Of Life.', verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='status',
            field=models.CharField(choices=[('Engagement', 'Engagement'), ('Contract', 'Contract'), ('Wedding', 'Wedding'), ('None', 'None')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for engagement or wedding status.', 'required': 'Engagement or wedding status is required.'}, help_text='If user has engagment or related history', max_length=50, verbose_name='Person Status'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='status',
            field=models.BooleanField(help_text='Select the Status Of Life.', verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='sister',
            name='status',
            field=models.BooleanField(help_text='Select the Status Of Life.', verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.CharField(error_messages={'blank': 'Access code cannot be blank.', 'invalid': 'Access code is invalid.', 'null': 'Access code cannot be null.'}, help_text='Required access code for initial user creation.', max_length=50, validators=[core.utils.validators.shared.validate_active_access_code], verbose_name='User Access Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'Email cannot be blank.', 'invalid': 'Email is invalid.', 'null': 'Email cannot be null.', 'unique': 'This email is already taken.'}, help_text='Email format accepted.', max_length=254, null=True, verbose_name='email address'),
        ),
    ]
