# Generated by Django 4.2.13 on 2025-02-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_user_options_alter_brideorwife_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificateinformation',
            name='birth_certificate_serial',
            field=models.CharField(error_messages={'blank': 'Birth certificate serial cannot be blank.', 'max_length': 'Birth certificate serial cannot exceed 10 characters.', 'null': 'Birth certificate serial cannot be null.'}, help_text='Enter the birth certificate serial number of the user.', max_length=15, verbose_name='Birth Certificate Serial'),
        ),
    ]
