# Generated by Django 4.2.13 on 2025-02-06 16:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_birthcertificateinformation_birth_certificate_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='leisure_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Park', 'Park'), ('Trip', 'Trip'), ('Family', 'Family'), ('Television', 'Television'), ('Mobile', 'Mobile'), ('Reading', 'Reading'), ('Shrine', 'Shrine'), ('Jankaran', 'Jankaran'), ('Cinema', 'Cinema'), ('Working in Home', 'Working in Home'), ('Gym', 'Gym'), ('Poem', 'Poem'), ('Garden', 'Garden')], error_messages={'invalid_choice': 'Invalid choice for leisure type.', 'required': 'Leisure type is required.'}, help_text='Select the types of leisure activities the user enjoys.', max_length=97, verbose_name='Leisure Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_man_code',
            field=models.CharField(blank=True, error_messages={'blank': 'Middle man code cannot be blank.', 'invalid': 'Middle man code is invalid.', 'null': 'Middle man code cannot be null.'}, help_text='Optional Username or Full Name for middle man reference.', null=True, verbose_name='Middle man code'),
        ),
    ]
