# Generated by Django 4.2.13 on 2025-02-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_personalinformation_leisure_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_man_code',
            field=models.CharField(blank=True, error_messages={'blank': 'Middle man code cannot be blank.', 'invalid': 'Middle man code is invalid.', 'null': 'Middle man code cannot be null.'}, help_text='Optional Username or Full Name for middle man reference.', max_length=100, null=True, verbose_name='Middle man code'),
        ),
    ]
