# Generated by Django 4.2.13 on 2025-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_user_middle_man_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinformation',
            name='income',
            field=models.CharField(choices=[('-10', 'Under 10'), ('10-20', 'Between 10 to 20'), ('20-30', 'Between 20 to 30'), ('30-40', 'Between 30 to 40'), ('40-50', 'Between 40 to 50'), ('50-100', 'Between 50 to 100'), ('+100', 'Plus 100')], error_messages={'blank': 'Income cannot be blank.', 'invalid': 'Income is invalid.', 'null': 'Income cannot be null.'}, help_text='Enter the income of the user in Rials.', verbose_name='Income in Rials'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='insurance',
            field=models.CharField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('iran', 'Iran'), ('asia', 'Asia'), ('dana', 'Dana'), ('moalem', 'Moalem'), ('parsian', 'Parsian'), ('pasargad', 'Pasargad'), ('Saman', 'Saman'), ('melat', 'Melat'), ('ma', 'Ma'), ('alborz', 'Alborz'), ('kosar', 'Kosar'), ('karafarin', 'Karafarin'), ('novin', 'Novin'), ('day', 'Day'), ('sarmad', 'Sarmad'), ('Razi', 'Razi'), ('taavon', 'Taavon'), ('hafez', 'Hafez'), ('etkayii', 'Etkayii Iranian'), ('tejaratno', 'Tejarat No'), ('khavermiane', 'Khavermiane'), ('hekmat', 'Hekmat Saba'), ('tosehe', 'Tosehe')], error_messages={'blank': 'Insurance cannot be blank.', 'invalid': 'Insurance is invalid.', 'null': 'Insurance cannot be null.'}, help_text='Select the insurance type of the user.', max_length=50, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='income',
            field=models.CharField(choices=[('-10', 'Under 10'), ('10-20', 'Between 10 to 20'), ('20-30', 'Between 20 to 30'), ('30-40', 'Between 30 to 40'), ('40-50', 'Between 40 to 50'), ('50-100', 'Between 50 to 100'), ('+100', 'Plus 100')], db_index=True, error_messages={'invalid': 'Invalid income value.', 'required': 'Income is required.'}, help_text='Enter the income of the user.', verbose_name='Income'),
        ),
    ]
