# Generated by Django 4.2.13 on 2025-02-07 15:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_identityinformation_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityinformation',
            name='introduced_subjects_explantions',
            field=models.TextField(blank=True, error_messages={'blank': 'Introduced subjects cannot be blank.', 'invalid': 'Introduced subjects is invalid.', 'null': 'Introduced subjects cannot be null.'}, help_text='Needed Explantions About Result of Introduced Subjects.', null=True, verbose_name='Introduced Subjects Explanations'),
        ),
        migrations.AlterField(
            model_name='birthcertificateinformation',
            name='children',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('one_boy', 'One Boy'), ('two_boys', 'Two Boys'), ('three_boys', 'Three Boys'), ('one_girl', 'One Girl'), ('two_girls', 'Two Girls'), ('three_girls', 'Three Girls')], error_messages={'blank': 'Children cannot be blank.', 'invalid': 'Children is invalid.', 'null': 'Children cannot be null.'}, help_text='Select the number of children.', max_length=63, verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='capital',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('house', 'House'), ('shop', 'Shop'), ('land', 'Land'), ('garden', 'Garden'), ('factory', 'Factory'), ('company', 'Company'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('gold', 'Gold'), ('other', 'Other')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for capital.', 'required': 'Capital is required.'}, help_text='Select the types of capital owned by the user.', max_length=64, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='assets',
            field=models.CharField(choices=[('house', 'House'), ('shop', 'Shop'), ('land', 'Land'), ('garden', 'Garden'), ('factory', 'Factory'), ('company', 'Company'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('gold', 'Gold'), ('other', 'Other')], error_messages={'blank': 'Assets cannot be blank.', 'max_length': 'Assets cannot exceed 150 characters.', 'null': 'Assets cannot be null.'}, help_text='Enter the assets of the user.', verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], error_messages={'blank': 'Education cannot be blank.', 'max_length': 'Education cannot exceed 80 characters.', 'null': 'Education cannot be null.'}, help_text='Enter the education level of the user.', verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='income',
            field=models.CharField(choices=[('-10', 'Under 10M'), ('10-20', 'Between 10M to 20M'), ('20-30', 'Between 20M to 30M'), ('30-40', 'Between 30M to 40M'), ('40-50', 'Between 40M to 50M'), ('50-100', 'Between 50M to 100M'), ('+100', 'Plus 100')], error_messages={'blank': 'Income cannot be blank.', 'invalid': 'Income is invalid.', 'null': 'Income cannot be null.'}, help_text='Enter the income of the user in Rials.', verbose_name='Income in Rials'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='degree',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineer', 'Engineer'), ('Human Science', 'Human Science'), ('Hoze Molabas', 'Hoze Molabas'), ('Hoze Not Molabas', 'Hoze Not Molabas'), ('Art', 'Art'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the user.', verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='deposit',
            field=models.CharField(choices=[('-50', 'Under 50M'), ('50-100', 'Between 50M to 100M'), ('100-200', 'Between 100M to 200M'), ('200-500', 'Between 200M to 500M'), ('+500', 'Plus 500M')], error_messages={'invalid': 'Invalid deposit value.', 'required': 'Deposit is required.'}, help_text='Enter the deposit amount of the user.', verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='income',
            field=models.CharField(choices=[('-10', 'Under 10M'), ('10-20', 'Between 10M to 20M'), ('20-30', 'Between 20M to 30M'), ('30-40', 'Between 30M to 40M'), ('40-50', 'Between 40M to 50M'), ('50-100', 'Between 50M to 100M'), ('+100', 'Plus 100')], db_index=True, error_messages={'invalid': 'Invalid income value.', 'required': 'Income is required.'}, help_text='Enter the income of the user.', verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('iran', 'Iran'), ('asia', 'Asia'), ('dana', 'Dana'), ('moalem', 'Moalem'), ('parsian', 'Parsian'), ('pasargad', 'Pasargad'), ('Saman', 'Saman'), ('melat', 'Melat'), ('ma', 'Ma'), ('alborz', 'Alborz'), ('kosar', 'Kosar'), ('karafarin', 'Karafarin'), ('novin', 'Novin'), ('day', 'Day'), ('sarmad', 'Sarmad'), ('Razi', 'Razi'), ('taavon', 'Taavon'), ('hafez', 'Hafez'), ('etkayii', 'Etkayii Iranian'), ('tejaratno', 'Tejarat No'), ('khavermiane', 'Khavermiane'), ('hekmat', 'Hekmat Saba'), ('tosehe', 'Tosehe')], error_messages={'invalid_choice': 'Invalid choice for insurance type.', 'required': 'Insurance type is required.'}, help_text='Select the type of insurance the user has.', max_length=196, verbose_name='Insurance Type'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='military_status',
            field=models.CharField(choices=[('Exemption', 'Exemption'), ('Mother Sponsorship', 'Mother Sponsorship'), ('Father Sponsorship', 'Father Sponsorship'), ('Educational Exemption', 'Educational Exemption'), ('Medical Exemption', 'Medical Exemption'), ('End of Service', 'End of Service')], error_messages={'invalid_choice': 'Invalid choice for military status.', 'required': 'Military status is required.'}, help_text='Select the military status of the user.', verbose_name='Military Status'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='usage_cases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Alcoholic Drinks', 'Alcoholic Drinks'), ('Drugs', 'Drugs'), ('Cigarettes', 'Cigarettes'), ('Hookah', 'Hookah'), ('none', 'None')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for usage cases.', 'required': 'Usage cases are required.'}, help_text='Select the usage cases applicable to the user.', max_length=45, verbose_name='Usage Cases'),
        ),
    ]
