# Generated by Django 4.2.13 on 2025-02-07 15:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_identityinformation_introduced_subjects_explantions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinformation',
            name='other_captial',
            field=models.CharField(blank=True, db_index=True, error_messages={'max_length': 'Other Captial cannot exceed 150 characters.'}, help_text='Enter the Other capitals owned by the user.', max_length=150, null=True, verbose_name='Other Capital'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='assets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('house', 'House'), ('shop', 'Shop'), ('land', 'Land'), ('garden', 'Garden'), ('factory', 'Factory'), ('company', 'Company'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('gold', 'Gold'), ('other', 'Other')], error_messages={'blank': 'Assets cannot be blank.', 'max_length': 'Assets cannot exceed 150 characters.', 'null': 'Assets cannot be null.'}, help_text='Enter the assets of the user.', max_length=64, verbose_name='Capital'),
        ),
    ]
