# Generated by Django 4.2.13 on 2025-02-07 15:44

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_financialinformation_other_captial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityinformation',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Upload a PDF, JPG, or PNG file as proof of payment.', null=True, upload_to='payment_proofs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message={'invalid': 'Invalid file type. Only PDF, JPG, JPEG, and PNG files are allowed.'})], verbose_name='Proof Of Payment'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='income',
            field=models.CharField(choices=[('-10', 'Under 10M'), ('10-20', 'Between 10M to 20M'), ('20-30', 'Between 20M to 30M'), ('30-40', 'Between 30M to 40M'), ('40-50', 'Between 40M to 50M'), ('50-100', 'Between 50M to 100M'), ('+100', 'Plus 100')], error_messages={'blank': 'Income cannot be blank.', 'invalid': 'Income is invalid.', 'null': 'Income cannot be null.'}, help_text='Enter the income of the user in Tooman.', verbose_name='Income in Tooman'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='leisure_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Park', 'Park'), ('Trip', 'Trip'), ('Family', 'Family'), ('Television', 'Television'), ('Mobile', 'Mobile'), ('Reading', 'Reading'), ('Shrine', 'Shrine'), ('Jankaran', 'Jankaran'), ('Cinema', 'Cinema'), ('Family', 'Visiting Family'), ('Gym', 'Gym'), ('Poem', 'Poem'), ('Garden', 'Garden')], error_messages={'invalid_choice': 'Invalid choice for leisure type.', 'required': 'Leisure type is required.'}, help_text='Select the types of leisure activities the user enjoys.', max_length=88, verbose_name='Leisure Type'),
        ),
    ]
