# Generated by Django 4.2.13 on 2025-02-07 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_physicalinformation_skin_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalinformation',
            name='blood_type',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], error_messages={'invalid_choice': 'Invalid choice for blood type.', 'required': 'Blood type is required.'}, help_text='Select the blood type of the user.', max_length=3, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='body_and_face',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Suitable', 'Suitable'), ('Nice Face', 'Nice Face'), ('Nice Body', 'Nice Body'), ('Looks Older', 'Looks Older'), ('Looks Younger', 'Looks Younger'), ('Satisfied', 'Satisfied'), ('None', 'None')], error_messages={'invalid_choice': 'Invalid choice for body and face.', 'required': 'Body and face is required.'}, help_text='Select the body and face characteristics of the user.', max_length=20, verbose_name='Body and Face'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='character_and_temperament',
            field=models.CharField(choices=[('Safravi', 'Safravi (Hot & Dry)'), ('Damvi', 'Damvi (Hot & Wet)'), ('Sodavi', 'Sodavi (Cold & Dry)'), ('Balghami', 'Balghami (Cold & Wet)')], error_messages={'invalid_choice': 'Invalid choice for character and temperament.', 'required': 'Character and temperament is required.'}, help_text='Select the character and temperament of the user.', max_length=20, verbose_name='Character and Temperament'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='eyes_color',
            field=models.CharField(choices=[('Green', 'Green'), ('Light Blue', 'Light Blue'), ('Hazel', 'Hazel'), ('Darken Blue', 'Darken Blue'), ('Grey', 'Grey'), ('Honey', 'Honey'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Black', 'Black')], error_messages={'invalid_choice': 'Invalid choice for eyes color.', 'required': 'Eyes color is required.'}, help_text='Select the eyes color of the user.', max_length=20, verbose_name='Eyes Color'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='skin_color',
            field=models.CharField(choices=[('Very Bright', 'Very Bright'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Date', 'Date'), ('Green', 'Green'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Normal', 'Normal'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Green', 'Bright Green')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the user.', max_length=20, verbose_name='Skin Color'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='user',
            field=models.OneToOneField(error_messages={'required': 'User is required.'}, help_text='Select the user associated with this physical information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
