# Generated by Django 4.2.13 on 2025-02-08 15:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_physicalinformation_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brideorwife',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='contact_with_family',
            field=models.CharField(error_messages={'max_length': 'Contact with family cannot exceed 50 characters.', 'required': 'Contact with family is required.'}, help_text='Describe the contact with the family.', max_length=150, verbose_name='Contact with Family'),
        ),
        migrations.AlterField(
            model_name='father',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='job',
            field=models.CharField(error_messages={'blank': 'Job cannot be blank.', 'invalid': 'Job is invalid.', 'null': 'Job cannot be null.'}, help_text='Select the job of the user.', max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='skin_color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Very Bright', 'Very Bright'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Green', 'Green'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Normal', 'Normal'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Green', 'Bright Green')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the preferred wife.', max_length=50, verbose_name='Skin Color'),
        ),
        migrations.AlterField(
            model_name='sister',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, verbose_name='Job'),
        ),
    ]
