# Generated by Django 4.2.13 on 2025-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_alter_brideorwife_job_alter_brother_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinformation',
            name='dowry_type',
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_status',
            field=models.CharField(choices=[('cash', 'Cash'), ('rights', 'Rights'), ('settled', 'Settled'), ('creditor', 'Creditor'), ('debtor', 'Debtor')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the type of dowry.', verbose_name='Dowry Type'),
        ),
    ]
