# Generated by Django 4.2.13 on 2025-02-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_remove_financialinformation_dowry_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinformation',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='financialinformation',
            name='ex_spouse_financial_pay_status',
        ),
        migrations.RemoveField(
            model_name='financialinformation',
            name='tocher',
        ),
        migrations.AddField(
            model_name='financialinformation',
            name='dowry_type',
            field=models.CharField(blank=True, choices=[('mecca', 'Mecca'), ('gifts_from_iraq', 'Gifts from Iraq'), ('gifts_from_syria', 'Gifts from Syria'), ('gold_coin', 'Gold Coin'), ('money', 'Money'), ('land', 'Land'), ('car', 'Car'), ('garden', 'Garden'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the type of dowry.', null=True, verbose_name='Dowry Type'),
        ),
        migrations.AddField(
            model_name='financialinformation',
            name='jahiziyeh',
            field=models.CharField(blank=True, choices=[('does', 'Does'), ('doesnt', "Doesn't"), ('wants', 'Wants'), ('doesnt_want', "Doesn't Want"), ('man_should_help', 'Man Should Help'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the Status of Jahiziyeh.', null=True, verbose_name='Jahiziyeh'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_status',
            field=models.CharField(choices=[('cash', 'Cash'), ('rights', 'Rights'), ('settled', 'Settled'), ('creditor', 'Creditor'), ('debtor', 'Debtor')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial status.', 'required': 'Ex-spouse financial status is required.'}, help_text='Select the financial status with the ex-spouse.', verbose_name='Ex-Spouse Financial Status'),
        ),
    ]
