# Generated by Django 4.2.13 on 2025-02-08 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_financialinformation_dowry_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferredwifeintellectualinformation',
            name='future_spouse_originality',
        ),
        migrations.AddField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_veteran',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Depends', 'Depends')], db_index=True, default='Defualt', error_messages={'invalid_choice': 'Invalid choice for marriage with disabled.', 'required': 'Marriage with disabled is required.'}, help_text='Select the preference for marriage with a disabled person.', verbose_name='Marriage with Veteran Person'),
        ),
        migrations.CreateModel(
            name='FutureSposeOriginality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_spouse_originality', models.CharField(error_messages={'invalid_choice': 'Invalid choice for future spouse originality.', 'required': 'Future spouse originality is required.'}, help_text='Select the originality of the future spouse.', max_length=50, verbose_name='Future Spouse Originality')),
                ('user', models.OneToOneField(help_text='Select the user associated with this preferred wife information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'FutureSposeOriginality',
                'verbose_name_plural': 'FutureSposeOriginalities',
            },
        ),
    ]
