# Generated by Django 4.2.13 on 2025-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_remove_preferredwifeintellectualinformation_future_spouse_originality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_veteran',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Depends', 'Depends')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for marriage with disabled.', 'required': 'Marriage with disabled is required.'}, help_text='Select the preference for marriage with a disabled person.', verbose_name='Marriage with Veteran Person'),
        ),
    ]
