# Generated by Django 4.2.13 on 2025-02-08 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_preferredwifeintellectualinformation_marriage_with_veteran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresposeoriginality',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this preferred wife information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
