# Generated by Django 4.2.13 on 2025-02-08 18:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_futuresposeoriginality_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='appearance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Religious', 'Religious'), ('Norm', 'Norm'), ('Cador', 'Cador'), ('Manto', 'Manto'), ('Sport & Modern', 'Sport & Modern')], error_messages={'invalid_choice': 'Invalid choice for appearance type.', 'required': 'Appearance type is required.'}, help_text='Select the appearance type of the preferred wife.', max_length=50, verbose_name='Appearance Type'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='after_marriage_residence_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mecca City', 'Mecca City'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Agreement', 'Agreement')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for after marriage residence location.', 'required': 'After marriage residence location is required.'}, help_text='Select the after marriage residence location of the preferred wife.', max_length=50, verbose_name='After Marriage Residence Location'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='current_residence_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mecca City', 'Mecca City'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Agreement', 'Agreement')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for current residence location.', 'required': 'Current residence location is required.'}, help_text='Select the current residence location of the preferred wife.', max_length=50, verbose_name='Current Residence Location'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='education',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Uninterested', 'Uninterested'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ('Bachelor', 'Bachelor'), ('Master’s Bachelor', 'Master’s Bachelor'), ('Hoze LVL1', 'Hoze LVL1'), ('Hoze LVL2', 'Hoze LVL2'), ('Hoze LVL3', 'Hoze LVL3'), ('Hoze LVL4', 'Hoze LVL4'), ('School & Quranic', 'School & Quranic')], error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, help_text='Select the education level of the preferred wife.', max_length=50, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='field_of_study',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Medical', 'Medical'), ('Engineer', 'Engineer'), ('Human Science', 'Human Science'), ('Hoze Mobtadas', 'Hoze Mobtadas'), ('Hoze Not Mobtadas', 'Hoze Not Mobtadas'), ('Art', 'Art'), ('Other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the preferred wife.', max_length=50, verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='future_spouse_job',
            field=models.CharField(db_index=True, error_messages={'invalid_choice': 'Invalid choice for future spouse job.', 'required': 'Future spouse job is required.'}, help_text='Select the future spouse job of the preferred wife.', max_length=50, verbose_name='Future Spouse Job'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='skin_color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Very Bright', 'Very Bright'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Green', 'Green'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Normal', 'Normal'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Green', 'Bright Green')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the preferred wife.', max_length=139, verbose_name='Skin Color'),
        ),
    ]
