# Generated by Django 4.2.13 on 2025-02-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_preferredwifeintellectualinformation_appearance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='tatoo',
            field=models.BooleanField(db_index=True, default=False, error_messages='Invalid value for the tattoo field.', help_text='Indicate whether the user has any tattoos.', verbose_name='Tatto'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='tatto_description',
            field=models.TextField(blank=True, error_messages='Invalid description provided for tattoos.', help_text='Provide details about the tattoos, if any.', null=True, verbose_name='Tatto Description'),
        ),
    ]
