# Generated by Django 4.2.13 on 2025-02-08 18:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_personalinformation_tatoo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='usage_case_description',
            field=models.TextField(blank=True, error_messages='Invalid usage case description.', help_text='Provide additional details about usage cases. Like how many cigars or hookah a day.', null=True, verbose_name='Usage Case Description'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='tatto_description',
            field=models.TextField(blank=True, error_messages='Invalid description provided for tattoos.', help_text='Provide details about the tattoos, Like Where on the Body.', null=True, verbose_name='Tatto Description'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='after_marriage_residence_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mecca City', 'Mecca City'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Foreign Country', 'Foreign Country'), ('Agreement', 'Agreement')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for after marriage residence location.', 'required': 'After marriage residence location is required.'}, help_text='Select the after marriage residence location of the preferred wife.', max_length=50, verbose_name='After Marriage Residence Location'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='current_residence_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mecca City', 'Mecca City'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Foreign Country', 'Foreign Country'), ('Agreement', 'Agreement')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for current residence location.', 'required': 'Current residence location is required.'}, help_text='Select the current residence location of the preferred wife.', max_length=50, verbose_name='Current Residence Location'),
        ),
    ]
