# Generated by Django 4.2.13 on 2025-02-08 19:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_personalinformation_usage_case_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinformation',
            name='ex_spouse_financial_pay_status',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('two_years', 'Two Years')], default=0, error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial pay status.', 'required': 'Ex-spouse financial pay status is required.'}, help_text='Select the payment status for the ex-spouse financial amount.', max_length=50, verbose_name='Ex-Spouse Financial Pay Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_amount',
            field=models.CharField(error_messages={'max_length': 'Dowry amount cannot exceed 50 characters.', 'required': 'Dowry amount is required.'}, help_text='Enter the dowry amount in the local currency or gold.', max_length=50, verbose_name='Future Spose Dowry Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mecca', 'Mecca'), ('gifts_from_iraq', 'Gifts from Iraq'), ('gifts_from_syria', 'Gifts from Syria'), ('gold_coin', 'Gold Coin'), ('money', 'Money'), ('land', 'Land'), ('car', 'Car'), ('garden', 'Garden'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the type of dowry Of Future Wife.', max_length=80, null=True, verbose_name='Future Spouse Dowry Type'),
        ),
    ]
