# Generated by Django 4.2.13 on 2025-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_financialinformation_ex_spouse_financial_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_pay_status',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('two_years', 'Two Years')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial pay status.', 'required': 'Ex-spouse financial pay status is required.'}, help_text='Select the payment status for the ex-spouse financial amount.', max_length=50, verbose_name='Ex-Spouse Financial Pay Status'),
        ),
    ]
