# Generated by Django 4.2.13 on 2025-02-11 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_alter_financialinformation_ex_spouse_financial_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinformation',
            name='jahiziyeh',
            field=models.CharField(blank=True, choices=[('does', 'Does'), ('doesnt', "Doesn't"), ('wants', 'Wants'), ('doesnt_want', "Doesn't Want"), ('man_should_help', 'Man Should Help'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the Status of Jahiziyeh.', null=True, verbose_name='Future Spose Jahiziyeh'),
        ),
        migrations.CreateModel(
            name='IntroducedSubjectsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'max_length': 'The username cannot exceed 50 characters.', 'required': 'The username is required.'}, help_text='Enter the username of the introduced subject. This should be unique and descriptive.', max_length=50, verbose_name='Username')),
                ('birth_date', models.DateField(error_messages={'blank': 'Birth date cannot be blank.', 'invalid': 'Birth date is invalid.', 'null': 'Birth date cannot be null.'}, help_text='Enter the birth date of the user.', verbose_name='Birth Date')),
                ('marriage_status', models.CharField(choices=[('husband', 'Husband'), ('blank_birth_certificate', 'Blank Birth Certificate')], error_messages={'blank': 'Marriage status cannot be blank.', 'invalid': 'Marriage status is invalid.', 'null': 'Marriage status cannot be null.'}, help_text='Select the marriage status of the user.', verbose_name='Marriage Status')),
                ('postive', models.BooleanField(error_messages={'required': 'You must indicate whether the introduction was positive.'}, help_text='Indicate whether the introduction was positive.', verbose_name='Positive')),
                ('negative', models.BooleanField(error_messages={'required': 'You must indicate whether the introduction was negative.'}, help_text='Indicate whether the introduction was negative.', verbose_name='Negative')),
                ('reason', models.TextField(error_messages={'required': "A reason for the introduction's outcome is required."}, help_text="Provide a detailed reason for the introduction's outcome.", verbose_name='Reason')),
                ('dates_of_meetings', models.TextField(error_messages={'required': 'You must provide the dates of meetings.'}, help_text='List the dates of meetings with the introduced subject.', verbose_name='Dates Of Meetings')),
                ('result_and_regards', models.TextField(error_messages={'required': 'You must summarize the results and any regards from the meetings.'}, help_text='Summarize the results and any regards from the meetings.', verbose_name='Result & Regards')),
                ('cost_of_introduction', models.CharField(error_messages={'max_length': 'The cost of introduction cannot exceed 100 characters.', 'required': 'The cost of introduction is required.'}, help_text='Specify the cost associated with the introduction.', max_length=100, verbose_name='Cost of Introduction')),
                ('cost_of_meeting', models.CharField(error_messages={'max_length': 'The cost of meeting cannot exceed 100 characters.', 'required': 'The cost of meeting is required.'}, help_text='Specify the cost associated with the meetings.', max_length=100, verbose_name='Cost of Meeting')),
                ('user', models.OneToOneField(error_messages={'blank': 'User cannot be blank.', 'invalid': 'User is invalid.', 'null': 'User cannot be null.'}, help_text='Select the user associated with this birth certificate information.', on_delete=django.db.models.deletion.CASCADE, related_name='introduced_subjects_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IntroducedSubjects',
                'verbose_name_plural': 'IntroducedSubjectss',
            },
        ),
    ]
