# Generated by Django 4.2.13 on 2025-02-11 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_alter_financialinformation_jahiziyeh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='user',
            field=models.ForeignKey(error_messages={'blank': 'User cannot be blank.', 'invalid': 'User is invalid.', 'null': 'User cannot be null.'}, help_text='Select the user associated with this birth certificate information.', on_delete=django.db.models.deletion.CASCADE, related_name='introduced_subjects_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
