# Generated by Django 4.2.13 on 2025-02-12 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_introducedsubjectsinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinformation',
            name='user',
            field=models.OneToOneField(error_messages={'blank': 'User cannot be blank.', 'invalid': 'User is invalid.', 'null': 'User cannot be null.'}, help_text='Select the user associated with this identity information.', on_delete=django.db.models.deletion.CASCADE, related_name='confidintional_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
