# Generated by Django 4.2.13 on 2025-02-12 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_alter_identityinformation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntellectualInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_goals', models.TextField(error_messages={'max_length': 'Marriage goals should not exceed 1000 characters.', 'required': 'Marriage goals and purposes cannot be empty.'}, help_text='Describe your goals and purposes for marriage in detail.', verbose_name='Marriage Goals & Purposes')),
                ('opinion_woman_job', models.CharField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('must_have_job', 'Must have a job'), ('depends_work_env', 'Depends on Work Environment'), ('depends_job_type', 'Depends on Job Type'), ('womanly_job', 'Womanly Job'), ('housekeeper', 'Housekeeper')], error_messages={'invalid_choice': "The selected option for a woman's job is not valid.", 'required': "Please provide your opinion about a woman's job."}, help_text="Select your opinion about a woman's job and employment status.", max_length=50, verbose_name="Opinion About Woman's Job")),
                ('opinion_woman_edu', models.CharField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('depends_degree', 'Depends on the Degree')], error_messages={'invalid_choice': "The selected option for a woman's education is not valid.", 'required': "Please provide your opinion about a woman's education."}, help_text="Choose your stance on women's education.", max_length=50, verbose_name="Opinion About Woman's Education")),
                ('pros_of_yourself', models.TextField(error_messages={'max_length': 'Your pros should not exceed 1000 characters.', 'required': 'Please list some of your positive attributes.'}, help_text='List positive traits about yourself.', verbose_name='Pros Of Yourself')),
                ('cons_of_yourself', models.TextField(error_messages={'max_length': 'Your cons should not exceed 1000 characters.', 'required': 'Please list some of your negative attributes.'}, help_text='List aspects of yourself you wish to improve.', verbose_name='Cons Of Yourself')),
                ('type_connection_friends', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('weak', 'Weak'), ('none', 'None')], error_messages={'invalid_choice': "Invalid selection for type of friends' connection.", 'required': 'Please specify the type of connection you have with friends.'}, help_text='Specify the type of connection you prefer with friends.', max_length=50, verbose_name='Type of Connection With Friends')),
                ('friends_connection_reason', models.CharField(error_messages={'max_length': 'Your explanation should not exceed 500 characters.', 'required': 'Please explain why you maintain connections with your friends.'}, help_text='Explain why you connect with friends.', max_length=100, verbose_name='Friends Connection Reason')),
                ('political_orientation', models.BooleanField(error_messages={'invalid': 'Invalid input for political orientation.', 'required': 'Please specify your political orientation.'}, help_text='Indicate whether you have a political orientation.', verbose_name='Political Orientation')),
                ('opinion_velayat_faqih', models.CharField(choices=[('agree', 'Agree'), ('no_opinion', 'No Opinion')], error_messages={'invalid_choice': 'Invalid selection for opinion about Velayat Faqih.', 'required': 'Please share your opinion about Velayat Faqih.'}, help_text='State your opinion on Velayat Faqih.', max_length=50, verbose_name='Opinion About Velayat Faqih')),
                ('opinion_child_quantity', models.CharField(choices=[('dont_want', "Don't Want"), ('depends', 'Depends'), ('one', '1'), ('two', '2'), ('three', '3'), ('more_than_three', 'More than 3'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid selection for child quantity preference.', 'required': 'Please specify your opinion about the number of children.'}, help_text='How many children do you prefer to have?', max_length=50, verbose_name='Opinion About Child Quantity')),
                ('contract_how', models.CharField(choices=[('registry', 'In the Registry'), ('house_family', 'In House & Family'), ('hall', 'In the Hall'), ('doesnt_matter', "Doesn't Matter"), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid selection for contract preferences.', 'required': 'Please specify how you prefer the marriage contract.'}, help_text='Define how you prefer the marriage contract to be arranged.', max_length=50, verbose_name='Contract How & What')),
                ('wedding_how', models.CharField(choices=[('house_family', 'In House & Family'), ('hall', 'In the Hall'), ('pilgrimage', 'Pilgrimage'), ('trip', 'Trip'), ('doesnt_matter', "Doesn't Matter"), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid selection for wedding preferences.', 'required': 'Please specify how you prefer the wedding.'}, help_text='Choose your preferred wedding arrangement.', max_length=50, verbose_name='Wedding How & What')),
                ('worship_prayer', models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('doesnt_matter', "Doesn't Matter"), ('disagree', 'Disagree'), ('sick', 'Sick')], error_messages={'invalid_choice': 'Invalid selection for worship and prayer habits.', 'required': 'Please describe your worship and prayer habits.'}, help_text='Indicate your level of commitment to worship and prayer.', max_length=50, verbose_name='Worship and Prayer')),
                ('fasting', models.CharField(choices=[('too_much', 'Too Much'), ('much', 'Much'), ('average', 'Average'), ('low', 'Low'), ('doesnt_matter', "Doesn't Matter")], error_messages={'invalid_choice': 'Invalid selection for fasting habits.', 'required': 'Please specify your fasting habits.'}, help_text='Describe your practice regarding fasting.', max_length=50, verbose_name='Fasting')),
                ('cover_type_house', models.CharField(choices=[('cozy_attractive', 'Cozy & Attractive'), ('normal', 'Normal')], error_messages={'invalid_choice': 'Invalid selection for house covering type.', 'required': 'Please specify the type of covering you use at home.'}, help_text='Choose your preferred clothing style at home.', max_length=50, verbose_name='Cover Type in House')),
                ('cover_type_society', models.CharField(choices=[('only_chador', 'Only Chador'), ('covered_manto', 'Covered Manto'), ('free_manto', 'Free Manto')], error_messages={'invalid_choice': 'Invalid selection for society and workplace covering type.', 'required': 'Please specify the type of covering you use in society and workplace.'}, help_text='Select your dress preference in society and the workplace.', max_length=50, verbose_name='Cover Type in Society & Workplace')),
                ('user', models.OneToOneField(error_messages={'required': 'A unique ID is required.', 'unique': 'This ID already exists. Please use a different one.'}, help_text='Select the user associated with this intellectual information.', on_delete=django.db.models.deletion.CASCADE, related_name='intellectual_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intellectual Information',
                'verbose_name_plural': 'Intellectual Information',
            },
        ),
    ]
