# Generated by Django 4.2.13 on 2025-02-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_intellectualinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intellectualinformation',
            name='contract_how',
            field=models.CharField(choices=[('registry', 'In the Registry'), ('house_family', 'In House & Family'), ('hall', 'In the Hall'), ('doesnt_matter', "Doesn't Matter"), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid selection for contract preferences.', 'required': 'Please specify how you prefer the marriage contract.'}, help_text='Define how you prefer the marriage contract to be arranged.', verbose_name='Contract How & What'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_house',
            field=models.CharField(choices=[('cozy_attractive', 'Cozy & Attractive'), ('normal', 'Normal')], error_messages={'invalid_choice': 'Invalid selection for house covering type.', 'required': 'Please specify the type of covering you use at home.'}, help_text='Choose your preferred clothing style at home.', verbose_name='Cover Type in House'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_society',
            field=models.CharField(choices=[('only_chador', 'Only Chador'), ('covered_manto', 'Covered Manto'), ('free_manto', 'Free Manto')], error_messages={'invalid_choice': 'Invalid selection for society and workplace covering type.', 'required': 'Please specify the type of covering you use in society and workplace.'}, help_text='Select your dress preference in society and the workplace.', verbose_name='Cover Type in Society & Workplace'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='fasting',
            field=models.CharField(choices=[('too_much', 'Too Much'), ('much', 'Much'), ('average', 'Average'), ('low', 'Low'), ('doesnt_matter', "Doesn't Matter")], error_messages={'invalid_choice': 'Invalid selection for fasting habits.', 'required': 'Please specify your fasting habits.'}, help_text='Describe your practice regarding fasting.', verbose_name='Fasting'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_child_quantity',
            field=models.CharField(choices=[('dont_want', "Don't Want"), ('depends', 'Depends'), ('one', '1'), ('two', '2'), ('three', '3'), ('more_than_three', 'More than 3'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid selection for child quantity preference.', 'required': 'Please specify your opinion about the number of children.'}, help_text='How many children do you prefer to have?', verbose_name='Opinion About Child Quantity'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_velayat_faqih',
            field=models.CharField(choices=[('agree', 'Agree'), ('no_opinion', 'No Opinion')], db_index=True, error_messages={'invalid_choice': 'Invalid selection for opinion about Velayat Faqih.', 'required': 'Please share your opinion about Velayat Faqih.'}, help_text='State your opinion on Velayat Faqih.', verbose_name='Opinion About Velayat Faqih'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_edu',
            field=models.CharField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('depends_degree', 'Depends on the Degree')], error_messages={'invalid_choice': "The selected option for a woman's education is not valid.", 'required': "Please provide your opinion about a woman's education."}, help_text="Choose your stance on women's education.", verbose_name="Opinion About Woman's Education"),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_job',
            field=models.CharField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('must_have_job', 'Must have a job'), ('depends_work_env', 'Depends on Work Environment'), ('depends_job_type', 'Depends on Job Type'), ('womanly_job', 'Womanly Job'), ('housekeeper', 'Housekeeper')], error_messages={'invalid_choice': "The selected option for a woman's job is not valid.", 'required': "Please provide your opinion about a woman's job."}, help_text="Select your opinion about a woman's job and employment status.", verbose_name="Opinion About Woman's Job"),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='type_connection_friends',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('weak', 'Weak'), ('none', 'None')], error_messages={'invalid_choice': "Invalid selection for type of friends' connection.", 'required': 'Please specify the type of connection you have with friends.'}, help_text='Specify the type of connection you prefer with friends.', verbose_name='Type of Connection With Friends'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='wedding_how',
            field=models.CharField(choices=[('house_family', 'In House & Family'), ('hall', 'In the Hall'), ('pilgrimage', 'Pilgrimage'), ('trip', 'Trip'), ('doesnt_matter', "Doesn't Matter"), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid selection for wedding preferences.', 'required': 'Please specify how you prefer the wedding.'}, help_text='Choose your preferred wedding arrangement.', verbose_name='Wedding How & What'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='worship_prayer',
            field=models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('doesnt_matter', "Doesn't Matter"), ('disagree', 'Disagree'), ('sick', 'Sick')], db_index=True, error_messages={'invalid_choice': 'Invalid selection for worship and prayer habits.', 'required': 'Please describe your worship and prayer habits.'}, help_text='Indicate your level of commitment to worship and prayer.', verbose_name='Worship and Prayer'),
        ),
    ]
