# Generated by Django 4.2.13 on 2025-02-12 19:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_intellectualinformation_cover_type_innocent_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_innocent_contact',
            field=models.CharField(choices=[('cozy_attractive', 'Cozy & Attractive'), ('cozy_desired', 'Cozy & Desired'), ('formal_manto', 'Formal Manto'), ('colored_chador', 'Colored Chador'), ('only_chador', 'Only Chador'), ('covered_manto', 'Covered Manto'), ('free_manto', 'Free Manto')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Please select the cover type you prefer in contact with someone innocent.', verbose_name='Cover Type in Contact of Innocent'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='dance_singing_assemblies',
            field=models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('disagree', 'Disagree'), ('agree', 'Agree')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Do you participate in dance and singing assemblies?', verbose_name='Dance & Singing Assemblies'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='decision_making_choosing_spouse',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dependent', 'Dependent'), ('independet', 'Independet'), ('counsole_with_parents', 'Counsole with Parents'), ('counsole_with_bros_and_siss', 'Counsole with Brothers and Sisters'), ('counsole_with_childs', 'Counsole with Childs'), ('counsole_with_professional', 'Counsole with Professional')], error_messages={'required': 'This field is required. Please select an option for decision making.'}, help_text='How do you prefer to decide when choosing a spouse?', max_length=118, verbose_name='Decision Making in Choosing a Spouse'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='music',
            field=models.CharField(choices=[('listen_regularly', 'Listen Regularly'), ('sometimes_listen', 'Sometimes Listen'), ('do_not_listen', 'Do Not Listen'), ('agree', 'Agree'), ('disagree', 'Disagree')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='How often do you listen to music?', verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_innocent_contact',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='What is your opinion on innocent contact?', verbose_name='Opinion About Innocent Contact'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='participating_prayer_quran_meetings',
            field=models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('disagree', 'Disagree'), ('agree', 'Agree')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='How committed are you to attending prayer and Quran religious meetings?', verbose_name='Participating in Prayer and Quran Religious Meetings'),
        ),
    ]
