# Generated by Django 4.2.13 on 2025-02-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_alter_intellectualinformation_cover_type_innocent_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introducedsubjectsinformation',
            options={'verbose_name': 'IntroducedSubjects', 'verbose_name_plural': 'IntroducedSubjects'},
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_innocent_contact',
            field=models.CharField(choices=[('only_chador', 'Only Chador'), ('formal_manto', 'Formal Manto'), ('colored_chador', 'Colored Chador')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Please select the cover type you prefer in contact with someone innocent.', verbose_name='Cover Type in Contact of Innocent'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_society',
            field=models.CharField(choices=[('always_chador', 'Always Chador'), ('always_coverd_manto', 'Always Coverd Manto'), ('always_free_manto', 'Always Free Manto'), ('sometimes_chador', 'Sometimes Chador'), ('sometimes_coverd_manto', 'Sometimes Coverd Manto'), ('sometimes_free_manto', 'Sometimes Free Manto')], error_messages={'invalid_choice': 'Invalid selection for society and workplace covering type.', 'required': 'Please specify the type of covering you use in society and workplace.'}, help_text='Select your dress preference in society and the workplace.', verbose_name='Cover Type in Society & Workplace'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='dance_singing_assemblies',
            field=models.CharField(choices=[('too_much', 'Too Much'), ('much', 'Much'), ('average', 'Average'), ('low', 'Low'), ('never', 'Never')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Do you participate in dance and singing assemblies?', verbose_name='Dance & Singing Assemblies'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='fasting',
            field=models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('disagree', 'Disagree'), ('sick', 'Sick')], error_messages={'invalid_choice': 'Invalid selection for fasting habits.', 'required': 'Please specify your fasting habits.'}, help_text='Describe your practice regarding fasting.', verbose_name='Fasting'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='music',
            field=models.CharField(choices=[('too_much', 'Too Much'), ('much', 'Much'), ('average', 'Average'), ('low', 'Low'), ('never', 'Never')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='How often do you listen to music?', verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_innocent_contact',
            field=models.CharField(choices=[('daily_matters', 'Daily Matters'), ('work_matters', 'Work Matters'), ('doesnt_matter', "Doesn't Matter")], error_messages={'required': 'This field is required. Please select an option.'}, help_text='What is your opinion on innocent contact?', verbose_name='Opinion About Innocent Contact'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='participating_prayer_quran_meetings',
            field=models.CharField(choices=[('too_much', 'Too Much'), ('much', 'Much'), ('average', 'Average'), ('low', 'Low'), ('doesnt_matter', "Doesn't Matter")], error_messages={'required': 'This field is required. Please select an option.'}, help_text='How committed are you to attending prayer and Quran religious meetings?', verbose_name='Participating in Prayer and Quran Religious Meetings'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='worship_prayer',
            field=models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('doesnt_matter', "Doesn't Matter"), ('disagree', 'Disagree')], db_index=True, error_messages={'invalid_choice': 'Invalid selection for worship and prayer habits.', 'required': 'Please describe your worship and prayer habits.'}, help_text='Indicate your level of commitment to worship and prayer.', verbose_name='Worship and Prayer'),
        ),
    ]
