# Generated by Django 4.2.13 on 2025-02-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_alter_introducedsubjectsinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='education',
            field=models.CharField(error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, help_text='Select the education level of the preferred wife.', max_length=50, verbose_name='Education Level'),
        ),
    ]
