# Generated by Django 4.2.13 on 2025-02-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_preferredwifepersonalinformation_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityinformation',
            name='introduced_subjects',
        ),
        migrations.RemoveField(
            model_name='identityinformation',
            name='introduced_subjects_explantions',
        ),
    ]
