# Generated by Django 4.2.13 on 2025-02-16 17:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_remove_identityinformation_introduced_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinformation',
            name='contact_with_relatives',
            field=models.CharField(default=0, error_messages={'max_length': 'Contact with Relatives cannot exceed 50 characters.', 'required': 'Contact with Relatives is required.'}, help_text='Describe the contact with the Relatives.', max_length=150, verbose_name='Contact with Relatives'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='insurance',
            field=models.CharField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('iran', 'Iran'), ('asia', 'Asia'), ('dana', 'Dana'), ('moalem', 'Moalem'), ('parsian', 'Parsian'), ('pasargad', 'Pasargad'), ('Saman', 'Saman'), ('melat', 'Melat'), ('ma', 'Ma'), ('alborz', 'Alborz'), ('kosar', 'Kosar'), ('karafarin', 'Karafarin'), ('novin', 'Novin'), ('day', 'Day'), ('sarmad', 'Sarmad'), ('Razi', 'Razi'), ('taavon', 'Taavon'), ('hafez', 'Hafez'), ('etkayii', 'Etkayii Iranian'), ('tejaratno', 'Tejarat No'), ('khavermiane', 'Khavermiane'), ('hekmat', 'Hekmat Saba'), ('tosehe', 'Tosehe'), ('other', 'Other')], error_messages={'blank': 'Insurance cannot be blank.', 'invalid': 'Insurance is invalid.', 'null': 'Insurance cannot be null.'}, help_text='Select the insurance type of the user.', max_length=50, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_innocent_contact',
            field=models.CharField(choices=[('only_chador', 'Only Chador'), ('formal_manto', 'Formal Manto'), ('colored_chador', 'Colored Chador'), ('cozy_attractive', 'Cozy & Attractive')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Please select the cover type you prefer in contact with someone innocent.', verbose_name='Cover Type in Contact of Innocent'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='fasting',
            field=models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('disagree', 'Disagree'), ('doesnt_matter', "Doesn't Matter"), ('sick', 'Sick')], error_messages={'invalid_choice': 'Invalid selection for fasting habits.', 'required': 'Please specify your fasting habits.'}, help_text='Describe your practice regarding fasting.', verbose_name='Fasting'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_job',
            field=models.CharField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('must_have_job', 'Must have a job'), ('depends_work_env', 'Depends on Work Environment'), ('depends_job_type', 'Depends on Job Type'), ('womanly_job', 'Womanly Job'), ('housejob', 'Housejob'), ('depends_spouse_opinion', 'Depends On Spouse Opinion')], error_messages={'invalid_choice': "The selected option for a woman's job is not valid.", 'required': "Please provide your opinion about a woman's job."}, help_text="Select your opinion about a woman's job and employment status.", verbose_name="Opinion About Woman's Job"),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='degree',
            field=models.CharField(error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the user.', verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('iran', 'Iran'), ('asia', 'Asia'), ('dana', 'Dana'), ('moalem', 'Moalem'), ('parsian', 'Parsian'), ('pasargad', 'Pasargad'), ('Saman', 'Saman'), ('melat', 'Melat'), ('ma', 'Ma'), ('alborz', 'Alborz'), ('kosar', 'Kosar'), ('karafarin', 'Karafarin'), ('novin', 'Novin'), ('day', 'Day'), ('sarmad', 'Sarmad'), ('Razi', 'Razi'), ('taavon', 'Taavon'), ('hafez', 'Hafez'), ('etkayii', 'Etkayii Iranian'), ('tejaratno', 'Tejarat No'), ('khavermiane', 'Khavermiane'), ('hekmat', 'Hekmat Saba'), ('tosehe', 'Tosehe'), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for insurance type.', 'required': 'Insurance type is required.'}, help_text='Select the type of insurance the user has.', max_length=202, verbose_name='Insurance Type'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='military_status',
            field=models.CharField(choices=[('Exemption', 'Exemption'), ('Mother Sponsorship', 'Mother Sponsorship'), ('Father Sponsorship', 'Father Sponsorship'), ('Educational Exemption', 'Educational Exemption'), ('Medical Exemption', 'Medical Exemption'), ('End of Service', 'End of Service'), ('No Service', 'No Service'), ('Woman', 'Woman')], error_messages={'invalid_choice': 'Invalid choice for military status.', 'required': 'Military status is required.'}, help_text='Select the military status of the user.', verbose_name='Military Status'),
        ),
    ]
