# Generated by Django 4.2.13 on 2025-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_familyinformation_contact_with_relatives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinformation',
            name='contact_with_relatives',
            field=models.CharField(error_messages={'max_length': 'Contact with Relatives cannot exceed 50 characters.', 'required': 'Contact with Relatives is required.'}, help_text='Describe the contact with the Relatives.', max_length=150, verbose_name='Contact with Relatives'),
        ),
    ]
