# Generated by Django 4.2.13 on 2025-02-16 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_alter_familyinformation_contact_with_relatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='skin_color',
            field=models.CharField(choices=[('Very Bright', 'Very Bright'), ('Bor', 'Bor'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Green', 'Green'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Normal', 'Normal'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Green', 'Bright Green'), ('other', 'Other')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the user.', max_length=20, verbose_name='Skin Color'),
        ),
    ]
