# Generated by Django 4.2.13 on 2025-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_alter_exhusbandchildstatus_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhusbandchildstatus',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default=1, error_messages={'invalid_choice': 'Invalid choice for gender.', 'required': 'Gender is required.'}, help_text='Select the gender of the user.', max_length=50, verbose_name='Gender'),
        ),
    ]
