# Generated by Django 4.2.13 on 2025-02-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_alter_exhusbandchildstatus_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='brideorwife',
            name='bride_or',
            field=models.CharField(choices=[('bride', 'Bride or Shohar Khahar')], default=1, error_messages={'invalid_choice': 'Selected value for bride or wife is invalid.', 'required': 'Bride or Wife field is required.'}, help_text='Select the bride or wife from the available options.', verbose_name='Bride or Shohar Khahar'),
        ),
        migrations.AddField(
            model_name='groom',
            name='groom_or',
            field=models.CharField(choices=[('groom', 'Zan Dadash')], default=1, error_messages={'invalid_choice': 'Selected value for groom is invalid.', 'required': 'Groom field is required.'}, help_text=('Select the groom from the available options.',), verbose_name='Groom or Zan Dadash'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_innocent_contact',
            field=models.CharField(choices=[('only_chador', 'Only Chador'), ('formal_manto', 'Formal Manto'), ('colored_chador', 'Colored Chador'), ('cozy_attractive', 'Cozy & Attractive')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Select the cover type for innocent contact situations.', verbose_name='Cover Type in Contact of Innocent'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='dance_singing_assemblies',
            field=models.CharField(choices=[('too_much', 'Too Much'), ('much', 'Much'), ('average', 'Average'), ('low', 'Low'), ('never', 'Never')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Select your preference for dance and singing assemblies.', verbose_name='Dance & Singing Assemblies'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='decision_making_choosing_spouse',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dependent', 'Dependent'), ('independet', 'Independet'), ('counsole_with_parents', 'Counsole with Parents'), ('counsole_with_bros_and_siss', 'Counsole with Brothers and Sisters'), ('counsole_with_childs', 'Counsole with Childs'), ('counsole_with_professional', 'Counsole with Professional')], error_messages={'required': 'This field is required. Please select an option for decision making.'}, help_text='Select your decision-making approach when choosing a spouse.', max_length=118, verbose_name='Decision Making in Choosing a Spouse'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='music',
            field=models.CharField(choices=[('too_much', 'Too Much'), ('much', 'Much'), ('average', 'Average'), ('low', 'Low'), ('never', 'Never')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Select your music preference.', verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_innocent_contact',
            field=models.CharField(choices=[('daily_matters', 'Daily Matters'), ('work_matters', 'Work Matters'), ('doesnt_matter', "Doesn't Matter")], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Select your opinion about innocent contacts.', verbose_name='Opinion About Innocent Contact'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='participating_prayer_quran_meetings',
            field=models.CharField(choices=[('too_much', 'Too Much'), ('much', 'Much'), ('average', 'Average'), ('low', 'Low'), ('doesnt_matter', "Doesn't Matter")], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Select your level of participation in prayer and Quran meetings.', verbose_name='Participating in Prayer and Quran Religious Meetings'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='user',
            field=models.OneToOneField(error_messages={'required': 'A unique ID is required.', 'unique': 'This ID already exists. Please use a different one.'}, help_text='Select the user associated with this information.', on_delete=django.db.models.deletion.CASCADE, related_name='intellectual_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
