# Generated by Django 4.2.13 on 2025-02-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_brideorwife_bride_or_groom_groom_or_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brideorwife',
            name='bride_or',
            field=models.CharField(choices=[('bride', 'Bride or Shohar Khahar')], error_messages={'invalid_choice': 'Selected value for bride or wife is invalid.', 'required': 'Bride or Wife field is required.'}, help_text='Select the bride or wife from the available options.', verbose_name='Bride or Shohar Khahar'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='groom_or',
            field=models.CharField(choices=[('groom', 'Zan Dadash')], error_messages={'invalid_choice': 'Selected value for groom is invalid.', 'required': 'Groom field is required.'}, help_text=('Select the groom from the available options.',), verbose_name='Groom or Zan Dadash'),
        ),
    ]
