# Generated by Django 4.2.13 on 2025-02-17 18:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_brideorwife_bride_or_alter_groom_groom_or'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brideorwife',
            name='bride_or',
            field=models.CharField(choices=[('bride', 'Bride'), ('shohar_khahar', 'Shohar Khahar')], error_messages={'invalid_choice': 'Selected value for bride or wife is invalid.', 'required': 'Bride or Wife field is required.'}, help_text='Select the bride or wife from the available options.', verbose_name='Bride or Shohar Khahar'),
        ),
        migrations.AlterField(
            model_name='father',
            name='alive',
            field=models.BooleanField(error_messages={'invalid': 'Invalid value for alive status.', 'required': 'Alive status is required.'}, help_text='Indicate if the parent is alive.', verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='father',
            name='birth_date',
            field=models.DateField(error_messages={'invalid': 'Invalid birth date format.', 'required': 'Birth date is required.'}, help_text='Enter the birth date of the parent.', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='father',
            name='death_date',
            field=models.DateField(blank=True, error_messages={'invalid': 'Invalid death date.', 'max_length': 'Death date format error.'}, help_text='Enter the death date of the parent if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='father',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, help_text='Select the education level of the family member.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='father',
            name='job',
            field=models.CharField(error_messages={'max_length': 'Job cannot exceed 100 characters.', 'required': 'Job is required.'}, help_text='Enter the job of the family member.', max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='father',
            name='language',
            field=models.CharField(error_messages={'max_length': 'Language cannot exceed 50 characters.', 'required': 'Language is required.'}, help_text='Enter the language spoken by the parent.', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='father',
            name='originality',
            field=models.CharField(choices=[('Alborz', 'Alborz'), ('Ardabil', 'Ardabil'), ('Bushehr', 'Bushehr'), ('Chaharmahal and Bakhtiari', 'Chaharmahal and Bakhtiari'), ('East Azerbaijan', 'East Azerbaijan'), ('Esfahan', 'Esfahan'), ('Fars', 'Fars'), ('Gilan', 'Gilan'), ('Golestan', 'Golestan'), ('Hamadan', 'Hamadan'), ('Hormozgan', 'Hormozgan'), ('Ilam', 'Ilam'), ('Kerman', 'Kerman'), ('Kermanshah', 'Kermanshah'), ('Khuzestan', 'Khuzestan'), ('Kohgiluyeh and Boyer-Ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('Kurdistan', 'Kurdistan'), ('Lorestan', 'Lorestan'), ('Markazi', 'Markazi'), ('Mazandaran', 'Mazandaran'), ('North Khorasan', 'North Khorasan'), ('Qazvin', 'Qazvin'), ('Qom', 'Qom'), ('Razavi Khorasan', 'Razavi Khorasan'), ('Semnan', 'Semnan'), ('Sistan and Baluchestan', 'Sistan and Baluchestan'), ('South Khorasan', 'South Khorasan'), ('Tehran', 'Tehran'), ('West Azerbaijan', 'West Azerbaijan'), ('Yazd', 'Yazd'), ('Zanjan', 'Zanjan')], error_messages={'max_length': 'Originality cannot exceed 80 characters.', 'required': 'Originality is required.'}, help_text='Enter the originality of the parent.', verbose_name='Originality'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mecca', 'Mecca'), ('gifts_from_iraq', 'Gifts from Iraq'), ('gifts_from_syria', 'Gifts from Syria'), ('gold_coin', 'Gold Coin'), ('money', 'Money'), ('land', 'Land'), ('car', 'Car'), ('garden', 'Garden'), ('agreement', 'Agreement'), ('house', 'House')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the type of dowry Of Future Wife.', max_length=86, null=True, verbose_name='Future Spouse Dowry Type'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='groom_or',
            field=models.CharField(choices=[('groom', 'Groomm'), ('zan_dadash', 'Zan Dadash')], error_messages={'invalid_choice': 'Selected value for groom is invalid.', 'required': 'Groom field is required.'}, help_text=('Select the groom from the available options.',), verbose_name='Groom or Zan Dadash'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='alive',
            field=models.BooleanField(error_messages={'invalid': 'Invalid value for alive status.', 'required': 'Alive status is required.'}, help_text='Indicate if the parent is alive.', verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='birth_date',
            field=models.DateField(error_messages={'invalid': 'Invalid birth date format.', 'required': 'Birth date is required.'}, help_text='Enter the birth date of the parent.', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='death_date',
            field=models.DateField(blank=True, error_messages={'invalid': 'Invalid death date.', 'max_length': 'Death date format error.'}, help_text='Enter the death date of the parent if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='education',
            field=models.CharField(choices=[('Unlettered', 'Unlettered'), ('Under Diploma', 'Under Diploma'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Hoze (Islamic Seminary) LVL 1', 'Hoze (Islamic Seminary) LVL 1'), ('Hoze (Islamic Seminary) LVL 2', 'Hoze (Islamic Seminary) LVL 2'), ('Hoze (Islamic Seminary) LVL 3', 'Hoze (Islamic Seminary) LVL 3'), ('Hoze (Islamic Seminary) LVL 4', 'Hoze (Islamic Seminary) LVL 4'), ('School & Quranic', 'School & Quranic')], error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, help_text='Select the education level of the family member.', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='job',
            field=models.CharField(error_messages={'max_length': 'Job cannot exceed 100 characters.', 'required': 'Job is required.'}, help_text='Enter the job of the family member.', max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='language',
            field=models.CharField(error_messages={'max_length': 'Language cannot exceed 50 characters.', 'required': 'Language is required.'}, help_text='Enter the language spoken by the parent.', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='originality',
            field=models.CharField(choices=[('Alborz', 'Alborz'), ('Ardabil', 'Ardabil'), ('Bushehr', 'Bushehr'), ('Chaharmahal and Bakhtiari', 'Chaharmahal and Bakhtiari'), ('East Azerbaijan', 'East Azerbaijan'), ('Esfahan', 'Esfahan'), ('Fars', 'Fars'), ('Gilan', 'Gilan'), ('Golestan', 'Golestan'), ('Hamadan', 'Hamadan'), ('Hormozgan', 'Hormozgan'), ('Ilam', 'Ilam'), ('Kerman', 'Kerman'), ('Kermanshah', 'Kermanshah'), ('Khuzestan', 'Khuzestan'), ('Kohgiluyeh and Boyer-Ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('Kurdistan', 'Kurdistan'), ('Lorestan', 'Lorestan'), ('Markazi', 'Markazi'), ('Mazandaran', 'Mazandaran'), ('North Khorasan', 'North Khorasan'), ('Qazvin', 'Qazvin'), ('Qom', 'Qom'), ('Razavi Khorasan', 'Razavi Khorasan'), ('Semnan', 'Semnan'), ('Sistan and Baluchestan', 'Sistan and Baluchestan'), ('South Khorasan', 'South Khorasan'), ('Tehran', 'Tehran'), ('West Azerbaijan', 'West Azerbaijan'), ('Yazd', 'Yazd'), ('Zanjan', 'Zanjan')], error_messages={'max_length': 'Originality cannot exceed 80 characters.', 'required': 'Originality is required.'}, help_text='Enter the originality of the parent.', verbose_name='Originality'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='skin_color',
            field=models.CharField(choices=[('Very Bright', 'Very Bright'), ('Bor', 'Bor'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Green', 'Green'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Green', 'Bright Green'), ('other', 'Other')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the user.', max_length=20, verbose_name='Skin Color'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='skin_color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Very Bright', 'Very Bright'), ('Bor', 'Bor'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Green', 'Green'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Green', 'Bright Green'), ('other', 'Other')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the preferred wife.', max_length=142, verbose_name='Skin Color'),
        ),
    ]
