# Generated by Django 4.2.13 on 2025-02-17 18:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_alter_father_originality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinformation',
            name='insurance',
            field=models.CharField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('iran', 'Iran'), ('asia', 'Asia'), ('dana', 'Dana'), ('moalem', 'Moalem'), ('parsian', 'Parsian'), ('pasargad', 'Pasargad'), ('Saman', 'Saman'), ('melat', 'Melat'), ('ma', 'Ma'), ('alborz_insurance', 'Alborz'), ('kosar', 'Kosar'), ('karafarin', 'Karafarin'), ('novin', 'Novin'), ('day', 'Day'), ('sarmad', 'Sarmad'), ('Razi', 'Razi'), ('taavon', 'Taavon'), ('hafez', 'Hafez'), ('etkayii', 'Etkayii Iranian'), ('tejaratno', 'Tejarat No'), ('khavermiane', 'Khavermiane'), ('hekmat', 'Hekmat Saba'), ('tosehe', 'Tosehe'), ('other', 'Other')], error_messages={'blank': 'Insurance cannot be blank.', 'invalid': 'Insurance is invalid.', 'null': 'Insurance cannot be null.'}, help_text='Select the insurance type of the user.', max_length=50, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('iran', 'Iran'), ('asia', 'Asia'), ('dana', 'Dana'), ('moalem', 'Moalem'), ('parsian', 'Parsian'), ('pasargad', 'Pasargad'), ('Saman', 'Saman'), ('melat', 'Melat'), ('ma', 'Ma'), ('alborz_insurance', 'Alborz'), ('kosar', 'Kosar'), ('karafarin', 'Karafarin'), ('novin', 'Novin'), ('day', 'Day'), ('sarmad', 'Sarmad'), ('Razi', 'Razi'), ('taavon', 'Taavon'), ('hafez', 'Hafez'), ('etkayii', 'Etkayii Iranian'), ('tejaratno', 'Tejarat No'), ('khavermiane', 'Khavermiane'), ('hekmat', 'Hekmat Saba'), ('tosehe', 'Tosehe'), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for insurance type.', 'required': 'Insurance type is required.'}, help_text='Select the type of insurance the user has.', max_length=212, verbose_name='Insurance Type'),
        ),
    ]
