# Generated by Django 4.2.13 on 2025-02-17 19:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_alter_identityinformation_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinformation',
            name='jahiziyeh_explantion',
            field=models.CharField(blank=True, error_messages={'max_length': 'Jahiziyeh explanation cannot exceed 150 characters.', 'required': 'Jahiziyeh explanation is required.'}, help_text='Write the Explanation of Jahiziyeh.', null=True, verbose_name='Future Spose Jahiziyeh Explantion'),
        ),
        migrations.AddField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_veteran_disabled_explanation',
            field=models.CharField(default=1, error_messages={'max_length': 'Marriage With Disabled & Veteran Explanation cannot exceed 150 characters.', 'required': 'Marriage with disabled & Veteran Explanation is required.'}, help_text='Enter the Marriage With Disabled & Veteran Explanation', verbose_name='Marriage with Veteran & Disabled Person Explanation'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mecca', 'Mecca'), ('iraq', 'Iraq'), ('syria', 'Syria'), ('gold', 'Gold'), ('money', 'Money'), ('land', 'Land'), ('car', 'Car'), ('garden', 'Garden'), ('house', 'House'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the type of dowry Of Future Wife.', max_length=59, null=True, verbose_name='Future Spouse Dowry Type'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_status',
            field=models.CharField(choices=[('rights', 'Rights'), ('settled', 'Settled'), ('creditor', 'Creditor'), ('debtor', 'Debtor')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial status.', 'required': 'Ex-spouse financial status is required.'}, help_text='Select the financial status with the ex-spouse.', verbose_name='Ex-Spouse Financial Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='jahiziyeh',
            field=models.CharField(blank=True, choices=[('does', 'Does'), ('doesnt', "Doesn't"), ('wants', 'Wants'), ('doesnt_want', "Doesn't Want"), ('man_should_help', 'Man Should Help'), ('agreement', 'Agreement')], error_messages={'invalid_choice': 'Invalid choice for Jahiziyeh type.', 'required': 'Jahiziyeh type is required.'}, help_text='Select the Status of Jahiziyeh.', null=True, verbose_name='Future Spose Jahiziyeh'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='other_captial',
            field=models.CharField(blank=True, db_index=True, error_messages={'max_length': 'Other capital cannot exceed 150 characters.'}, help_text='Enter the Other capitals owned by the user.', max_length=150, null=True, verbose_name='Other Capital'),
        ),
    ]
