# Generated by Django 4.2.13 on 2025-02-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_financialinformation_jahiziyeh_explantion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_veteran_disabled_explanation',
            field=models.CharField(error_messages={'max_length': 'Marriage With Disabled & Veteran Explanation cannot exceed 150 characters.', 'required': 'Marriage with disabled & Veteran Explanation is required.'}, help_text='Enter the Marriage With Disabled & Veteran Explanation', verbose_name='Marriage with Veteran & Disabled Person Explanation'),
        ),
    ]
