# Generated by Django 4.2.13 on 2025-02-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_alter_preferredwifeintellectualinformation_marriage_with_veteran_disabled_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='degree',
            field=models.CharField(error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the user.', max_length=150, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='military_status_explanation',
            field=models.TextField(blank=True, error_messages={'invalid_choice': 'Invalid choice for military status.', 'required': 'Military status is required.'}, help_text='Provide an explanation for the military status if applicable.', null=True, verbose_name='Military Status Explanation'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='tatto_description',
            field=models.TextField(blank=True, error_messages='Invalid description provided for tattoos.', help_text='Provide details about the tattoos, like where on the body.', null=True, verbose_name='Tatto Description'),
        ),
    ]
