# Generated by Django 4.2.13 on 2025-02-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_alter_personalinformation_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='field_of_study',
            field=models.CharField(error_messages={'max_length': 'Degree cannot exceed 150 characters.', 'required': 'Degree is required.'}, help_text='Enter the degree of the preferred wife.', max_length=150, verbose_name='Field of Study'),
        ),
    ]
