# Generated by Django 4.2.13 on 2025-02-17 19:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_alter_preferredwifepersonalinformation_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='future_spouse_job',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('free', 'Freelance'), ('military', 'Military'), ('office', 'Office'), ('teacher', 'Teacher'), ('hoze_m', 'Hoze M'), ('hoze_n', 'Hoze N'), ('hoze_s', 'hoze Sis'), ('womanly', 'Womanly Job'), ('no_job', 'No Job At All'), ('housekeeper', 'Housekeeper'), ('Doesn’t Matter', 'Doesn’t Matter')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for future spouse job.', 'required': 'Future spouse job is required.'}, help_text='Select the future spouse job of the preferred wife.', max_length=91, verbose_name='Future Spouse Job'),
        ),
    ]
