# Generated by Django 4.2.13 on 2025-02-17 19:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_alter_preferredwifepersonalinformation_future_spouse_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='after_marriage_residence_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mega Cities', 'Mega Cities'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Environs Near Qom', 'Environs Near Qom'), ('Foreign Country', 'Foreign Country'), ('Agreement', 'Agreement')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for after marriage residence location.', 'required': 'After marriage residence location is required.'}, help_text='Select the after marriage residence location of the preferred wife.', max_length=50, verbose_name='After Marriage Residence Location'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='current_residence_location',
            field=models.CharField(db_index=True, error_messages={'max_length': 'Current residence location  cannot exceed 150 characters.', 'required': 'Current residence location is required.'}, help_text='Enter the current residence location of the preferred wife.', max_length=150, verbose_name='Current Residence Location'),
        ),
    ]
