# Generated by Django 4.2.13 on 2025-02-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_alter_preferredwifepersonalinformation_after_marriage_residence_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinformation',
            name='job',
            field=models.CharField(default='None', error_messages={'blank': 'Job cannot be blank.', 'invalid': 'Job is invalid.', 'null': 'Job cannot be null.'}, help_text='Select the job of the user.', max_length=100, verbose_name='Job'),
        ),
    ]
