# Generated by Django 4.2.13 on 2025-02-20 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_alter_father_originality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='father',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, related_name='father', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, related_name='mother', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
