# Generated by Django 4.2.13 on 2025-02-20 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_alter_father_user_alter_mother_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinformation',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this financial information.', on_delete=django.db.models.deletion.CASCADE, related_name='financialinformation', to=settings.AUTH_USER_MODEL),
        ),
    ]
