# Generated by Django 4.2.13 on 2025-02-20 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_alter_financialinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='user',
            field=models.OneToOneField(error_messages={'required': 'User is required.'}, help_text='The user associated with this personal information.', on_delete=django.db.models.deletion.CASCADE, related_name='personalinformation', to=settings.AUTH_USER_MODEL),
        ),
    ]
