# Generated by Django 4.2.13 on 2025-02-20 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_alter_personalinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhusbandchildstatus',
            name='kids',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('+3', '+3')], help_text='Choose the number of Kids', null=True, verbose_name='Kids'),
        ),
        migrations.AlterField(
            model_name='father',
            name='originality',
            field=models.CharField(choices=[('Alborzz', 'Alborzz'), ('Ardabil', 'Ardabil'), ('Bushehr', 'Bushehr'), ('Chaharmahal and Bakhtiari', 'Chaharmahal and Bakhtiari'), ('East Azerbaijan', 'East Azerbaijan'), ('Esfahan', 'Esfahan'), ('Fars', 'Fars'), ('Gilan', 'Gilan'), ('Golestan', 'Golestan'), ('Hamadan', 'Hamadan'), ('Hormozgan', 'Hormozgan'), ('Ilam', 'Ilam'), ('Kerman', 'Kerman'), ('Kermanshah', 'Kermanshah'), ('Khuzestan', 'Khuzestan'), ('Kohgiluyeh and Boyer-Ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('Kurdistan', 'Kurdistan'), ('Lorestan', 'Lorestan'), ('Markazi', 'Markazi'), ('Mazandaran', 'Mazandaran'), ('North Khorasan', 'North Khorasan'), ('Qazvin', 'Qazvin'), ('Qom', 'Qom'), ('Razavi Khorasan', 'Razavi Khorasan'), ('Semnan', 'Semnan'), ('Sistan and Baluchestan', 'Sistan and Baluchestan'), ('South Khorasan', 'South Khorasan'), ('Tehran', 'Tehran'), ('West Azerbaijan', 'West Azerbaijan'), ('Yazd', 'Yazd'), ('Zanjan', 'Zanjan'), ('doesnt_matter', "Doesn't Matter")], error_messages={'max_length': 'Originality cannot exceed 80 characters.', 'required': 'Originality is required.'}, help_text='Enter the originality of the parent.', verbose_name='Originality'),
        ),
        migrations.AlterField(
            model_name='futuresposeoriginality',
            name='future_spouse_originality',
            field=models.CharField(choices=[('Alborzz', 'Alborzz'), ('Ardabil', 'Ardabil'), ('Bushehr', 'Bushehr'), ('Chaharmahal and Bakhtiari', 'Chaharmahal and Bakhtiari'), ('East Azerbaijan', 'East Azerbaijan'), ('Esfahan', 'Esfahan'), ('Fars', 'Fars'), ('Gilan', 'Gilan'), ('Golestan', 'Golestan'), ('Hamadan', 'Hamadan'), ('Hormozgan', 'Hormozgan'), ('Ilam', 'Ilam'), ('Kerman', 'Kerman'), ('Kermanshah', 'Kermanshah'), ('Khuzestan', 'Khuzestan'), ('Kohgiluyeh and Boyer-Ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('Kurdistan', 'Kurdistan'), ('Lorestan', 'Lorestan'), ('Markazi', 'Markazi'), ('Mazandaran', 'Mazandaran'), ('North Khorasan', 'North Khorasan'), ('Qazvin', 'Qazvin'), ('Qom', 'Qom'), ('Razavi Khorasan', 'Razavi Khorasan'), ('Semnan', 'Semnan'), ('Sistan and Baluchestan', 'Sistan and Baluchestan'), ('South Khorasan', 'South Khorasan'), ('Tehran', 'Tehran'), ('West Azerbaijan', 'West Azerbaijan'), ('Yazd', 'Yazd'), ('Zanjan', 'Zanjan'), ('doesnt_matter', "Doesn't Matter")], error_messages={'invalid_choice': 'Invalid choice for future spouse originality.', 'required': 'Future spouse originality is required.'}, help_text='Select the originality of the future spouse.', verbose_name='Future Spouse Originality'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='originality',
            field=models.CharField(choices=[('Alborzz', 'Alborzz'), ('Ardabil', 'Ardabil'), ('Bushehr', 'Bushehr'), ('Chaharmahal and Bakhtiari', 'Chaharmahal and Bakhtiari'), ('East Azerbaijan', 'East Azerbaijan'), ('Esfahan', 'Esfahan'), ('Fars', 'Fars'), ('Gilan', 'Gilan'), ('Golestan', 'Golestan'), ('Hamadan', 'Hamadan'), ('Hormozgan', 'Hormozgan'), ('Ilam', 'Ilam'), ('Kerman', 'Kerman'), ('Kermanshah', 'Kermanshah'), ('Khuzestan', 'Khuzestan'), ('Kohgiluyeh and Boyer-Ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('Kurdistan', 'Kurdistan'), ('Lorestan', 'Lorestan'), ('Markazi', 'Markazi'), ('Mazandaran', 'Mazandaran'), ('North Khorasan', 'North Khorasan'), ('Qazvin', 'Qazvin'), ('Qom', 'Qom'), ('Razavi Khorasan', 'Razavi Khorasan'), ('Semnan', 'Semnan'), ('Sistan and Baluchestan', 'Sistan and Baluchestan'), ('South Khorasan', 'South Khorasan'), ('Tehran', 'Tehran'), ('West Azerbaijan', 'West Azerbaijan'), ('Yazd', 'Yazd'), ('Zanjan', 'Zanjan'), ('doesnt_matter', "Doesn't Matter")], error_messages={'max_length': 'Originality cannot exceed 80 characters.', 'required': 'Originality is required.'}, help_text='Enter the originality of the parent.', verbose_name='Originality'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this preferred wife information.', on_delete=django.db.models.deletion.CASCADE, related_name='preferred_wife_intellectual_information', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
