# Generated by Django 4.2.13 on 2025-02-20 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_exhusbandchildstatus_kids_alter_father_originality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhusbandchildstatus',
            name='kids',
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='kids',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('+3', '+3')], help_text='Choose the number of Kids', null=True, verbose_name='Kids'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, related_name='family_information', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
