# Generated by Django 4.2.13 on 2025-02-20 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_remove_exhusbandchildstatus_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='user',
            field=models.ForeignKey(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='user',
            field=models.OneToOneField(help_text='Select the user associated with this family information.', on_delete=django.db.models.deletion.CASCADE, related_name='family_information', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
