# Generated by Django 4.2.13 on 2025-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_alter_exhusbandchildstatus_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='have_insurance',
            field=models.BooleanField(default=True, help_text='Select the type of insurance the user has.', verbose_name='Have Insurance'),
        ),
    ]
