# Generated by Django 4.2.13 on 2025-03-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_personalinformation_have_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'blank': 'First name cannot be blank.', 'max_length': 'First name cannot exceed 150 characters.', 'null': 'First name cannot be null.'}, help_text='150 characters or fewer.', max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, error_messages={'blank': 'Last name cannot be blank.', 'max_length': 'Last name cannot exceed 150 characters.', 'null': 'Last name cannot be null.'}, help_text='150 characters or fewer.', max_length=150, null=True, verbose_name='last name'),
        ),
    ]
