# Generated by Django 4.2.13 on 2025-03-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
