# Generated by Django 4.2.13 on 2025-03-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='tatoo',
            field=models.BooleanField(db_index=True, default=False, error_messages={'invalid': 'Invalid value for the tattoo field.'}, help_text='Indicate whether the user has any tattoos.', verbose_name='Tatto'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='tatto_description',
            field=models.TextField(blank=True, error_messages={'invalid': 'Invalid description provided for tattoos.'}, help_text='Provide details about the tattoos, like where on the body.', null=True, verbose_name='Tatto Description'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='usage_case_description',
            field=models.TextField(blank=True, error_messages={'invalid': 'Invalid usage case description.'}, help_text='Provide additional details about usage cases. Like how many cigars or hookah a day.', null=True, verbose_name='Usage Case Description'),
        ),
    ]
