# Generated by Django 4.2.20 on 2025-07-05 13:12

import core.utils.validators.preferred_wife_validators
import core.utils.validators.shared
import core.utils.validators.user_validators
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_alter_personalinformation_tatoo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brideorwife',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, validators=[django.core.validators.RegexValidator(message='Job must contain only letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\u0600-\\u06FF-]+$')], verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, validators=[django.core.validators.RegexValidator(message='Job must contain only letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\u0600-\\u06FF-]+$')], verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='living_location',
            field=models.CharField(blank=True, help_text='Enter the living location if applicable.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Contact information must contain only letters, spaces, and basic punctuation', regex='^[a-zA-Z\\s\\u0600-\\u06FF,.]+$')], verbose_name='Living Location'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='contact_with_family',
            field=models.CharField(error_messages={'max_length': 'Contact with family cannot exceed 50 characters.', 'required': 'Contact with family is required.'}, help_text='Describe the contact with the family.', max_length=150, validators=[django.core.validators.RegexValidator(message='Contact information must contain only letters, spaces, and basic punctuation', regex='^[a-zA-Z\\s\\u0600-\\u06FF,.]+$')], verbose_name='Contact with Family'),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='contact_with_relatives',
            field=models.CharField(error_messages={'max_length': 'Contact with Relatives cannot exceed 50 characters.', 'required': 'Contact with Relatives is required.'}, help_text='Describe the contact with the Relatives.', max_length=150, validators=[django.core.validators.RegexValidator(message='Contact information must contain only letters, spaces, and basic punctuation', regex='^[a-zA-Z\\s\\u0600-\\u06FF,.]+$')], verbose_name='Contact with Relatives'),
        ),
        migrations.AlterField(
            model_name='father',
            name='death_date',
            field=models.DateField(blank=True, help_text='Enter the death date if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='father',
            name='job',
            field=models.CharField(error_messages={'max_length': 'Job cannot exceed 100 characters.', 'required': 'Job is required.'}, help_text='Enter the job of the family member.', max_length=100, validators=[django.core.validators.RegexValidator(message='Job must contain only letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\u0600-\\u06FF-]+$')], verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='father',
            name='language',
            field=models.CharField(error_messages={'max_length': 'Language cannot exceed 50 characters.', 'required': 'Language is required.'}, help_text='Enter the language spoken by the parent.', max_length=50, validators=[django.core.validators.RegexValidator(message='Language must contain only letters, spaces, and commas', regex='^[a-zA-Z\\s\\u0600-\\u06FF,]+$')], verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_amount',
            field=models.CharField(error_messages={'max_length': 'Dowry amount cannot exceed 50 characters.', 'required': 'Dowry amount is required.'}, help_text='Enter the dowry amount in the local currency or gold.', max_length=50, validators=[django.core.validators.RegexValidator(message='Amount must contain only numbers and commas', regex='^[0-9,]+$')], verbose_name='Future Spose Dowry Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_amount',
            field=models.CharField(blank=True, error_messages={'max_length': 'Ex-spouse financial amount cannot exceed 50 characters.', 'required': 'Ex-spouse financial amount is required.'}, help_text='Enter the financial amount related to the ex-spouse.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Amount must contain only numbers and commas', regex='^[0-9,]+$')], verbose_name='Ex-Spouse Financial Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='mortgage_amount',
            field=models.CharField(blank=True, error_messages={'invalid': 'Invalid value for mortgage amount.', 'required': 'Mortgage amount is required.'}, help_text='Enter the mortgage amount in the local currency.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Amount must contain only numbers and commas', regex='^[0-9,]+$')], verbose_name='Mortgage Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='rent_amount',
            field=models.CharField(blank=True, error_messages={'invalid': 'Invalid value for rent amount.', 'required': 'Rent amount is required.'}, help_text='Enter the rent amount in the local currency.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Amount must contain only numbers and commas', regex='^[0-9,]+$')], verbose_name='Rent Amount'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, validators=[django.core.validators.RegexValidator(message='Job must contain only letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\u0600-\\u06FF-]+$')], verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cons_of_yourself',
            field=models.TextField(error_messages={'max_length': 'Your cons should not exceed 1000 characters.', 'required': 'Please list some of your negative attributes.'}, help_text='List aspects of yourself you wish to improve.', validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_pros_cons], verbose_name='Cons Of Yourself'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='friends_connection_reason',
            field=models.CharField(error_messages={'max_length': 'Your explanation should not exceed 500 characters.', 'required': 'Please explain why you maintain connections with your friends.'}, help_text='Explain why you connect with friends.', max_length=100, validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_friends_connection_reason], verbose_name='Friends Connection Reason'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='marriage_goals',
            field=models.TextField(error_messages={'max_length': 'Marriage goals should not exceed 1000 characters.', 'required': 'Marriage goals and purposes cannot be empty.'}, help_text='Describe your goals and purposes for marriage in detail.', validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_marriage_goals], verbose_name='Marriage Goals & Purposes'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_edu',
            field=models.CharField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('depends_degree', 'Depends on the Degree'), ('depends_spouse_opinion', 'Depends On Spouse Opinion')], error_messages={'invalid_choice': "The selected option for a woman's education is not valid.", 'required': "Please provide your opinion about a woman's education."}, help_text="Choose your stance on women's education.", validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_opinion_woman_edu], verbose_name="Opinion About Woman's Education"),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_job',
            field=models.CharField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('must_have_job', 'Must have a job'), ('depends_work_env', 'Depends on Work Environment'), ('depends_job_type', 'Depends on Job Type'), ('womanly_job', 'Womanly Job'), ('housejob', 'Housejob'), ('depends_spouse_opinion', 'Depends On Spouse Opinion')], error_messages={'invalid_choice': "The selected option for a woman's job is not valid.", 'required': "Please provide your opinion about a woman's job."}, help_text="Select your opinion about a woman's job and employment status.", validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_opinion_woman_job], verbose_name="Opinion About Woman's Job"),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='pros_of_yourself',
            field=models.TextField(error_messages={'max_length': 'Your pros should not exceed 1000 characters.', 'required': 'Please list some of your positive attributes.'}, help_text='List positive traits about yourself.', validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_pros_cons], verbose_name='Pros Of Yourself'),
        ),
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='birth_date',
            field=models.DateField(error_messages={'blank': 'Birth date cannot be blank.', 'invalid': 'Birth date is invalid.', 'null': 'Birth date cannot be null.'}, help_text='Enter the birth date of the user.', validators=[core.utils.validators.user_validators.ConfidentialInfoValidator.validate_birth_date], verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='cost_of_introduction',
            field=models.CharField(error_messages={'max_length': 'The cost of introduction cannot exceed 100 characters.', 'required': 'The cost of introduction is required.'}, help_text='Specify the cost associated with the introduction.', max_length=100, validators=[core.utils.validators.user_validators.PaymentValidator.validate_cost], verbose_name='Cost of Introduction'),
        ),
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='cost_of_meeting',
            field=models.CharField(error_messages={'max_length': 'The cost of meeting cannot exceed 100 characters.', 'required': 'The cost of meeting is required.'}, help_text='Specify the cost associated with the meetings.', max_length=100, validators=[core.utils.validators.user_validators.PaymentValidator.validate_cost], verbose_name='Cost of Meeting'),
        ),
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='dates_of_meetings',
            field=models.TextField(error_messages={'required': 'You must provide the dates of meetings.'}, help_text='List the dates of meetings with the introduced subject.', validators=[core.utils.validators.user_validators.IntroducedSubjectsValidator.validate_dates_of_meetings], verbose_name='Dates Of Meetings'),
        ),
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='reason',
            field=models.TextField(error_messages={'required': "A reason for the introduction's outcome is required."}, help_text="Provide a detailed reason for the introduction's outcome.", validators=[core.utils.validators.user_validators.IntroducedSubjectsValidator.validate_reason], verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='result_and_regards',
            field=models.TextField(error_messages={'required': 'You must summarize the results and any regards from the meetings.'}, help_text='Summarize the results and any regards from the meetings.', validators=[core.utils.validators.user_validators.IntroducedSubjectsValidator.validate_result_and_regards], verbose_name='Result & Regards'),
        ),
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='user',
            field=models.ForeignKey(error_messages={'required': 'User is required.'}, help_text='Select the user associated with this information.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='username',
            field=models.CharField(error_messages={'max_length': 'The username cannot exceed 50 characters.', 'required': 'The username is required.'}, help_text='Enter the username of the introduced subject. This should be unique and descriptive.', max_length=50, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, and underscores', regex='^[a-zA-Z0-9_]+$')], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='death_date',
            field=models.DateField(blank=True, help_text='Enter the death date if applicable.', null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='job',
            field=models.CharField(error_messages={'max_length': 'Job cannot exceed 100 characters.', 'required': 'Job is required.'}, help_text='Enter the job of the family member.', max_length=100, validators=[django.core.validators.RegexValidator(message='Job must contain only letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\u0600-\\u06FF-]+$')], verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='language',
            field=models.CharField(error_messages={'max_length': 'Language cannot exceed 50 characters.', 'required': 'Language is required.'}, help_text='Enter the language spoken by the parent.', max_length=50, validators=[django.core.validators.RegexValidator(message='Language must contain only letters, spaces, and commas', regex='^[a-zA-Z\\s\\u0600-\\u06FF,]+$')], verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_date',
            field=models.DateField(db_index=True, error_messages={'invalid': 'Invalid birth date format.', 'required': 'Birth date is required.'}, help_text='Enter the birth date of the user.', validators=[core.utils.validators.user_validators.PersonalInformationValidator.validate_birth_date], verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='glasses_size',
            field=models.CharField(blank=True, error_messages={'invalid': 'Invalid glasses size value.'}, help_text='Enter the size of the glasses if applicable.', null=True, validators=[django.core.validators.RegexValidator(message='Glasses size must be a valid number', regex='^[-+]?\\d*\\.?\\d+$')], verbose_name='Glasses Size'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='height',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid height value.', 'max_value': 'Height cannot exceed 260 cm.', 'required': 'Height is required.'}, help_text='Enter the height of the user in centimeters.', max_digits=5, validators=[django.core.validators.MinValueValidator(140, 'Height must be at least 140cm'), django.core.validators.MaxValueValidator(260, 'Height must be at most 260cm')], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='weight',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid weight value.', 'max_value': 'Weight cannot exceed 300 kg.', 'required': 'Weight is required.'}, help_text='Enter the weight of the user in kilograms.', max_digits=5, validators=[django.core.validators.MinValueValidator(35, 'Weight must be at least 35kg'), django.core.validators.MaxValueValidator(300, 'Weight must be at most 300kg')], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='preferredwifeextrainformation',
            name='additional_explanations',
            field=models.TextField(error_messages={'required': 'Additional explanations are required.'}, help_text='Enter any additional information that is not included in the form.', validators=[core.utils.validators.preferred_wife_validators.PreferredWifeExtraInformationValidator.validate_additional_explanations], verbose_name='Additional Explanations'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_veteran_disabled_explanation',
            field=models.CharField(error_messages={'max_length': 'Marriage With Disabled & Veteran Explanation cannot exceed 150 characters.', 'required': 'Marriage with disabled & Veteran Explanation is required.'}, help_text='Enter the Marriage With Disabled & Veteran Explanation', validators=[core.utils.validators.preferred_wife_validators.PreferredWifeIntellectualInformationValidator.validate_disabled_veteran_explanation], verbose_name='Marriage with Veteran & Disabled Person Explanation'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='most_important_moral_feature_of_future_spouse',
            field=models.TextField(error_messages={'required': 'Most important moral feature of future spouse is required.'}, help_text='Enter the most important moral feature of the future spouse.', validators=[core.utils.validators.preferred_wife_validators.PreferredWifeIntellectualInformationValidator.validate_moral_feature], verbose_name='Most Important Moral Feature of Future Spouse'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='red_flags',
            field=models.TextField(error_messages={'required': 'Red flags are required.'}, help_text='Enter any red flags for the future spouse.', validators=[core.utils.validators.preferred_wife_validators.PreferredWifeIntellectualInformationValidator.validate_red_flags], verbose_name='Red Flags'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='current_residence_location',
            field=models.CharField(db_index=True, error_messages={'max_length': 'Current residence location  cannot exceed 150 characters.', 'required': 'Current residence location is required.'}, help_text='Enter the current residence location of the preferred wife.', max_length=150, validators=[django.core.validators.RegexValidator(message='Location must contain only letters, spaces, and basic punctuation', regex='^[a-zA-Z\\s\\u0600-\\u06FF,.-]+$')], verbose_name='Current Residence Location'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='education',
            field=models.CharField(error_messages={'invalid_choice': 'Invalid choice for education.', 'required': 'Education is required.'}, help_text='Select the education level of the preferred wife.', max_length=50, validators=[django.core.validators.RegexValidator(message='Education level must contain only letters and spaces', regex='^[a-zA-Z\\s\\u0600-\\u06FF]+$')], verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='field_of_study',
            field=models.CharField(error_messages={'max_length': 'Degree cannot exceed 150 characters.', 'required': 'Degree is required.'}, help_text='Enter the degree of the preferred wife.', max_length=150, validators=[django.core.validators.RegexValidator(message='Field of study must contain only letters and spaces', regex='^[a-zA-Z\\s\\u0600-\\u06FF]+$')], verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='height',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid height value.', 'required': 'Height is required.'}, help_text='Enter the height of the preferred wife in centimeters.', max_digits=5, validators=[django.core.validators.MinValueValidator(140, 'Height must be at least 140cm'), django.core.validators.MaxValueValidator(260, 'Height must be at most 260cm')], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='weight',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid weight value.', 'required': 'Weight is required.'}, help_text='Enter the weight of the preferred wife in kilograms.', max_digits=5, validators=[django.core.validators.MinValueValidator(35, 'Weight must be at least 35kg'), django.core.validators.MaxValueValidator(300, 'Weight must be at most 300kg')], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='sister',
            name='job',
            field=models.CharField(help_text='Enter the job of the family member.', max_length=100, validators=[django.core.validators.RegexValidator(message='Job must contain only letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\u0600-\\u06FF-]+$')], verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.CharField(error_messages={'blank': 'Access code cannot be blank.', 'invalid': 'Access code is invalid.', 'null': 'Access code cannot be null.'}, help_text='Required access code for initial user creation.', max_length=50, validators=[core.utils.validators.shared.validate_active_access_code, core.utils.validators.user_validators.UserValidator.validate_access_code], verbose_name='User Access Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'Email cannot be blank.', 'invalid': 'Email is invalid.', 'null': 'Email cannot be null.', 'unique': 'This email is already taken.'}, help_text='Email format accepted.', max_length=254, null=True, validators=[core.utils.validators.user_validators.UserValidator.validate_email], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_man_code',
            field=models.CharField(blank=True, error_messages={'blank': 'Middle man code cannot be blank.', 'invalid': 'Middle man code is invalid.', 'null': 'Middle man code cannot be null.'}, help_text='Optional Username or Full Name for middle man reference.', max_length=100, null=True, validators=[core.utils.validators.user_validators.UserValidator.validate_middle_man_code], verbose_name='Middle man code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username cannot be blank.', 'invalid': 'Username is invalid.', 'max_length': 'Username cannot exceed 150 characters.', 'null': 'Username cannot be null.', 'unique': 'This username is already taken.'}, help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), core.utils.validators.user_validators.UserValidator.validate_username], verbose_name='username'),
        ),
    ]
