# Generated by Django 4.2.20 on 2025-07-05 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinformation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this record was created.', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this user joined.', verbose_name='Date Joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialinformation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this record was created.', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialinformation',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this user joined.', verbose_name='Date Joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='introducedsubjectsinformation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this record was created.', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='introducedsubjectsinformation',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this subject joined.', verbose_name='Date Joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this record was created.', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this user joined.', verbose_name='Date Joined'),
            preserve_default=False,
        ),
    ]
