# Generated by Django 4.2.20 on 2025-07-05 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_intellectualinformation_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementorweddingstatus',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this record was created.', verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engagementorweddingstatus',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this user joined.', verbose_name='Date Joined'),
            preserve_default=False,
        ),
    ]
