# Generated by Django 4.2.20 on 2025-07-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0111_identityinformation_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introducedsubjectsinformation',
            name='date_joined',
            field=models.DateTimeField(help_text='The date this subject joined.', verbose_name='Date Joined'),
        ),
    ]
