# Generated by Django 4.2.20 on 2025-07-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_alter_introducedsubjectsinformation_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinformation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='financialinformation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='intellectualinformation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='intellectualinformation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='introducedsubjectsinformation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='introducedsubjectsinformation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='physicalinformation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='physicalinformation',
            name='date_joined',
        ),
    ]
