# Generated by Django 4.2.20 on 2025-07-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_remove_financialinformation_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementorweddingstatus',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='engagementorweddingstatus',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='identityinformation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='identityinformation',
            name='date_joined',
        ),
    ]
