# Generated by Django 4.2.20 on 2025-07-06 07:12

import core.utils.validators.user_validators
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0114_remove_engagementorweddingstatus_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introducedsubjectsinformation',
            name='marriage_status',
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_edu',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('depends_degree', 'Depends on the Degree'), ('depends_spouse_opinion', 'Depends On Spouse Opinion')], error_messages={'invalid_choice': "The selected option for a woman's education is not valid.", 'required': "Please provide your opinion about a woman's education."}, help_text="Choose your stance on women's education.", max_length=52, validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_opinion_woman_edu], verbose_name="Opinion About Woman's Education"),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='body_and_face',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Suitable', 'Suitable'), ('Nice Face', 'Nice Face'), ('Nice Body', 'Nice Body'), ('Looks Older', 'Looks Older'), ('Looks Younger', 'Looks Younger'), ('Satisfied', 'Satisfied'), ('None', 'None')], error_messages={'invalid_choice': 'Invalid choice for body and face.', 'required': 'Body and face is required.'}, help_text='Select the body and face characteristics of the user.', max_length=20, verbose_name='Body and Face'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='height',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid height value.', 'max_value': 'Height cannot exceed 260 cm.', 'required': 'Height is required.'}, help_text='Enter the height of the user in centimeters.', max_digits=5, validators=[django.core.validators.MinValueValidator(100, 'Height must be at least 100cm'), django.core.validators.MaxValueValidator(260, 'Height must be at most 260cm')], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='height',
            field=models.DecimalField(db_index=True, decimal_places=2, error_messages={'invalid': 'Invalid height value.', 'required': 'Height is required.'}, help_text='Enter the height of the preferred wife in centimeters.', max_digits=5, validators=[django.core.validators.MinValueValidator(100, 'Height must be at least 100cm'), django.core.validators.MaxValueValidator(260, 'Height must be at most 260cm')], verbose_name='Height'),
        ),
    ]
