# Generated by Django 4.2.20 on 2025-07-06 07:13

import core.utils.validators.user_validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_remove_introducedsubjectsinformation_marriage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_edu',
            field=models.CharField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('depends_degree', 'Depends on the Degree'), ('depends_spouse_opinion', 'Depends On Spouse Opinion')], error_messages={'invalid_choice': "The selected option for a woman's education is not valid.", 'required': "Please provide your opinion about a woman's education."}, help_text="Choose your stance on women's education.", validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_opinion_woman_edu], verbose_name="Opinion About Woman's Education"),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_job',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('must_have_job', 'Must have a job'), ('depends_work_env', 'Depends on Work Environment'), ('depends_job_type', 'Depends on Job Type'), ('womanly_job', 'Womanly Job'), ('housejob', 'Housejob'), ('depends_spouse_opinion', 'Depends On Spouse Opinion')], error_messages={'invalid_choice': "The selected option for a woman's job is not valid.", 'required': "Please provide your opinion about a woman's job."}, help_text="Select your opinion about a woman's job and employment status.", max_length=106, validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_opinion_woman_job], verbose_name="Opinion About Woman's Job"),
        ),
    ]
