# Generated by Django 4.2.20 on 2025-07-06 16:33

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0116_alter_intellectualinformation_opinion_woman_edu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinformation',
            name='kids',
        ),
        migrations.AddField(
            model_name='intellectualinformation',
            name='fasting_explanation',
            field=models.CharField(default=1, error_messages={'required': 'Please provide an explanation if you cannot fast due to sickness.'}, help_text='If you cannot fast due to sickness, please explain your condition.', max_length=150, verbose_name='Fasting Explanation (sickness that makes him not be able to fast)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='reason_for_divorce_or_death',
            field=models.CharField(help_text='Specify the reason for divorce or death if applicable.', max_length=100, null=True, verbose_name='Reason for Divorce or Death'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Engagement', 'Engagement'), ('Contract', 'Contract'), ('Wedding', 'Wedding'), ('None', 'None')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for engagement or wedding status.', 'required': 'Engagement or wedding status is required.'}, help_text='If user has engagment or related history', max_length=50, verbose_name='Person Status'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='custody',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Independant', 'Independant'), ('Other', 'Other')], help_text='Select the custody status of the children.', max_length=50, verbose_name='Custody'),
        ),
        migrations.AlterField(
            model_name='exhusbandchildstatus',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl')], error_messages={'invalid_choice': 'Invalid choice for gender.', 'required': 'Gender is required.'}, help_text='Select the gender of the user.', max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='capital',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('house', 'House'), ('shop', 'Shop'), ('land', 'Land'), ('garden', 'Garden'), ('factory', 'Factory'), ('company', 'Company'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('gold', 'Gold'), ('other', 'Other'), ('none', 'I dont Have Any')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for capital.', 'required': 'Capital is required.'}, help_text='Select the types of capital owned by the user.', max_length=69, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_amount',
            field=models.CharField(error_messages={'max_length': 'Dowry amount cannot exceed 50 characters.', 'required': 'Dowry amount is required.'}, help_text='Enter the dowry amount in the local currency or gold.', max_length=50, validators=[django.core.validators.RegexValidator(message='Amount must contain only letters, numbers, spaces, Persian characters, and commas', regex='^[a-zA-Z0-9,\\s\\u0600-\\u06FF]+$')], verbose_name='Future Spose Dowry Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_amount',
            field=models.CharField(blank=True, error_messages={'max_length': 'Ex-spouse financial amount cannot exceed 50 characters.', 'required': 'Ex-spouse financial amount is required.'}, help_text='Enter the financial amount related to the ex-spouse.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Amount must contain only letters, numbers, spaces, Persian characters, and commas', regex='^[a-zA-Z0-9,\\s\\u0600-\\u06FF]+$')], verbose_name='Ex-Spouse Financial Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_status',
            field=models.CharField(choices=[('rights', 'Rights'), ('settled', 'Settled'), ('creditor', 'Creditor'), ('debtor', 'Debtor'), ('female', 'Female')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial status.', 'required': 'Ex-spouse financial status is required.'}, help_text='Select the financial status with the ex-spouse.', verbose_name='Ex-Spouse Financial Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='mortgage_amount',
            field=models.CharField(blank=True, error_messages={'invalid': 'Invalid value for mortgage amount.', 'required': 'Mortgage amount is required.'}, help_text='Enter the mortgage amount in the local currency.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Amount must contain only letters, numbers, spaces, Persian characters, and commas', regex='^[a-zA-Z0-9,\\s\\u0600-\\u06FF]+$')], verbose_name='Mortgage Amount'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='rent_amount',
            field=models.CharField(blank=True, error_messages={'invalid': 'Invalid value for rent amount.', 'required': 'Rent amount is required.'}, help_text='Enter the rent amount in the local currency.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Amount must contain only letters, numbers, spaces, Persian characters, and commas', regex='^[a-zA-Z0-9,\\s\\u0600-\\u06FF]+$')], verbose_name='Rent Amount'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='assets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('house', 'House'), ('shop', 'Shop'), ('land', 'Land'), ('garden', 'Garden'), ('factory', 'Factory'), ('company', 'Company'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('gold', 'Gold'), ('other', 'Other'), ('none', 'I dont Have Any')], error_messages={'blank': 'Assets cannot be blank.', 'max_length': 'Assets cannot exceed 150 characters.', 'null': 'Assets cannot be null.'}, help_text='Enter the assets of the user.', max_length=69, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='income',
            field=models.CharField(choices=[('no_income', 'No Income'), ('-10', 'Under 10M'), ('10-20', 'Between 10M to 20M'), ('20-30', 'Between 20M to 30M'), ('30-40', 'Between 30M to 40M'), ('40-50', 'Between 40M to 50M'), ('50-100', 'Between 50M to 100M'), ('+100', 'Plus 100')], error_messages={'blank': 'Income cannot be blank.', 'invalid': 'Income is invalid.', 'null': 'Income cannot be null.'}, help_text='Enter the income of the user in Tooman.', verbose_name='Income in Tooman'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_house',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cozy_attractive', 'Cozy & Attractive'), ('normal', 'Normal')], error_messages={'invalid_choice': 'Invalid selection for house covering type.', 'required': 'Please specify the type of covering you use at home.'}, help_text='Choose your preferred clothing style at home.', max_length=22, verbose_name='Cover Type in House'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_innocent_contact',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('only_chador', 'Only Chador'), ('formal_manto', 'Formal Manto'), ('colored_chador', 'Colored Chador'), ('cozy_attractive', 'Cozy & Attractive')], error_messages={'required': 'This field is required. Please select an option.'}, help_text='Select the cover type for innocent contact situations.', max_length=55, verbose_name='Cover Type in Contact of Innocent'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='cover_type_society',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('always_chador', 'Always Chador'), ('always_coverd_manto', 'Always Coverd Manto'), ('always_free_manto', 'Always Free Manto'), ('sometimes_chador', 'Sometimes Chador'), ('sometimes_coverd_manto', 'Sometimes Coverd Manto'), ('sometimes_free_manto', 'Sometimes Free Manto')], error_messages={'invalid_choice': 'Invalid selection for society and workplace covering type.', 'required': 'Please specify the type of covering you use in society and workplace.'}, help_text='Select your dress preference in society and the workplace.', max_length=112, verbose_name='Cover Type in Society & Workplace'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='fasting',
            field=models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('obligated_but_lazy', 'Obligated But Lazy'), ('disagree', 'Disagree'), ('doesnt_matter', "Doesn't Matter"), ('sick', 'Sick')], error_messages={'invalid_choice': 'Invalid selection for fasting habits.', 'required': 'Please specify your fasting habits.'}, help_text='Describe your practice regarding fasting.', verbose_name='Fasting'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='worship_prayer',
            field=models.CharField(choices=[('fully_obligated', 'Fully Obligated'), ('sometimes', 'Sometimes'), ('not_obligated', 'Not Obligated'), ('obligated_but_lazy', 'Obligated But Lazy'), ('doesnt_matter', "Doesn't Matter"), ('disagree', 'Disagree')], db_index=True, error_messages={'invalid_choice': 'Invalid selection for worship and prayer habits.', 'required': 'Please describe your worship and prayer habits.'}, help_text='Indicate your level of commitment to worship and prayer.', verbose_name='Worship and Prayer'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='deposit',
            field=models.CharField(choices=[('no_deposit', 'No Deposit'), ('-50', 'Under 50M'), ('50-100', 'Between 50M to 100M'), ('100-200', 'Between 100M to 200M'), ('200-500', 'Between 200M to 500M'), ('+500', 'Plus 500M')], error_messages={'invalid': 'Invalid deposit value.', 'required': 'Deposit is required.'}, help_text='Enter the deposit amount of the user.', verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('boy', 'Boy'), ('girl', 'Girl'), ('seperated', 'Seperated'), ('deceased', 'Deceased')], error_messages={'invalid_choice': 'Invalid choice for gender.', 'required': 'Gender is required.'}, help_text='Select the gender of the user.', max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='income',
            field=models.CharField(choices=[('no_income', 'No Income'), ('-10', 'Under 10M'), ('10-20', 'Between 10M to 20M'), ('20-30', 'Between 20M to 30M'), ('30-40', 'Between 30M to 40M'), ('40-50', 'Between 40M to 50M'), ('50-100', 'Between 50M to 100M'), ('+100', 'Plus 100')], db_index=True, error_messages={'invalid': 'Invalid income value.', 'required': 'Income is required.'}, help_text='Enter the income of the user.', verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='leisure_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Park', 'Park'), ('Trip', 'Trip'), ('Family', 'Family'), ('working_from_home', 'Working from home'), ('Mobile', 'Mobile'), ('Reading', 'Reading'), ('Shrine', 'Shrine'), ('Jankaran', 'Jankaran'), ('Cinema', 'Cinema'), ('Family', 'Visiting Family (Sele arham)'), ('sport', 'Sport'), ('Poem', 'Poem'), ('Garden', 'Garden')], error_messages={'invalid_choice': 'Invalid choice for leisure type.', 'required': 'Leisure type is required.'}, help_text='Select the types of leisure activities the user enjoys.', max_length=97, verbose_name='Leisure Type'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='eyes_color',
            field=models.CharField(choices=[('Green', 'Green'), ('Light Blue', 'Light Blue'), ('Hazel', 'Hazel'), ('Darken Blue', 'Darken Blue'), ('Grey', 'Grey'), ('Honey', 'Honey'), ('Purple', 'Purple'), ('Light Brown', 'Light Brown'), ('Deep Brown', 'Deep Brown'), ('Black', 'Black')], error_messages={'invalid_choice': 'Invalid choice for eyes color.', 'required': 'Eyes color is required.'}, help_text='Select the eyes color of the user.', max_length=20, verbose_name='Eyes Color'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='skin_color',
            field=models.CharField(choices=[('Very Bright', 'Very Bright'), ('Bor', 'Bor'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Greenish', 'Greenish'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Greenish', 'Bright Greenish'), ('other', 'Other')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the user.', max_length=20, verbose_name='Skin Color'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_someone_with_marriage_experience',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Never', 'Never'), ('Divorced No Life', 'Divorced No Life'), ('Divorced No Child', 'Divorced No Child'), ('Divorced Have Boy', 'Divorced Have Boy'), ('Divorced Have Girl', 'Divorced Have Girl')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for marriage with someone with marriage experience.', 'required': 'Marriage with someone with marriage experience is required.'}, help_text='Select the preference for marriage with someone with marriage experience.', max_length=77, verbose_name='Marriage with Someone with Marriage Experience'),
        ),
        migrations.AlterField(
            model_name='preferredwifephysicalinformation',
            name='skin_color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Very Bright', 'Very Bright'), ('Bor', 'Bor'), ('Fair', 'Fair'), ('White', 'White'), ('Wheat', 'Wheat'), ('Greenish', 'Greenish'), ('Olive', 'Olive'), ('Darken', 'Darken'), ('Black', 'Black'), ('Bright Brown', 'Bright Brown'), ('Darken Brown', 'Darken Brown'), ('Bright', 'Bright'), ('Yellow', 'Yellow'), ('Whitish White', 'Whitish White'), ('Red & White', 'Red & White'), ('Bright Greenish', 'Bright Greenish'), ('other', 'Other')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for skin color.', 'required': 'Skin color is required.'}, help_text='Select the skin color of the preferred wife.', max_length=148, verbose_name='Skin Color'),
        ),
    ]
