# Generated by Django 4.2.20 on 2025-07-06 18:21

import core.utils.validators.subject_validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_remove_familyinformation_kids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date_times', models.CharField(blank=True, error_messages={'blank': 'Preferred date times cannot be blank.', 'max_length': 'Preferred date times cannot exceed 255 characters.', 'null': 'Preferred date times cannot be null.'}, help_text="Enter your preferred date and times for meetings (e.g., 'Weekdays after 6 PM, Weekends anytime').", max_length=255, null=True, verbose_name='Preferred Date Times')),
                ('signup_fee_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card (Transfer to Card)')], error_messages={'blank': 'Signup fee type cannot be blank.', 'invalid_choice': 'Invalid choice for signup fee type.', 'null': 'Signup fee type cannot be null.'}, help_text='Select the payment method for the signup fee - Cash or Card (Transfer to Card).', max_length=50, null=True, verbose_name='Signup Fee Type')),
                ('account_number', models.CharField(blank=True, error_messages={'blank': 'Account number cannot be blank.', 'invalid': 'Invalid account number format.', 'max_length': 'Account number cannot exceed 20 characters.', 'null': 'Account number cannot be null.'}, help_text="Enter your bank account number (10-20 digits). This is required if you select 'Card' as payment method.", max_length=20, null=True, validators=[core.utils.validators.subject_validators.validate_account_number], verbose_name='Account Number')),
                ('bank', models.CharField(blank=True, error_messages={'blank': 'Bank name cannot be blank.', 'invalid': 'Invalid bank name format.', 'max_length': 'Bank name cannot exceed 100 characters.', 'null': 'Bank name cannot be null.'}, help_text='Enter the name of your bank (e.g., Melli, Mellat, Saderat, etc.).', max_length=100, null=True, validators=[core.utils.validators.subject_validators.validate_bank_name], verbose_name='Bank Name')),
                ('gender_target', models.CharField(blank=True, error_messages={'blank': 'Gender target cannot be blank.', 'invalid_choice': 'Invalid choice for gender target.', 'null': 'Gender target cannot be null.'}, help_text='Select the gender you are interested in (Man/Woman).', max_length=100, null=True, verbose_name='Gender Target')),
                ('amount', models.CharField(blank=True, error_messages={'blank': 'Amount cannot be blank.', 'invalid': 'Invalid amount format.', 'max_length': 'Amount cannot exceed 20 characters.', 'null': 'Amount cannot be null.'}, help_text='Enter the amount in Rials. Only numbers and decimal point are allowed.', max_length=20, null=True, validators=[core.utils.validators.subject_validators.validate_amount], verbose_name='Amount')),
                ('professional_opinion', models.TextField(blank=True, error_messages={'blank': 'Professional opinion cannot be blank.', 'max_length': 'Professional opinion cannot exceed 1000 characters.', 'null': 'Professional opinion cannot be null.'}, help_text='Enter any professional opinion or notes about the subject (max 1000 characters).', max_length=1000, null=True, verbose_name='Professional Opinion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_details', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subject Details',
                'verbose_name_plural': 'Subject Details',
            },
        ),
    ]
