# Generated by Django 4.2.20 on 2025-07-10 15:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_subjectdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('boy', 'Boy'), ('girl', 'Girl'), ('seperated', 'Seperated'), ('deceased', 'Deceased')], error_messages={'invalid_choice': 'Invalid choice for gender.', 'required': 'Gender is required.'}, help_text='Select the gender of the user.', max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tamin', 'Tamin'), ('takmili', 'Takmili'), ('darmani', 'Darmani'), ('niroo_mosalah', 'Niroo Mosalah'), ('ommr', 'Ommr'), ('iran', 'Iran'), ('asia', 'Asia'), ('dana', 'Dana'), ('moalem', 'Moalem'), ('parsian', 'Parsian'), ('pasargad', 'Pasargad'), ('Saman', 'Saman'), ('melat', 'Melat'), ('ma', 'Ma'), ('alborz_insurance', 'Alborz'), ('kosar', 'Kosar'), ('karafarin', 'Karafarin'), ('novin', 'Novin'), ('day', 'Day'), ('sarmad', 'Sarmad'), ('Razi', 'Razi'), ('taavon', 'Taavon'), ('hafez', 'Hafez'), ('etkayii', 'Etkayii Iranian'), ('tejaratno', 'Tejarat No'), ('khavermiane', 'Khavermiane'), ('hekmat', 'Hekmat Saba'), ('tosehe', 'Tosehe'), ('other', 'Other')], error_messages={'invalid_choice': 'Invalid choice for insurance type.', 'required': 'Insurance type is required.'}, help_text='Select the type of insurance the user has.', max_length=212, null=True, verbose_name='Insurance Type'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='leisure_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Park', 'Park'), ('Trip', 'Trip'), ('working_from_home', 'Working from home'), ('Mobile', 'Mobile'), ('Reading', 'Reading'), ('Shrine', 'Shrine'), ('Jankaran', 'Jankaran'), ('Cinema', 'Cinema'), ('Family', 'Visiting Family (Sele arham)'), ('sport', 'Sport'), ('Poem', 'Poem'), ('Garden', 'Garden')], error_messages={'invalid_choice': 'Invalid choice for leisure type.', 'required': 'Leisure type is required.'}, help_text='Select the types of leisure activities the user enjoys.', max_length=90, verbose_name='Leisure Type'),
        ),
    ]
