# Generated by Django 4.2.20 on 2025-07-10 15:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_alter_personalinformation_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredwifeintellectualinformation',
            name='additional_explnation_marriage_with_someone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marriage with Someone with Marriage Experience Additional Explnations'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_someone_with_marriage_experience',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Never', 'Never'), ('Divorced Virgin', 'Divorced Virgin'), ('Divorced No Custody', 'Divorced No Custody'), ('Divorced No Life', 'Divorced No Life'), ('Divorced No Child', 'Divorced No Child'), ('Divorced Have Boy', 'Divorced Have Boy'), ('Divorced Have Girl', 'Divorced Have Girl'), ('Spouse Died', 'Spouse Died')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for marriage with someone with marriage experience.', 'required': 'Marriage with someone with marriage experience is required.'}, help_text='Select the preference for marriage with someone with marriage experience.', max_length=125, verbose_name='Marriage with Someone with Marriage Experience'),
        ),
    ]
