# Generated by Django 4.2.20 on 2025-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_preferredwifeintellectualinformation_additional_explnation_marriage_with_someone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_pay_status',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('two_years', 'Two Years')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial pay status.', 'required': 'Ex-spouse financial pay status is required.'}, help_text='Select the payment status for the ex-spouse financial amount.', max_length=50, null=True, verbose_name='Ex-Spouse Financial Pay Status'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='ex_spouse_financial_status',
            field=models.CharField(blank=True, choices=[('rights', 'Rights'), ('settled', 'Settled'), ('creditor', 'Creditor'), ('debtor', 'Debtor'), ('female', 'Female')], error_messages={'invalid_choice': 'Invalid choice for ex-spouse financial status.', 'required': 'Ex-spouse financial status is required.'}, help_text='Select the financial status with the ex-spouse.', null=True, verbose_name='Ex-Spouse Financial Status'),
        ),
    ]
