# Generated by Django 4.2.20 on 2025-07-10 17:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0121_alter_financialinformation_ex_spouse_financial_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Engagement', 'Engagement'), ('Contract', 'Contract'), ('Wedding', 'Wedding'), ('None', 'None')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for engagement or wedding status.', 'required': 'Engagement or wedding status is required.'}, help_text='If user has engagment or related history', max_length=32, verbose_name='Person Status'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('boy', 'Boy'), ('girl', 'Girl'), ('seperated', 'Seperated'), ('deceased', 'Deceased')], error_messages={'invalid_choice': 'Invalid choice for gender.', 'required': 'Gender is required.'}, help_text='Select the gender of the user.', max_length=37, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='body_and_face',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Suitable', 'Suitable'), ('Nice Face', 'Nice Face'), ('Nice Body', 'Nice Body'), ('Looks Older', 'Looks Older'), ('Looks Younger', 'Looks Younger'), ('Satisfied', 'Satisfied'), ('None', 'None')], error_messages={'invalid_choice': 'Invalid choice for body and face.', 'required': 'Body and face is required.'}, help_text='Select the body and face characteristics of the user.', max_length=92, verbose_name='Body and Face'),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='appearance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Religious', 'Religious'), ('Norm', 'Norm'), ('Cador', 'Cador'), ('Manto', 'Manto'), ('Sport & Modern', 'Sport & Modern')], error_messages={'invalid_choice': 'Invalid choice for appearance type.', 'required': 'Appearance type is required.'}, help_text='Select the appearance type of the preferred wife.', max_length=41, verbose_name='Appearance Type'),
        ),
        migrations.AlterField(
            model_name='preferredwifepersonalinformation',
            name='after_marriage_residence_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exactly Qom', 'Exactly Qom'), ('Near Qom', 'Near Qom'), ('Mega Cities', 'Mega Cities'), ('Anywhere in Iran', 'Anywhere in Iran'), ('Villages Near Qom', 'Villages Near Qom'), ('Environs Near Qom', 'Environs Near Qom'), ('Foreign Country', 'Foreign Country'), ('Agreement', 'Agreement')], db_index=True, error_messages={'invalid_choice': 'Invalid choice for after marriage residence location.', 'required': 'After marriage residence location is required.'}, help_text='Select the after marriage residence location of the preferred wife.', max_length=111, verbose_name='After Marriage Residence Location'),
        ),
    ]
