# Generated by Django 4.2.20 on 2025-07-11 16:15

import core.utils.validators.preferred_wife_validators
import core.utils.validators.user_validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0122_alter_engagementorweddingstatus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intellectualinformation',
            name='fasting_explanation',
            field=models.CharField(blank=True, error_messages={'required': 'Please provide an explanation if you cannot fast due to sickness.'}, help_text='If you cannot fast due to sickness, please explain your condition.', max_length=150, null=True, verbose_name='Fasting Explanation (sickness that makes him not be able to fast)'),
        ),
        migrations.AlterField(
            model_name='intellectualinformation',
            name='opinion_woman_edu',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('disagree', 'Disagree'), ('agree', 'Agree'), ('depends_degree', 'Depends on the Degree'), ('depends_spouse_opinion', 'Depends On Spouse Opinion')], error_messages={'invalid_choice': "The selected option for a woman's education is not valid.", 'required': "Please provide your opinion about a woman's education."}, help_text="Choose your stance on women's education.", max_length=52, validators=[core.utils.validators.user_validators.IntellectualInformationValidator.validate_opinion_woman_edu], verbose_name="Opinion About Woman's Education"),
        ),
        migrations.AlterField(
            model_name='preferredwifeintellectualinformation',
            name='marriage_with_veteran_disabled_explanation',
            field=models.CharField(blank=True, error_messages={'max_length': 'Marriage With Disabled & Veteran Explanation cannot exceed 150 characters.', 'required': 'Marriage with disabled & Veteran Explanation is required.'}, help_text='Enter the Marriage With Disabled & Veteran Explanation', null=True, validators=[core.utils.validators.preferred_wife_validators.PreferredWifeIntellectualInformationValidator.validate_disabled_veteran_explanation], verbose_name='Marriage with Veteran & Disabled Person Explanation'),
        ),
    ]
