# Generated by Django 4.2.20 on 2025-08-23 14:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0123_alter_intellectualinformation_fasting_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinformation',
            name='number_of_brothers',
            field=models.PositiveSmallIntegerField(default=0, error_messages={'invalid': 'Number of brothers must be a positive number.', 'required': 'Number of brothers is required.'}, help_text='Enter the number of brothers you have.', verbose_name='Number of Brothers'),
        ),
        migrations.AddField(
            model_name='familyinformation',
            name='number_of_sisters',
            field=models.PositiveSmallIntegerField(default=0, error_messages={'invalid': 'Number of sisters must be a positive number.', 'required': 'Number of sisters is required.'}, help_text='Enter the number of sisters you have.', verbose_name='Number of Sisters'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='contract_length',
            field=models.CharField(default=0, help_text='Enter the length of the contract.', max_length=50, verbose_name='Contract Length'),
        ),
        migrations.AlterField(
            model_name='engagementorweddingstatus',
            name='living_length',
            field=models.CharField(default=0, help_text='Enter the length of living together.', max_length=50, verbose_name='Living Length'),
        ),
        migrations.AlterField(
            model_name='financialinformation',
            name='dowry_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mecca', 'Mecca'), ('iraq', 'Iraq'), ('syria', 'Syria'), ('gold', 'Gold'), ('money', 'Money'), ('land', 'Land'), ('car', 'Car'), ('garden', 'Garden'), ('house', 'House'), ('agreement', 'Agreement')], default='None', error_messages={'invalid_choice': 'Invalid choice for dowry type.', 'required': 'Dowry type is required.'}, help_text='Select the type of dowry Of Future Wife.', max_length=59, verbose_name='Future Spouse Dowry Type'),
        ),
        migrations.AlterField(
            model_name='groom',
            name='groom_or',
            field=models.CharField(choices=[('groom', 'Groomm'), ('zan_dadash', 'Zan Dadash')], error_messages={'invalid_choice': 'Selected value for groom is invalid.', 'required': 'Groom field is required.'}, help_text='Select the groom from the available options.', verbose_name='Groom or Zan Dadash'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='degree',
            field=models.CharField(blank=True, error_messages={'invalid_choice': 'Invalid choice for degree.', 'required': 'Degree is required.'}, help_text='Select the degree of the user.', max_length=150, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='insurance_years',
            field=models.PositiveIntegerField(blank=True, error_messages={'invalid': 'Invalid insurance years value.', 'max_value': 'Insurance years cannot exceed 60.', 'required': 'Insurance years are required.'}, help_text='Enter the number of years the user has had insurance.', null=True, verbose_name='Insurance Years'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='leisure_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Park', 'Park'), ('Trip', 'Trip'), ('working_from_home', 'Working from home'), ('Mobile', 'Mobile'), ('Reading', 'Reading'), ('Shrine', 'Shrine'), ('Jankaran', 'Jankaran'), ('Cinema', 'Cinema'), ('Family', 'Visiting Family (Sele arham)'), ('sport', 'Sport'), ('Poem', 'Poem'), ('Garden', 'Garden')], error_messages={'invalid_choice': 'Invalid choice for leisure type.', 'required': 'Leisure type is required.'}, help_text='Select the types of leisure activities the user enjoys.', max_length=90, null=True, verbose_name='Leisure Type'),
        ),
        migrations.AlterField(
            model_name='physicalinformation',
            name='medication_surgery_disease_type',
            field=models.CharField(default='None', error_messages={'max_length': 'Medication, surgery, or disease type cannot exceed 100 characters.'}, help_text='Specify the type of medication, surgery, or disease if applicable.', max_length=100, verbose_name='Medication/Surgery/Disease Type'),
        ),
    ]
