# Generated by Django 4.2.20 on 2026-02-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_familyinformation_number_of_brothers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresposeoriginality',
            name='future_spouse_originality',
            field=models.CharField(choices=[('فارس', 'فارس'), ('لر', 'لر'), ('ترک', 'ترک'), ('کرد', 'کرد'), ('لک', 'لک'), ('تات', 'تات'), ('عرب', 'عرب'), ('بلوچ', 'بلوچ')], error_messages={'invalid_choice': 'Invalid choice for future spouse originality.', 'required': 'Future spouse originality is required.'}, help_text='Select the originality of the future spouse.', verbose_name='Future Spouse Ethnicity'),
        ),
    ]
