# Generated by Django 4.2.20 on 2026-06-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_alter_futuresposeoriginality_future_spouse_originality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementorweddingstatus',
            options={'verbose_name': 'Engagement or Wedding Status', 'verbose_name_plural': 'Engagements or Weddings Statuses'},
        ),
        migrations.AlterModelOptions(
            name='financialinformation',
            options={'verbose_name': 'Financial Information', 'verbose_name_plural': 'Financial Information'},
        ),
        migrations.AlterModelOptions(
            name='physicalinformation',
            options={'verbose_name': 'Physical Information', 'verbose_name_plural': 'Physical Information'},
        ),
    ]
