# Generated by Django 4.2.20 on 2026-08-30 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_alter_engagementorweddingstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Bookmark',
                'verbose_name_plural': 'User Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bookmarked_user')},
            },
        ),
    ]
